In [ ]:
import sys
sys.path.append('../')
from source import Process
import pandas as pd
import re
import json
import numpy as np

Use cd-hit multiple times decreasing the cluster similarity cutoff to check redundancy

In [ ]:
NcrdClusters = Process.ClusterCounter("../data/filtered/ncrd95.tagged.fasta")
ResfinderClusters = Process.ClusterCounter("../data/filtered/resfinder.tagged.fasta")
CardClusters = Process.ClusterCounter("../data/filtered/card.tagged.fasta")
MegaresClusters = Process.ClusterCounter("../data/filtered/megares.tagged.fasta")
HmdClusters = Process.ClusterCounter("../data/filtered/hmd.tagged.fasta")
NdaroClusters = Process.ClusterCounter("../data/filtered/ndaro.tagged.fasta")

In [ ]:
ClusterLimits = pd.DataFrame({
    "Database": ["NCRD", "Resfinder", "CARD", "MEGARES", "HMD", "NDARO"],
    "100%": [NcrdClusters[0][0], ResfinderClusters[0][0], CardClusters[0][0], MegaresClusters[0][0], HmdClusters[0][0], NdaroClusters[0][0]],
    "95%":  [NcrdClusters[0][1], ResfinderClusters[0][1], CardClusters[0][1], MegaresClusters[0][1], HmdClusters[0][1], NdaroClusters[0][1]],
    "90%":  [NcrdClusters[0][2], ResfinderClusters[0][2], CardClusters[0][2], MegaresClusters[0][2], HmdClusters[0][2], NdaroClusters[0][2]],
    "85%":  [NcrdClusters[0][3], ResfinderClusters[0][3], CardClusters[0][3], MegaresClusters[0][3], HmdClusters[0][3], NdaroClusters[0][3]],
    "80%":  [NcrdClusters[0][4], ResfinderClusters[0][4], CardClusters[0][4], MegaresClusters[0][4], HmdClusters[0][4], NdaroClusters[0][4]],  
    "75%":  [NcrdClusters[0][5], ResfinderClusters[0][5], CardClusters[0][5], MegaresClusters[0][5], HmdClusters[0][5], NdaroClusters[0][5]],
    "70%":  [NcrdClusters[0][6], ResfinderClusters[0][6], CardClusters[0][6], MegaresClusters[0][6], HmdClusters[0][6], NdaroClusters[0][6]],
})
ClusterLimits = ClusterLimits.set_index("Database").T
ClusterLimits.columns.name = None
ClusterLimits.to_csv("../data/processed/cdhitclusters.defaultsettings.csv", index=True, sep = "\t")

Check the shared proteins with identity above 95% among databases.

In [30]:
PairWiseAlignment = pd.read_csv(
    "../data/filtered/AllDatabases.Paiwise.cov80.maxseq5.tsv", 
    sep = "\t",
    skipinitialspace=True, 
    header=None,
    names = "qseqid sseqid pident length qlen slen qstart qend sstart send evalue bitscore ppos full_qseq full_sseq".split(" ")
)

PairWiseAlignment["qseqtag"] = PairWiseAlignment["qseqid"].str.split("|").str[1]
PairWiseAlignment["sseqtag"] = PairWiseAlignment["sseqid"].str.split("|").str[1]
PairWiseAlignment["qseqid"] = PairWiseAlignment["qseqid"].str.split("|").str[0]
PairWiseAlignment["sseqid"] = PairWiseAlignment["sseqid"].str.split("|").str[0]
PairWiseAlignment = PairWiseAlignment.loc[PairWiseAlignment.pident >= 95]
PairWiseAlignment.replace({"RESFINDER":"ResFinder", "MEGARES":"MegaRes","HMDARG":"HMDARG-DB"}, inplace = True)
BlastPairWiseAlignmentPivoted = PairWiseAlignment.pivot_table(index="qseqtag", columns="sseqtag", values="pident", aggfunc="count").fillna(0)
BlastPairWiseAlignmentPivoted.index.name = None
BlastPairWiseAlignmentPivoted.columns.name = None
BlastPairWiseAlignmentPivoted.to_csv("../data/processed/BlastPairWiseAlignmentPivoted.cov80.maxseq1.csv", index=True, sep = "\t")

In [31]:
BlastPairWiseAlignmentPivoted

            CARD    HMD  MegaRes   NCRD  NDARO  ResFinder
CARD        5288   5237     7229   1466   7695       2212
HMD         7401  29172     7869   6302   5963       2668
MegaRes     8747   7448     4630   1582   6716       3191
NCRD        3830  12269     3748  17242   2844        811
NDARO      12812   8155    10082   1693   6647       2835
ResFinder   3854   3071     4012    573   2614        305

Standardize the resistance class of each protein

In [32]:
CardIndex = pd.read_csv(
    "../data/raw/card.index.tsv",
    sep = "\t"
)
CardDict = CardIndex.drop_duplicates(subset="ARO Accession", keep='first').set_index("ARO Accession").to_dict(orient="index")
## Duplicates
CardIndex.value_counts("ARO Accession")[:5]

ARO Accession
ARO:3002118    2
ARO:3003900    2
ARO:3003893    2
ARO:3000506    2
ARO:3003170    2
Name: count, dtype: int64

In [54]:
CardIndex.loc[CardIndex["ARO Accession"] == "ARO:3003900"]

,ARO Accession,CVTERM ID,Model Sequence ID,Model ID,Model Name,ARO Name,Protein Accession,DNA Accession,AMR Gene Family,Drug Class,Resistance Mechanism,CARD Short Name
1802,ARO:3003900,40602,4616,2379,Escherichia coli cyaA with mutation conferring...,Escherichia coli cyaA with mutation conferring...,CDJ73082.1,HG738867.1,antibiotic-resistant cya adenylate cyclase,phosphonic acid antibiotic,antibiotic target alteration,Ecol_cyaA_FOF
1803,ARO:3003900,40602,5882,2378,Escherichia coli CyaA with mutation conferring...,Escherichia coli cyaA with mutation conferring...,CDJ73082.1,HG738867.1,antibiotic-resistant cya adenylate cyclase,phosphonic acid antibiotic,antibiotic target alteration,Ecol_cyaA_FOF

In [33]:
NDAROIndex = pd.read_csv(
    "../data/raw/ndaro.index.tsv", 
    sep="\t")
NDAROIndex.fillna("Not Found", inplace=True)
NdaroDict = NDAROIndex.dropna(subset=["RefSeq protein"]).drop_duplicates(subset="RefSeq protein", keep='first').set_index("RefSeq protein").to_dict(orient="index")
NDAROIndex.value_counts("RefSeq protein")[:5]

RefSeq protein
Not Found         127
WP_000090315.1     61
WP_000918664.1     44
WP_003112576.1     33
WP_001212189.1     27
Name: count, dtype: int64

In [55]:
NDAROIndex.loc[NDAROIndex["RefSeq protein"] == "WP_000090315.1"]

,#Allele,Gene family,Product name,Scope,Type,Subtype,Class,Subclass,RefSeq protein,RefSeq nucleotide,GenBank protein,GenBank nucleotide,Curated RefSeq start,Links
9758,fusA_A160V,fusA,elongation factor G FusA,core,AMR,POINT,FUSIDIC ACID,FUSIDIC ACID,WP_000090315.1,NC_002758.2,BAB56709.1,BA000017.4,No,11
9759,fusA_A376V,fusA,elongation factor G FusA,core,AMR,POINT,FUSIDIC ACID,FUSIDIC ACID,WP_000090315.1,NC_002758.2,BAB56709.1,BA000017.4,No,11
9760,fusA_A655E,fusA,elongation factor G FusA,core,AMR,POINT,FUSIDIC ACID,FUSIDIC ACID,WP_000090315.1,NC_002758.2,BAB56709.1,BA000017.4,No,11
9761,fusA_A655P,fusA,elongation factor G FusA,core,AMR,POINT,FUSIDIC ACID,FUSIDIC ACID,WP_000090315.1,NC_002758.2,BAB56709.1,BA000017.4,No,11
9762,fusA_A655V,fusA,elongation factor G FusA,core,AMR,POINT,FUSIDIC ACID,FUSIDIC ACID,WP_000090315.1,NC_002758.2,BAB56709.1,BA000017.4,No,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9814,fusA_V407F,fusA,elongation factor G FusA,core,AMR,POINT,FUSIDIC ACID,FUSIDIC ACID,WP_000090315.1,NC_002758.2,BAB56709.1,BA000017.4,No,11
9815,fusA_V607I,fusA,elongation factor G FusA,core,AMR,POINT,FUSIDIC ACID,FUSIDIC ACID,WP_000090315.1,NC_002758.2,BAB56709.1,BA000017.4,No,11
9816,fusA_V90A,fusA,elongation factor G FusA,core,AMR,POINT,FUSIDIC ACID,FUSIDIC ACID,WP_000090315.1,NC_002758.2,BAB56709.1,BA000017.4,No,11
9817,fusA_V90I,fusA,elongation factor G FusA,core,AMR,POINT,FUSIDIC ACID,FUSIDIC ACID,WP_000090315.1,NC_002758.2,BAB56709.1,BA000017.4,No,11
9818,fusA_Y654N,fusA,elongation factor G FusA,core,AMR,POINT,FUSIDIC ACID,FUSIDIC ACID,WP_000090315.1,NC_002758.2,BAB56709.1,BA000017.4,No,11

In [34]:
sorted(NDAROIndex.Class.unique())

['AMINOCOUMARIN',
 'AMINOGLYCOSIDE',
 'AMINOGLYCOSIDE/BETA-LACTAM/QUINOLONE',
 'AMINOGLYCOSIDE/LINCOSAMIDE/MACROLIDE/PLEUROMUTILIN/TETRACYCLINE',
 'AMINOGLYCOSIDE/PHENICOL',
 'AMINOGLYCOSIDE/QUINOLONE',
 'ARSENIC',
 'AVILAMYCIN',
 'AZABICYCLOALKANE',
 'BACITRACIN',
 'BETA-LACTAM',
 'BETA-LACTAM/MACROLIDE/TETRACYCLINE',
 'BETA-LACTAM/PHENICOL/QUINOLONE',
 'BETA-LACTAM/PHENICOL/QUINOLONE/TETRACYCLINE',
 'BETA-LACTAM/QUINOLONE/TETRACYCLINE',
 'BETA-LACTAM/RIFAMYCIN',
 'BETA-LACTAM/TETRACYCLINE',
 'BLEOMYCIN',
 'CADMIUM',
 'CADMIUM/COBALT/NICKEL',
 'CADMIUM/LEAD/ZINC',
 'CHROMATE',
 'COLISTIN',
 'COPPER',
 'COPPER/GOLD',
 'COPPER/NICKEL',
 'COPPER/SILVER',
 'EDEINE',
 'EFFLUX',
 'FLUORIDE',
 'FOSFOMYCIN',
 'FOSMIDOMYCIN',
 'FUSIDIC ACID',
 'GLYCOPEPTIDE',
 'GLYCOPEPTIDE/LIPOPEPTIDE',
 'GOLD',
 'INTIMIN',
 'IONOPHORE',
 'ISONIAZID/TRICLOSAN',
 'LINCOSAMIDE',
 'LINCOSAMIDE/MACROLIDE',
 'LINCOSAMIDE/MACROLIDE/STREPTOGRAMIN',
 'LINCOSAMIDE/OXAZOLIDINONE',
 'LINCOSAMIDE/OXAZOLIDINONE/PHENICOL/PLEUROMUTILIN/STREPTOGRAMIN',
 'LINCOSAMIDE/PLEUROMUTILIN',
 'LINCOSAMIDE/PLEUROMUTILIN/STREPTOGRAMIN',
 'LINCOSAMIDE/STREPTOGRAMIN',
 'LIPOPEPTIDE',
 'LIPOPEPTIDE/RIFAMYCIN',
 'MACROLIDE',
 'MACROLIDE/OXAZOLIDINONE',
 'MACROLIDE/OXAZOLIDINONE/PHENICOL',
 'MACROLIDE/PHENICOL',
 'MACROLIDE/STREPTOGRAMIN',
 'MACROLIDE/STREPTOTHRICIN',
 'MERCURY',
 'MULTIDRUG',
 'MUPIROCIN',
 'NICKEL',
 'NITROFURAN',
 'NITROFURAN/PHENICOL/QUINOLONE/TETRACYCLINE',
 'NITROIMIDAZOLE',
 'Not Found',
 'OXAZOLIDINONE',
 'OXAZOLIDINONE/PHENICOL',
 'PHENICOL',
 'PHENICOL/QUINOLONE',
 'PHENICOL/QUINOLONE/TRIMETHOPRIM',
 'PLEUROMUTILIN',
 'POLYKETIDE',
 'QUATERNARY AMMONIUM',
 'QUINOLONE',
 'QUINOLONE/TRICLOSAN',
 'RIFAMYCIN',
 'SILVER',
 'SPIROPYRIMIDINETRIONE',
 'STREPTOGRAMIN',
 'STREPTOTHRICIN',
 'STX1',
 'STX2',
 'SULFONAMIDE',
 'TELLURIUM',
 'TETRACENOMYCIN',
 'TETRACYCLINE',
 'THIOSTREPTON',
 'TRICLOSAN',
 'TRIMETHOPRIM',
 'TRIMETHOPRIM-SULFAMETHOXAZOLE',
 'TUBERACTINOMYCIN']

In [35]:
ResfinderIndex = pd.read_csv(
    "../data/raw/resfinder.phenotypes.tsv", 
    sep="\t")
ResfinderDict = ResfinderIndex.drop_duplicates(subset="Gene_accession no.", keep='first').set_index("Gene_accession no.").to_dict(orient="index")
ResfinderIndex.value_counts("Gene_accession no.")[:5]

Gene_accession no.
vgb(B)_1_AF015628    1
ARR-2_1_HQ141279     1
ARR-3_1_JF806499     1
ARR-3_4_FM207631     1
ARR-4_1_EF660562     1
Name: count, dtype: int64

In [36]:
SCHEMAS = {
    "CARD": {
        "AROSplitPoint": 3,
        "IndexInfo": CardDict
    },
    "NDARO": {
        "AccSplitPoint": 0,
        "IndexInfo": NdaroDict
    },
    "MEGARES": {
        "DrugClassSplitPoint": 3,
        "NameSplitPoint": -1
    },
    "HMD": {
        "DrugClassSplitPoint": 4,
        "NameSplitPoint": 5
    },
    "NCRD": {
        "DrugClassSplitPoint": 4,
        "NameSplitPoint": 2
    },
    "RESFINDER": {
        "DrugClassSplitPoint": -1,
        "NameSplitPoint": 1,
        "IndexInfo": ResfinderDict
    }
}

In [37]:
MetaDict = Process.CreateMetadataFile(
    "../data/filtered/AllDatabases.tagged.fasta_ids",
    SCHEMAS
    )

In [38]:
MetaDict

{'CARD_0': {'Drug Class': 'cephalosporin', 'Name': 'CblA-1'},
 'CARD_1': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-52'},
 'CARD_2': {'Drug Class': 'diaminopyrimidine antibiotic', 'Name': 'dfrF'},
 'CARD_3': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-130'},
 'CARD_4': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'NDM-6'},
 'CARD_5': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'ACT-35'},
 'CARD_6': {'Drug Class': 'penicillin beta-lactam', 'Name': 'CARB-5'},
 'CARD_7': {'Drug Class': 'lincosamide antibiotic;macrolide antibiotic;streptogramin A antibiotic;streptogramin B antibiotic;streptogramin antibiotic',
  'Name': 'Erm(34)'},
 'CARD_8': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-126'},
 'CARD_9': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'LRA-12'},
 'CARD_10': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-72'},
 'CARD_11': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-59'},
 'CARD_12': {'Drug Class': 'carbapenem;cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'KPC-10'},
 'CARD_13': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-212'},
 'CARD_14': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'IMP-2'},
 'CARD_15': {'Drug Class': 'cephalosporin', 'Name': 'CMY-1'},
 'CARD_16': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-329'},
 'CARD_17': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'ACT-10'},
 'CARD_18': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-371'},
 'CARD_19': {'Drug Class': 'fusidane antibiotic', 'Name': 'fusB'},
 'CARD_20': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-121'},
 'CARD_21': {'Drug Class': 'cephalosporin;monobactam', 'Name': 'VEB-3'},
 'CARD_22': {'Drug Class': 'lincosamide antibiotic', 'Name': 'lnuA'},
 'CARD_23': {'Drug Class': 'penicillin beta-lactam', 'Name': 'OXA-45'},
 'CARD_24': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OXA-226'},
 'CARD_25': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-155'},
 'CARD_26': {'Drug Class': 'cephalosporin', 'Name': 'DHA-15'},
 'CARD_27': {'Drug Class': 'macrolide antibiotic;streptogramin antibiotic',
  'Name': 'msrE'},
 'CARD_28': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OXY-6-3'},
 'CARD_29': {'Drug Class': 'phosphonic acid antibiotic', 'Name': 'FosA2'},
 'CARD_30': {'Drug Class': 'aminoglycoside antibiotic', 'Name': "APH(3')-Va"},
 'CARD_31': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'AAC(3)-Ia'},
 'CARD_32': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrB58'},
 'CARD_33': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'rmtH'},
 'CARD_34': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OXY-6-1'},
 'CARD_35': {'Drug Class': 'carbapenem;cephalosporin;monobactam;penicillin beta-lactam;phenicol antibiotic',
  'Name': 'golS'},
 'CARD_36': {'Drug Class': 'disinfecting agents and antiseptics;nucleoside antibiotic',
  'Name': 'mdtP'},
 'CARD_37': {'Drug Class': 'cephalosporin', 'Name': 'CMY-114'},
 'CARD_38': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-60'},
 'CARD_39': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-90'},
 'CARD_40': {'Drug Class': 'carbapenem', 'Name': 'SME-2'},
 'CARD_41': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'AAC(3)-IIIc'},
 'CARD_42': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OXY-2-2'},
 'CARD_43': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'MOX-5'},
 'CARD_44': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-34'},
 'CARD_45': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-69'},
 'CARD_46': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-7'},
 'CARD_47': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-24'},
 'CARD_48': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrB47'},
 'CARD_49': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OXA-256'},
 'CARD_50': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrS6'},
 'CARD_51': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-330'},
 'CARD_52': {'Drug Class': 'cephalosporin', 'Name': 'CMY-42'},
 'CARD_53': {'Drug Class': 'aminoglycoside antibiotic', 'Name': "AAC(6')-Ib"},
 'CARD_54': {'Drug Class': 'cephalosporin', 'Name': 'CMY-70'},
 'CARD_55': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'GES-21'},
 'CARD_56': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-41'},
 'CARD_57': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-391'},
 'CARD_58': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-132'},
 'CARD_59': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'aadA23'},
 'CARD_60': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'NDM-10'},
 'CARD_61': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrB66'},
 'CARD_62': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-42'},
 'CARD_63': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OXA-35'},
 'CARD_64': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-18'},
 'CARD_65': {'Drug Class': 'fusidane antibiotic', 'Name': 'fusH'},
 'CARD_66': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-79'},
 'CARD_67': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-47'},
 'CARD_68': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-16'},
 'CARD_69': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'VIM-37'},
 'CARD_70': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'ACT-29'},
 'CARD_71': {'Drug Class': 'cephalosporin', 'Name': 'FOX-3'},
 'CARD_72': {'Drug Class': 'carbapenem;cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'PER-4'},
 'CARD_73': {'Drug Class': 'carbapenem;cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'GIM-1'},
 'CARD_74': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'IMP-42'},
 'CARD_75': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-102'},
 'CARD_76': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-116'},
 'CARD_77': {'Drug Class': 'cephalosporin', 'Name': 'CMY-55'},
 'CARD_78': {'Drug Class': 'fluoroquinolone antibiotic;macrolide antibiotic;penicillin beta-lactam',
  'Name': 'gadX'},
 'CARD_79': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-42'},
 'CARD_80': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-105'},
 'CARD_81': {'Drug Class': 'cephalosporin', 'Name': 'CMY-79'},
 'CARD_82': {'Drug Class': 'cephalosporin', 'Name': 'CMY-56'},
 'CARD_83': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-426'},
 'CARD_84': {'Drug Class': 'cephalosporin', 'Name': 'CMY-48'},
 'CARD_85': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrB38'},
 'CARD_86': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-109'},
 'CARD_87': {'Drug Class': 'cephalosporin;monobactam', 'Name': 'TLA-2'},
 'CARD_88': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-12'},
 'CARD_89': {'Drug Class': 'penicillin beta-lactam', 'Name': 'OXA-61'},
 'CARD_90': {'Drug Class': 'penicillin beta-lactam', 'Name': 'CARB-4'},
 'CARD_91': {'Drug Class': 'phenicol antibiotic', 'Name': 'catB9'},
 'CARD_92': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-43'},
 'CARD_93': {'Drug Class': 'carbapenem;cephalosporin;monobactam',
  'Name': 'PDC-8'},
 'CARD_94': {'Drug Class': 'lincosamide antibiotic;macrolide antibiotic;streptogramin A antibiotic;streptogramin B antibiotic;streptogramin antibiotic',
  'Name': 'ErmE'},
 'CARD_95': {'Drug Class': 'aminoglycoside antibiotic', 'Name': "AAC(6')-Iu"},
 'CARD_96': {'Drug Class': 'cephalosporin;monobactam', 'Name': 'VEB-5'},
 'CARD_97': {'Drug Class': 'diaminopyrimidine antibiotic', 'Name': 'dfrA13'},
 'CARD_98': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-87'},
 'CARD_99': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrB18'},
 'CARD_100': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'LRA-9'},
 'CARD_101': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'VIM-12'},
 'CARD_102': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'aadA4'},
 'CARD_103': {'Drug Class': 'fluoroquinolone antibiotic;macrolide antibiotic;penicillin beta-lactam',
  'Name': 'mdtF'},
 'CARD_104': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'VIM-34'},
 'CARD_105': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-64'},
 'CARD_106': {'Drug Class': 'carbapenem', 'Name': 'IND-7'},
 'CARD_107': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-182'},
 'CARD_108': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-183'},
 'CARD_109': {'Drug Class': 'lincosamide antibiotic;oxazolidinone antibiotic;phenicol antibiotic;pleuromutilin antibiotic;streptogramin A antibiotic;streptogramin antibiotic',
  'Name': 'clbB'},
 'CARD_110': {'Drug Class': 'macrolide antibiotic', 'Name': 'srmB'},
 'CARD_111': {'Drug Class': 'phosphonic acid antibiotic', 'Name': 'FosX'},
 'CARD_112': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-112'},
 'CARD_113': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-50'},
 'CARD_114': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-198'},
 'CARD_115': {'Drug Class': 'rifamycin antibiotic', 'Name': 'arr-8'},
 'CARD_116': {'Drug Class': 'rifamycin antibiotic', 'Name': 'rgt1438'},
 'CARD_117': {'Drug Class': 'carbapenem', 'Name': 'SME-5'},
 'CARD_118': {'Drug Class': 'cephalosporin', 'Name': 'CMY-9'},
 'CARD_119': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': "APH(2'')-Ie"},
 'CARD_120': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrB10'},
 'CARD_121': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': "AAC(6')-IIb"},
 'CARD_122': {'Drug Class': 'carbapenem', 'Name': 'cphA7'},
 'CARD_123': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'IMP-12'},
 'CARD_124': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-229'},
 'CARD_125': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-98'},
 'CARD_126': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-27'},
 'CARD_127': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-92'},
 'CARD_128': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'aadA12'},
 'CARD_129': {'Drug Class': 'phenicol antibiotic', 'Name': 'catB3'},
 'CARD_130': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OKP-A-15'},
 'CARD_131': {'Drug Class': 'aminocoumarin antibiotic;aminoglycoside antibiotic',
  'Name': 'cpxA'},
 'CARD_132': {'Drug Class': 'fluoroquinolone antibiotic;tetracycline antibiotic',
  'Name': 'adeF'},
 'CARD_133': {'Drug Class': 'cephalosporin;disinfecting agents and antiseptics;fluoroquinolone antibiotic;moenomycin antibiotic;penicillin beta-lactam;peptide antibiotic;tetracycline antibiotic',
  'Name': 'mgrA'},
 'CARD_134': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-195'},
 'CARD_135': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': "AAC(6')-Iaf"},
 'CARD_136': {'Drug Class': 'diaminopyrimidine antibiotic', 'Name': 'dfrA21'},
 'CARD_137': {'Drug Class': 'lincosamide antibiotic;macrolide antibiotic',
  'Name': 'myrA'},
 'CARD_138': {'Drug Class': 'lincosamide antibiotic;pleuromutilin antibiotic;streptogramin A antibiotic;streptogramin antibiotic',
  'Name': 'vgaALC'},
 'CARD_139': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-236'},
 'CARD_140': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-56'},
 'CARD_141': {'Drug Class': 'carbapenem;cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'KPC-8'},
 'CARD_142': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-376'},
 'CARD_143': {'Drug Class': 'glycopeptide antibiotic', 'Name': 'vanN'},
 'CARD_144': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'VIM-29'},
 'CARD_145': {'Drug Class': 'tetracycline antibiotic', 'Name': 'tet(42)'},
 'CARD_146': {'Drug Class': 'tetracycline antibiotic', 'Name': 'tet(45)'},
 'CARD_147': {'Drug Class': 'tetracycline antibiotic', 'Name': 'tet(E)'},
 'CARD_148': {'Drug Class': 'peptide antibiotic', 'Name': 'tsnR'},
 'CARD_149': {'Drug Class': 'cephalosporin', 'Name': 'CMY-39'},
 'CARD_150': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'VIM-17'},
 'CARD_151': {'Drug Class': 'aminoglycoside antibiotic;fluoroquinolone antibiotic;phosphonic acid antibiotic',
  'Name': 'fosA5'},
 'CARD_152': {'Drug Class': 'phenicol antibiotic',
  'Name': 'Streptomyces lividans cmlR'},
 'CARD_153': {'Drug Class': 'glycopeptide antibiotic',
  'Name': 'vanR gene in vanB cluster'},
 'CARD_154': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'IMP-33'},
 'CARD_155': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'IMP-19'},
 'CARD_156': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-78'},
 'CARD_157': {'Drug Class': 'rifamycin antibiotic', 'Name': 'arr-4'},
 'CARD_158': {'Drug Class': 'cephalosporin', 'Name': 'CfxA2'},
 'CARD_159': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-24'},
 'CARD_160': {'Drug Class': 'cephalosporin', 'Name': 'CMY-25'},
 'CARD_161': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'IMP-51'},
 'CARD_162': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrA5'},
 'CARD_163': {'Drug Class': 'cephalosporin', 'Name': 'DHA-19'},
 'CARD_164': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'GES-14'},
 'CARD_165': {'Drug Class': 'disinfecting agents and antiseptics;fluoroquinolone antibiotic',
  'Name': 'arlS'},
 'CARD_166': {'Drug Class': 'glycylcycline;tetracycline antibiotic',
  'Name': 'adeS'},
 'CARD_167': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OCH-1'},
 'CARD_168': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-232'},
 'CARD_169': {'Drug Class': 'penicillin beta-lactam', 'Name': 'OXA-12'},
 'CARD_170': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-348'},
 'CARD_171': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-89'},
 'CARD_172': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-19'},
 'CARD_173': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-195'},
 'CARD_174': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-199'},
 'CARD_175': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-38'},
 'CARD_176': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-121'},
 'CARD_177': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-61'},
 'CARD_178': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-58'},
 'CARD_179': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-56'},
 'CARD_180': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-138'},
 'CARD_181': {'Drug Class': 'cephalosporin', 'Name': 'SRT-1'},
 'CARD_182': {'Drug Class': 'penicillin beta-lactam', 'Name': 'LEN-14'},
 'CARD_183': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OCH-3'},
 'CARD_184': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-101'},
 'CARD_185': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OXY-2-8'},
 'CARD_186': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'VIM-43'},
 'CARD_187': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'APH(4)-Ia'},
 'CARD_188': {'Drug Class': 'phosphonic acid antibiotic', 'Name': 'FomA'},
 'CARD_189': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'GES-12'},
 'CARD_190': {'Drug Class': 'cephalosporin', 'Name': 'CMY-105'},
 'CARD_191': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-35'},
 'CARD_192': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-206'},
 'CARD_193': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OXA-21'},
 'CARD_194': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-121'},
 'CARD_195': {'Drug Class': 'peptide antibiotic', 'Name': 'bcrC'},
 'CARD_196': {'Drug Class': 'penicillin beta-lactam', 'Name': 'LEN-9'},
 'CARD_197': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'npmA'},
 'CARD_198': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OKP-A-12'},
 'CARD_199': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-92'},
 'CARD_200': {'Drug Class': 'cephalosporin', 'Name': 'CMY-100'},
 'CARD_201': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'GES-3'},
 'CARD_202': {'Drug Class': 'cephalosporin;monobactam', 'Name': 'MIR-2'},
 'CARD_203': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-88'},
 'CARD_204': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-113'},
 'CARD_205': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OKP-B-3'},
 'CARD_206': {'Drug Class': 'cephalosporin;disinfecting agents and antiseptics;fluoroquinolone antibiotic;glycylcycline;penicillin beta-lactam;phenicol antibiotic;rifamycin antibiotic;tetracycline antibiotic',
  'Name': 'sdiA'},
 'CARD_207': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-422'},
 'CARD_208': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-178'},
 'CARD_209': {'Drug Class': 'carbapenem', 'Name': 'imiH'},
 'CARD_210': {'Drug Class': 'penicillin beta-lactam', 'Name': 'LEN-21'},
 'CARD_211': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrS8'},
 'CARD_212': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-181'},
 'CARD_213': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'ACT-19'},
 'CARD_214': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-137'},
 'CARD_215': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-83'},
 'CARD_216': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'ACT-30'},
 'CARD_217': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-152'},
 'CARD_218': {'Drug Class': 'penicillin beta-lactam', 'Name': 'OXA-9'},
 'CARD_219': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-164'},
 'CARD_220': {'Drug Class': 'phenicol antibiotic', 'Name': 'cmlA5'},
 'CARD_221': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-126'},
 'CARD_222': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-158'},
 'CARD_223': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OKP-B-9'},
 'CARD_224': {'Drug Class': 'lincosamide antibiotic;macrolide antibiotic;streptogramin antibiotic',
  'Name': 'ermZ'},
 'CARD_225': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': "APH(3')-VIIa"},
 'CARD_226': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'APH(9)-Ia'},
 'CARD_227': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-150'},
 'CARD_228': {'Drug Class': 'cephalosporin', 'Name': 'CMY-21'},

In [39]:
PairWiseAlignment = pd.read_csv(
    "../data/filtered/AllDatabases.Paiwise.cov80.maxseq5.tsv", 
    sep = "\t",
    skipinitialspace=True, 
    header=None,
    names = "qseqid sseqid pident length qlen slen qstart qend sstart send evalue bitscore ppos full_qseq full_sseq".split(" ")
)
PairWiseAlignment["qcov"] = np.round((PairWiseAlignment["qend"] - PairWiseAlignment["qstart"] + 1) / (PairWiseAlignment["qlen"]) * 100, 2)
PairWiseAlignment["scov"] = np.round((PairWiseAlignment["send"] - PairWiseAlignment["sstart"] + 1) / (PairWiseAlignment["slen"]) * 100, 2)
PairWiseAlignment["qseqtag"] = PairWiseAlignment["qseqid"].str.split("|").str[1]
PairWiseAlignment["sseqtag"] = PairWiseAlignment["sseqid"].str.split("|").str[1]
PairWiseAlignment["qseqid"] = PairWiseAlignment["qseqid"].str.split("|").str[0]
PairWiseAlignment["sseqid"] = PairWiseAlignment["sseqid"].str.split("|").str[0]

In [40]:
PairWiseDictSource = PairWiseAlignment[["qseqid","full_qseq"]].set_index("qseqid").to_dict()["full_qseq"]
PairWiseDictTarget = PairWiseAlignment[["sseqid","full_sseq"]].set_index("sseqid").to_dict()["full_sseq"]

In [41]:
PairWiseDictTarget

{'MEGARES_1086': 'MKAYFIAILTLFTCIATVVRAQQMSELENRIDSLLNGKKATVGIAVWTDKGDMLRYNDHVHFPLLSVFKFHVALAVLDKMDKQSISLDSIVSIKASQMPPNTYSPLRKKFPDQDFTITLRELMQYSISQSDNNACDILIEYAGGIKHINDYIHRLSIDSFNLSETEDGMHSSFEAVYRNWSTPSAMVRLLRTADEKELFSNKELKDFLWQTMIDTETGANKLKGMLPAKTVVGHKTGSSDRNADGMKTADNDAGLVILPDGRKYYIAAFVMDSYETDEDNANIIARISRMVYDAMR',
 'MEGARES_1087': 'MKAYFIAILTLFTCIATVVRAQQMSELENRIDSLLNGKKATVGIAVWTDKGDMLRYNDHVHFPLLSVFKFHVALAVLDKMDKQSISLDSIVSIKASQMPPNTYSPLRKKFPDQDFTITLRELMQYSISQSDNNACDILIEYAGGIKHINDYIHRLSIDSFNLSETEDGMHSSFEAVYRNWSTPSAMVRLLRTADEKELFSNKELKDFLWQTMIDTETGANKLKGMLPAKTVVGHKTGSSDRNADGMKTADNDAGLVILPDGRKYYIAAFVMDSYETDEDNANIIARISRMVYDAMR',
 'NDARO_1066': 'MKAYFIAILTLFTCIATVVRAQQMSELENRIDSLLNGKKATVGIAVWTDKGDMLRYNDHVHFPLLSVFKFHVALAVLDKMDKQSISLDSIVSIKASQMPPNTYSPLRKKFPDQDFTITLRELMQYSISQSDNNACDILIEYAGGIKHINDYIHRLSIDSFNLSETEDGMHSSFEAVYRNWSTPSAMVRLLRTADEKELFSNKELKDFLWQTMIDTETGANKLKGMLPAKTVVGHKTGSSDRNADGMKTADNDAGLVILPDGRKYYIAAFVMDSYETDEDNANIIARISRMVYDAMR',
 'NCRD_32754': 'MKAYFIAILTLFTCIATVVRAQQMSELENRIDSLLNGKKATVGIAVWTDKGDMLRYNDHVHFPLLSVFKFHVALAVLDKMDKQSISLDSIVSIKASQMPPNTYSPLRKKFPDQDFTITLRELMQYSISQSDNNACDILIEYAGGIKHINDYIHRLSIDSFNLSETEDGMHSSFEAVYRNWSTPSAMVRLLRTADEKELFSNKELKDFLWQTMIDTETGANKLKGMLPAKTVVGHKTGSSDRNADGMKTADNDAGLVILPDGRKYYIAAFVMDSYETDEDNANIIARISRMVYDAMRRQGGYW',
 'HMD_10110': 'MPLKEIEVMKAYFIAILTLFTCIATVVRAQQMSELENRIDSLLNGKKSTVGIAVWTDKGDMLRYNDHVHFPLLSVFKFHVALAVLDKMDKQSISLDSIVSIKASQMPPNTYSPLRKKFPDQDFTITLRELMQYSISQSDNNACDILIEYAGGIKHINDYIHRLSIDSFNLSETEDGMHSSFEAVYRNWSTPSAMVRLLRTADEKELFSNKELKDFLWQTMIDTETGANKLKGMLPAKTVVGHKTGSSDRNADGMKTADNDAGLVILPDGRKYYIAAFVMDSYETDEDNANIIARISRMVYDAMR',
 'HMD_829': 'MRYIRLCIISLLAALPLAVHASPQPLEQIKQSESQLSGRVGMIEMDLASGRTLTAWRADERFPMISTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLAIVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARDTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR',
 'MEGARES_4627': 'MRYIRLCIISLLAALPLAVHASPQPLEQIKQSESQLSGRVGMIEMDLASGRTLTAWRADERFPMISTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLAIVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARDTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR',
 'NDARO_8827': 'MRYIRLCIISLLAALPLAVHASPQPLEQIKQSESQLSGRVGMIEMDLASGRTLTAWRADERFPMISTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLAIVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARDTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR',
 'RESFINDER_1099': 'MRYIRLCIISLLAALPLAVHASPQPLEQIKQSESQLSGRVGMIEMDLASGRTLTAWRADERFPMISTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLAIVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARDTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR',
 'CARD_127': 'MRYIRLCIISLLATLPLAVHASPQPLEQIKQSESQLSGRVGMIEMDLASGRTLTAWRADERFPMISTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLAIVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARDTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR',
 'NCRD_0': 'MIGLIVARSKNNVIGKNGNIPWKIKGEQKQFRELTTGNVVIMGRKSYEEIGHPLPNRMNIVVSTTTEYQGDNLVSVKSLEDALLLAKGRDVYISGGYGLFKEALQIVDKMYITEVDLNIEDGDTFFPEFDINDFEVLIGETLGEEVKYTRTFYVRKNELSRFWI',
 'NDARO_1354': 'MIGLIVARSKNNVIGKNGNIPWKIKGEQKQFRELTTGNVVIMGRKSYEEIGHPLPNRMNIVVSTTTEYQGDNLVSVKSLEDALLLAKGRDVYISGGYGLFKEALQIVDKMYITEVDLNIEDGDTFFPEFDINDFEVLIGETLGEEVKYTRTFYVRKNELSRFWI',
 'NCRD_8349': 'MIGLIVARSKNNVIGKNGNIPWKIKGEQKQFRELTTGNVVIMGRKSYEEIGHPLPNRMNIVVSTTTEYQGDNLVSVKSLEDALLLAKGRDVYISGGYGLFKEALQIXXXXXXXXXXXXXXXXIVDKMYITEVDLNIEDGDTFFPEFDINDFEVLIGETLGEEVKYTRTFYVRKNELSKFWI',
 'NCRD_8015': 'MISLIVARSKNNVIGKNGNIPWKIKGEQKQFRELTTGNVVIMGRKSYEEIGHPLPSRMNIVVSTTTEYQGDNLLSAKSLEDALLLTKGQDVYISGGYGLFKEALPLVDKMYITEVELIVEDGDTFFPEFEVADFEVVIGETFGEEVKYTRTYYTRKNKYYISEN',
 'NCRD_29912': 'MISLIVARSKNNVIGKNGNIPWKIKGEQRQFRELTTGNVVIMGRKSYEEIGRPLPNRMNIVVSTTTEYQGDNLVSAKSLEDALLLAKGQDVYIAGGYGLFKEALSLVDKMYITEVELIVEDGDTFFPEFDVAEFDVMIGETFGEEVKYTRTYYTRKK',
 'HMD_1374': 'MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDERFPMCSTSKVMAAAAVLKQSETQKQLLNQPVEIKPADLVNYNPIAEKHVNGTMTLAELSAAALQYSDNTAMNKLIAQLGGPGGVTAFARAIGDETFRLDRTEPTLNTAIPGDPRDTTTPRAMAQTLRQLTLGHALGETQRAQLVTWLKGNTTGAASIRAGLPTSWTVGDKTGSGDYGTTNDIAVIWPQGRAPLVLVTYFTQPQQNAERRHDVLASAARIIAEGL',
 'MEGARES_1622': 'MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDERFPMCSTSKVMAAAAVLKQSETQKQLLNQPVEIKPADLVNYNPIAEKHVNGTMTLAELSAAALQYSDNTAMNKLIAQLGGPGGVTAFARAIGDETFRLDRTEPTLNTAIPGDPRDTTTPRAMAQTLRQLTLGHALGETQRAQLVTWLKGNTTGAASIRAGLPTSWTVGDKTGSGDYGTTNDIAVIWPQGRAPLVLVTYFTQPQQNAERRHDVLASAARIIAEGL',
 'NDARO_4551': 'MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDERFPMCSTSKVMAAAAVLKQSETQKQLLNQPVEIKPADLVNYNPIAEKHVNGTMTLAELSAAALQYSDNTAMNKLIAQLGGPGGVTAFARAIGDETFRLDRTEPTLNTAIPGDPRDTTTPRAMAQTLRQLTLGHALGETQRAQLVTWLKGNTTGAASIRAGLPTSWTVGDKTGSGDYGTTNDIAVIWPQGRAPLVLVTYFTQPQQNAERRHDVLASAARIIAEGL',
 'RESFINDER_599': 'MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDERFPMCSTSKVMAAAAVLKQSETQKQLLNQPVEIKPADLVNYNPIAEKHVNGTMTLAELSAAALQYSDNTAMNKLIAQLGGPGGVTAFARAIGDETFRLDRTEPTLNTAIPGDPRDTTTPRAMAQTLRQLTLGHALGETQRAQLVTWLKGNTTGAASIRAGLPTSWTVGDKTGSGDYGTTNDIAVIWPQGRAPLVLVTYFTQPQQNAERRHDVLASAARIIAEGL',
 'CARD_159': 'MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDERFPMCSTSKVMAAAAVLKQSETQKQLLNQPVEIKPADLVNYNPIAEKHVNGTMTLAELSAAALQYSDNTAMNKLIAQLGGPGGVTAFARAIGDETFRLDRTEPTLNTAIPGDPRDTTTPRAMAQTLRQLTLGHALGETQRAQLVTWLKGNTTGAASIRAGLPTSWTVGDKTGSGDYGTTNDIAVIWPQGRAPLVLVTYFTQPQQNAERRRDVLASAARIIAEGL',
 'HMD_247': 'MELPNIMHPVAKLSTALAAALMLSGCMPGEIRPTIGQQMETGDQRFGDLVFRQLAPNVWQHTSYLDMPGFGAVASNGLIVRDGGRVLVVDTAWTDDQTAQILNWIKQEINLPVALAVVTHAHQDKMGGMDALHAAGIATYANALSNQLAPQEGMVAAQHSLTFAANGWVEPATAPNFGPLKVFYPGPGHTSDNITVGIDGTDIAFGGCLIKDSKAKSLGNLGDADTEHYAASVRAFGAAFPKASMIVMSHSAPDSRAAITHTARMADKLR',
 'MEGARES_2711': 'MELPNIMHPVAKLSTALAAALMLSGCMPGEIRPTIGQQMETGDQRFGDLVFRQLAPNVWQHTSYLDMPGFGAVASNGLIVRDGGRVLVVDTAWTDDQTAQILNWIKQEINLPVALAVVTHAHQDKMGGMDALHAAGIATYANALSNQLAPQEGMVAAQHSLTFAANGWVEPATAPNFGPLKVFYPGPGHTSDNITVGIDGTDIAFGGCLIKDSKAKSLGNLGDADTEHYAASVRAFGAAFPKASMIVMSHSAPDSRAAITHTARMADKLR',
 'NDARO_5885': 'MELPNIMHPVAKLSTALAAALMLSGCMPGEIRPTIGQQMETGDQRFGDLVFRQLAPNVWQHTSYLDMPGFGAVASNGLIVRDGGRVLVVDTAWTDDQTAQILNWIKQEINLPVALAVVTHAHQDKMGGMDALHAAGIATYANALSNQLAPQEGMVAAQHSLTFAANGWVEPATAPNFGPLKVFYPGPGHTSDNITVGIDGTDIAFGGCLIKDSKAKSLGNLGDADTEHYAASVRAFGAAFPKASMIVMSHSAPDSRAAITHTARMADKLR',
 'RESFINDER_1518': 'MELPNIMHPVAKLSTALAAALMLSGCMPGEIRPTIGQQMETGDQRFGDLVFRQLAPNVWQHTSYLDMPGFGAVASNGLIVRDGGRVLVVDTAWTDDQTAQILNWIKQEINLPVALAVVTHAHQDKMGGMDALHAAGIATYANALSNQLAPQEGMVAAQHSLTFAANGWVEPATAPNFGPLKVFYPGPGHTSDNITVGIDGTDIAFGGCLIKDSKAKSLGNLGDADTEHYAASVRAFGAAFPKASMIVMSHSAPDSRAAITHTARMADKLR',
 'CARD_2457': 'MELPNIMHPVAKLSTALAAALMLSGCMPGEIRPTIGQQMETGDQRFGDLVFRQLAPNVWQHTSYLDMPGFGAVASNGLIVRDGGRVLVVDTAWTDDQTAQILNWIKQEINLPVALAVVTHAHQDKMGGMDALHAAGIATYANALSNQLAPQEGLVAAQHSLTFAANGWVEPATAPNFGPLKVFYPGPGHTSDNITVGIDGTDIAFGGCLIKDSKAKSLGNLGDADTEHYAASVRAFGAAFPKASMIVMSHSAPDSRAAITHTARMADKLR',
 'HMD_1754': 'MMKKSLCCALLLGISCSALATPVSEKQLAEVVANTVTPLMKAQSVPGMAVAVIYQGKPHYYTFGKADIAANKPVTPQTLFELGSISKTFTGVLGGDAIARGEISLDDPVTRYWPQLTGKQWQGIRMLDLATYTAGGLPLQVPDEVTDNASLLRFYQNWQPQWKPGTTRLYANASIGLFGALAVKPSGMPYEQAMTTRVLKPLKLDHTWINVPKAEEAHYAWGYRDGKAVRVSPGMLDAQAYGVKTNVQDMANWVMANMAPENVADASLKQGIALAQSRYWRIGSMYQGLGWEMLNWPVEANTVVEGSDSKVALAPLPVVEVNPPAPPVKASWVHKTGSTGGFGSYVAFIPEKQIGIVMLANTSYPNPARVEAAYYILEALQ',
 'MEGARES_126': 'MMKKSLCCALLLGISCSALATPVSEKQLAEVVANTVTPLMKAQSVPGMAVAVIYQGKPHYYTFGKADIAANKPVTPQTLFELGSISKTFTGVLGGDAIARGEISLDDPVTRYWPQLTGKQWQGIRMLDLATYTAGGLPLQVPDEVTDNASLLRFYQNWQPQWKPGTTRLYANASIGLFGALAVKPSGMPYEQAMTTRVLKPLKLDHTWINVPKAEEAHYAWGYRDGKAVRVSPGMLDAQAYGVKTNVQDMANWVMANMAPENVADASLKQGIALAQSRYWRIGSMYQGLGWEMLNWPVEANTVVEGSDSKVALAPLPVVEVNPPAPPVKASWVHKTGSTGGFGSYVAFIPEKQIGIVMLANTSYPNPARVEAAYYILEALQ',
 'NDARO_3622': 'MMKKSLCCALLLGISCSALATPVSEKQLAEVVANTVTPLMKAQSVPGMAVAVIYQGKPHYYTFGKADIAANKPVTPQTLFELGSISKTFTGVLGGDAIARGEISLDDPVTRYWPQLTGKQWQGIRMLDLATYTAGGLPLQVPDEVTDNASLLRFYQNWQPQWKPGTTRLYANASIGLFGALAVKPSGMPYEQAMTTRVLKPLKLDHTWINVPKAEEAHYAWGYRDGKAVRVSPGMLDAQAYGVKTNVQDMANWVMANMAPENVADASLKQGIALAQSRYWRIGSMYQGLGWEMLNWPVEANTVVEGSDSKVALAPLPVVEVNPPAPPVKASWVHKTGSTGGFGSYVAFIPEKQIGIVMLANTSYPNPARVEAAYYILEALQ',
 'CARD_2943': 'MMKKSLCCALLLGISCSALATPVSEKQLAEVVANTVTPLMKAQSVPGMAVAVIYQGKPHYYTFGKADIAANKPVTPQTLFELGSISKTFTGVLGGDAIARGEISLDDPVTRYWPQLTGKQWQGIRMLDLATYTAGGLPLQVPDEVTDNASLLRFYQNWQPQWKPGTTRLYANASIGLFGALAVKPSGMPYEQAMTTRVLKPLKLDHTWINVPKAEEAHYAWGYRDGKAVRVSPGMLDAQAYGVKTNVQDMANWVMANMAPENVADASLKQGIALAQSRYWRIGSMYQGLGWEMLNWPVEANTVVEGSDSKVALAPLPVVEVNPPAPPVKASWVHKTGSTGGFGSYVAFIPEKQIGIVMLANTSYPNPARVEAAYHILEALQ',
 'MEGARES_69': 'MMKKSLCCALLLGISCSALATPVSEKQLAEVVANTVTPLMKAQSVPGMAVAVIYQGKPHYYTFGKADIAANKPVTPQTLFELGSISKTFTGVLGGDAIARGEISLDDPVTRYWPQLTGKQWQGIRMLDLATYTAGGLPLQVPDEVTDNASLLRFYQNWQPQWKPGTTRLYANASIGLFGALAVKPSGMPYEQAMTTRVLKPLKLDHTWINVPKAEEAHYAWGYRDGKAVRVSPGMLDAQAYGVKTNVQDMANWVMANMAPENVADASLKQGIALAQSRYWRIGSMYQGLGWEMLNWPVEANTVVEGSDSKVALAPLPVVEVNPPAPPVKASWVHKTGSTGGFGSYVAFIPEKQIGIVMLANTSYPNPARVEAAYHILEALQ',
 'HMD_1175': 'MNVRKHKASFFSVVITFLCLTLSLNANATDSVLEAVTNAETELGARIGLAVHDLETGKRWEHKSNERFPLSSTFKTLACANVLQRVDLGKERIDRVVRFSESNLVTYSPVTEKHVGKKGMSLAELCQATLSTSDNSAANFILQAIGGPKALTKFLRSIGDDTTRLDRWETELNEAVPGDKRDTTTPIAMVTTLEKLLIDETLSIKSRQQLESWLKGNEVGDALFRKGVPSDWIVADRTGAGGYGSRAITAVMWPPNRKPIVAALYITETDASFEERNAVIAKIGEQIAKTVLMENSRN',
 'MEGARES_979': 'MNVRKHKASFFSVVITFLCLTLSLNANATDSVLEAVTNAETELGARIGLAVHDLETGKRWEHKSNERFPLSSTFKTLACANVLQRVDLGKERIDRVVRFSESNLVTYSPVTEKHVGKKGMSLAELCQATLSTSDNSAANFILQAIGGPKALTKFLRSIGDDTTRLDRWETELNEAVPGDKRDTTTPIAMVTTLEKLLIDETLSIKSRQQLESWLKGNEVGDALFRKGVPSDWIVADRTGAGGYGSRAITAVMWPPNRKPIVAALYITETDASFEERNAVIAKIGEQIAKTVLMENSRN',
 'NCRD_1': 'MNVRKHKASFFSVVITFLCLTLSLNANATDSVLEAVTNAETELGARIGLAVHDLETGKRWEHKSNERFPLSSTFKTLACANVLQRVDLGKERIDRVVRFSESNLVTYSPVTEKHVGKKGMSLAELCQATLSTSDNSAANFILQAIGGPKALTKFLRSIGDDTTRLDRWETELNEAVPGDKRDTTTPIAMVTTLEKLLIDETLSIKSRQQLESWLKGNEVGDALFRKGVPSDWIVADRTGAGGYGSRAITAVMWPPNRKPIVAALYITETDASFEERNAVIAKIGEQIAKTVLMENSRN',
 'NDARO_4229': 'MNVRKHKASFFSVVITFLCLTLSLNANATDSVLEAVTNAETELGARIGLAVHDLETGKRWEHKSNERFPLSSTFKTLACANVLQRVDLGKERIDRVVRFSESNLVTYSPVTEKHVGKKGMSLAELCQATLSTSDNSAANFILQAIGGPKALTKFLRSIGDDTTRLDRWETELNEAVPGDKRDTTTPIAMVTTLEKLLIDETLSIKSRQQLESWLKGNEVGDALFRKGVPSDWIVADRTGAGGYGSRAITAVMWPPNRKPIVAALYITETDASFEERNAVIAKIGEQIAKTVLMENSRN',
 'RESFINDER_2124': 'MNVRKHKASFFSVVITFLCLTLSLNANATDSVLEAVTNAETELGARIGLAVHDLETGKRWEHKSNERFPLSSTFKTLACANVLQRVDLGKERIDRVVRFSESNLVTYSPVTEKHVGKKGMSLAELCQATLSTSDNSAANFILQAIGGPKALTKFLRSIGDDTTRLDRWETELNEAVPGDKRDTTTPIAMVTTLEKLLIDETLSIKSRQQLESWLKGNEVGDALFRKGVPSDWIVADRTGAGGYGSRAITAVMWPPNRKPIVAALYITETDASFEERNAVIAKIGEQIAKTVLMENSRN',
 'HMD_1580': 'MTKKMNKYNGKKLSRGEPPNFSGQHFMHNKRLLKEIVDKADVSVRDTVLELGAGKGALTTILSERADRVLAVEYDQKCIEALQWKLVGSKNVSILHQDIMKVALPTEPFVVVSNIPYSITTAIMKMLLNNPKNKLQRGAIVMEKGAAKRFTSVSPKDAYVMAWHMWFDIHYERGISRSSFSPPPKVDSALVRIVRKQHPLFPYKEAKAMHDFLSYALNNPRAPLDQVLRGIFTAPQAKKVRQAIGVKPETPVAMLHARQWAMVCDAMVRHVPKVYWPRRKR',
 'MEGARES_1763': 'MTKKMNKYNGKKLSRGEPPNFSGQHFMHNKRLLKEIVDKADVSVRDTVLELGAGKGALTTILSERADRVLAVEYDQKCIEALQWKLVGSKNVSILHQDIMKVALPTEPFVVVSNIPYSITTAIMKMLLNNPKNKLQRGAIVMEKGAAKRFTSVSPKDAYVMAWHMWFDIHYERGISRSSFSPPPKVDSALVRIVRKQHPLFPYKEAKAMHDFLSYALNNPRAPLDQVLRGIFTAPQAKKVRQAIGVKPETPVAMLHARQWAMVCDAMVRHVPKVYWPRRKR',
 'NCRD_2': 'MTKKMNKYNGKKLSRGEPPNFSGQHFMHNKRLLKEIVDKADVSVRDTVLELGAGKGALTTILSERADRVLAVEYDQKCIEALQWKLVGSKNVSILHQDIMKVALPTEPFVVVSNIPYSITTAIMKMLLNNPKNKLQRGAIVMEKGAAKRFTSVSPKDAYVMAWHMWFDIHYERGISRSSFSPPPKVDSALVRIVRKQHPLFPYKEAKAMHDFLSYALNNPRAPLDQVLRGIFTAPQAKKVRQAIGVKPETPVAMLHARQWAMVCDAMVRHVPKVYWPRRKR',
 'NDARO_1478': 'MTKKMNKYNGKKLSRGEPPNFSGQHFMHNKRLLKEIVDKADVSVRDTVLELGAGKGALTTILSERADRVLAVEYDQKCIEALQWKLVGSKNVSILHQDIMKVALPTEPFVVVSNIPYSITTAIMKMLLNNPKNKLQRGAIVMEKGAAKRFTSVSPKDAYVMAWHMWFDIHYERGISRSSFSPPPKVDSALVRIVRKQHPLFPYKEAKAMHDFLSYALNNPRAPLDQVLRGIFTAPQAKKVRQAIGVKPETPVAMLHARQWAMVCDAMVRHVPKVYWPRRKR',
 'RESFINDER_2345': 'MTKKMNKYNGKKLSRGEPPNFSGQHFMHNKRLLKEIVDKADVSVRDTVLELGAGKGALTTILSERADRVLAVEYDQKCIEALQWKLVGSKNVSILHQDIMKVALPTEPFVVVSNIPYSITTAIMKMLLNNPKNKLQRGAIVMEKGAAKRFTSVSPKDAYVMAWHMWFDIHYERGISRSSFSPPPKVDSALVRIVRKQHPLFPYKEAKAMHDFLSYALNNPRAPLDQVLRGIFTAPQAKKVRQAIGVKPETPVAMLHARQWAMVCDAMVRHVPKVYWPRRKR',
 'HMD_613': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERETTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
 'MEGARES_4952': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERETTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
 'NDARO_8929': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERETTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
 'RESFINDER_1271': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERETTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
 'CARD_1547': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
 'MEGARES_2430': 'MNVQNCMVKAVSVSIILFASLSLAAQKVKEPTVSNADWSKPYRPFRIAGNLYYIGTYDLACYLITTKQGNIIVNTGLAASALQIKNNIKALGFKLTDTKILLTTQAHYDHLGAMAEIKKITGAKLMADEGDATVMADGGSSDYAFGGHGSMFEPIIADRLLHDKDTIQLGDTKLVMLHHPGHTKGSCSFLFDTKDEQRSYRILIANMPTIVIEKKFSEVSSYPGIAKDYAYTLQAMKNLSFDIWVASHASQFSMHSKHKPGDGYNPKSFMDRKGYDESLDKLQKEYEKHLNEN',
 'NCRD_3': 'MNVQNCMVKAVSVSIILFASLSLAAQKVKEPTVSNADWSKPYRPFRIAGNLYYIGTYDLACYLITTKQGNIIVNTGLAASALQIKNNIKALGFKLTDTKILLTTQAHYDHLGAMAEIKKITGAKLMADEGDATVMADGGSSDYAFGGHGSMFEPIIADRLLHDKDTIQLGDTKLVMLHHPGHTKGSCSFLFDTKDEQRSYRILIANMPTIVIEKKFSEVSSYPGIAKDYAYTLQAMKNLSFDIWVASHASQFSMHSKHKPGDGYNPKSFMDRKGYDESLDKLQKEYEKHLNEN',
 'NDARO_838': 'MNVQNCMVKAVSVSIILFASLSLAAQKVKEPTVSNADWSKPYRPFRIAGNLYYIGTYDLACYLITTKQGNIIVNTGLAASALQIKNNIKALGFKLTDTKILLTTQAHYDHLGAMAEIKKITGAKLMADEGDATVMADGGSSDYAFGGHGSMFEPIIADRLLHDKDTIQLGDTKLVMLHHPGHTKGSCSFLFDTKDEQRSYRILIANMPTIVIEKKFSEVSSYPGIAKDYAYTLQAMKNLSFDIWVASHASQFSMHSKHKPGDGYNPKSFMDRKGYDESLDKLQKEYEKHLNEN',
 'NCRD_29762': 'MKIKFIFCLFLFPLFVLAQNVQEPTDTPKEWSAPYAPFRIVGNVYYVGTYDLACYLITTSKGNILINTGLSSSAEQIKKNVNLLGFNFKDIKILLTTQAHYDHLGAMAEIKKLTGAKMMVDEKDATVMKDGGKSDYALGNGKTTYAPIIPDRLLKDGDQIQLGNTNIVMFHHPGHTKGSCSFMLKTKDEKRSYSVLIANMPSIVTEKKFSEIPAYPEIEKDYAYTLNSLKKLSFDIWLSSHASQFGLHEKHKPGDKYNPAAFFDRKGYDKALNSLQLEFDKKIGKK',
 'CARD_4377': 'MLKQSINTVVLLLFLTFSSLFACAQKVAEPTRNPPEWTQPYQPFRIAGNLYYVGTSDLASYLITTPKGHILINTGLSSSLSSIKANVKTLGFKFSDIKILLTTQAHFDHMGAMAAIKKLTGAKFMVDEKDAKVAADGGRSDYALGGHRSTYVPVKADRILHDKDKITLGGMELVMLHHPGHTQGSCSFLFNVKDESRVYSVLIANMPTIVTEKKFSEVTTYPGIAKDYAYTLNAMKKLKFDMWLSSHASQFGLLTKHKPGDAYNPAAFIDQKGYDSAIRDLEDKFLRKE',
 'HMD_565': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGASKRGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
 'MEGARES_4888': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGASKRGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
 'NDARO_9101': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGASKRGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
 'RESFINDER_1226': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGASKRGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
 'MEGARES_5065': 'KRKSMSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGASKRGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
 'HMD_558': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMGDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAE',
 'MEGARES_4882': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMGDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAE',
 'MEGARES_5061': 'KRKSMSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMGDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAE',
 'HMD_16970': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMGDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
 'CARD_1789': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMGDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
 'HMD_306': 'MSLYRRLVLLSCLSWPLAGFSATALTNLVAEPFAKLEQDFGGSIGVYAMDTGSGATVSYRAEERFPLCSSFKGFLAAAVLARSQQQAGLLDTPIRYGKNALVRWSPISEKYLTTGMTVAELSAAAVQYSDNAAANLLLKELGGPAGLTAFMRSIGDTTFRLDRWELELNSAIPGDARDTSSPRAVTESLQKLTLGSALAAPQRQQFVDWLKGNTTGNHRIRAAVPADWAVGDKTGTCGVYGTANDYAVVWPTGRAPIVLAVYTRAPNKDDKYSEAVIAAAARLALEGLGVNGQ',
 'MEGARES_2324': 'MSLYRRLVLLSCLSWPLAGFSATALTNLVAEPFAKLEQDFGGSIGVYAMDTGSGATVSYRAEERFPLCSSFKGFLAAAVLARSQQQAGLLDTPIRYGKNALVRWSPISEKYLTTGMTVAELSAAAVQYSDNAAANLLLKELGGPAGLTAFMRSIGDTTFRLDRWELELNSAIPGDARDTSSPRAVTESLQKLTLGSALAAPQRQQFVDWLKGNTTGNHRIRAAVPADWAVGDKTGTCGVYGTANDYAVVWPTGRAPIVLAVYTRAPNKDDKYSEAVIAAAARLALEGLGVNGQ',
 'NDARO_5232': 'MSLYRRLVLLSCLSWPLAGFSATALTNLVAEPFAKLEQDFGGSIGVYAMDTGSGATVSYRAEERFPLCSSFKGFLAAAVLARSQQQAGLLDTPIRYGKNALVRWSPISEKYLTTGMTVAELSAAAVQYSDNAAANLLLKELGGPAGLTAFMRSIGDTTFRLDRWELELNSAIPGDARDTSSPRAVTESLQKLTLGSALAAPQRQQFVDWLKGNTTGNHRIRAAVPADWAVGDKTGTCGVYGTANDYAVVWPTGRAPIVLAVYTRAPNKDDKYSEAVIAAAARLALEGLGVNGQ',
 'RESFINDER_682': 'MSLYRRLVLLSCLSWPLAGFSATALTNLVAEPFAKLEQDFGGSIGVYAMDTGSGATVSYRAEERFPLCSSFKGFLAAAVLARSQQQAGLLDTPIRYGKNALVRWSPISEKYLTTGMTVAELSAAAVQYSDNAAANLLLKELGGPAGLTAFMRSIGDTTFRLDRWELELNSAIPGDARDTSSPRAVTESLQKLTLGSALAAPQRQQFVDWLKGNTTGNHRIRAAVPADWAVGDKTGTCGVYGTANDYAVVWPTGRAPIVLAVYTRAPNKDDKYSEAVIAAAARLALEGLGVNGQ',
 'CARD_927': 'MSLYRRLVLLSCLSWPLAGFSATALTNLVAEPFAKLEQDFGGSIGVYAMDTGSGATVSYRAEERFPLCSSFKGFLAAAVLARSQQQAGLLDTPIRYGKNALVRWSPISEKYLTTGMTVAELSAAAVQYSDNAAANLLLKELGGPAGLTAFMRSIGDTTFRLDRWELELNSAIPGDARDTSSPRAVTESLQKLTLGSALAAPQRQQFVDWLKGNTTGNHRIRAAVPADWAVGDKTGTCGVYGTANDYAVVWPTGRAPIVLAVYTRAPNKDDKHSEAVIAAAARLALEGLGVNGQ',

In [42]:
def MergeSequences(base, override1, override2):
    for key, value in base.items():
        try:     
            base[key].update({"Sequence": override1[key]})
            try:
                base[key].update({"Sequence": override2[key]})
            except:
                pass
        except:
            pass
    return base

In [43]:
MergeSequences(MetaDict, PairWiseDictSource, PairWiseDictTarget)

{'CARD_0': {'Drug Class': 'cephalosporin',
  'Name': 'CblA-1',
  'Sequence': 'MKAYFIAILTLFTCIATVVRAQQMSELENRIDSLLNGKKATVGIAVWTDKGDMLRYNDHVHFPLLSVFKFHVALAVLDKMDKQSISLDSIVSIKASQMPPNTYSPLRKKFPDQDFTITLRELMQYSISQSDNNACDILIEYAGGIKHINDYIHRLSIDSFNLSETEDGMHSSFEAVYRNWSTPSAMVRLLRTADEKELFSNKELKDFLWQTMIDTETGANKLKGMLPAKTVVGHKTGSSDRNADGMKTADNDAGLVILPDGRKYYIAAFVMDSYETDEDNANIIARISRMVYDAMR'},
 'CARD_1': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-52',
  'Sequence': 'MRYIRLCIISLLAALPLAVHASPQPLEQIKQSESQLSGRVGMIEMDLASGRTLTAWRADERFPMISTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLAIVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARDTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR'},
 'CARD_2': {'Drug Class': 'diaminopyrimidine antibiotic',
  'Name': 'dfrF',
  'Sequence': 'MIGLIVARSKNNVIGKNGNIPWKIKGEQKQFRELTTGNVVIMGRKSYEEIGHPLPNRMNIVVSTTTEYQGDNLVSVKSLEDALLLAKGRDVYISGGYGLFKEALQIVDKMYITEVDLNIEDGDTFFPEFDINDFEVLIGETLGEEVKYTRTFYVRKNELSRFWI'},
 'CARD_3': {'Drug Class': 'cephalosporin',
  'Name': 'CTX-M-130',
  'Sequence': 'MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDERFPMCSTSKVMAAAAVLKQSETQKQLLNQPVEIKPADLVNYNPIAEKHVNGTMTLAELSAAALQYSDNTAMNKLIAQLGGPGGVTAFARAIGDETFRLDRTEPTLNTAIPGDPRDTTTPRAMAQTLRQLTLGHALGETQRAQLVTWLKGNTTGAASIRAGLPTSWTVGDKTGSGDYGTTNDIAVIWPQGRAPLVLVTYFTQPQQNAERRHDVLASAARIIAEGL'},
 'CARD_4': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'NDM-6',
  'Sequence': 'MELPNIMHPVAKLSTALAAALMLSGCMPGEIRPTIGQQMETGDQRFGDLVFRQLAPNVWQHTSYLDMPGFGAVASNGLIVRDGGRVLVVDTAWTDDQTAQILNWIKQEINLPVALAVVTHAHQDKMGGMDALHAAGIATYANALSNQLAPQEGMVAAQHSLTFAANGWVEPATAPNFGPLKVFYPGPGHTSDNITVGIDGTDIAFGGCLIKDSKAKSLGNLGDADTEHYAASVRAFGAAFPKASMIVMSHSAPDSRAAITHTARMADKLR'},
 'CARD_5': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'ACT-35',
  'Sequence': 'MMKKSLCCALLLGISCSALATPVSEKQLAEVVANTVTPLMKAQSVPGMAVAVIYQGKPHYYTFGKADIAANKPVTPQTLFELGSISKTFTGVLGGDAIARGEISLDDPVTRYWPQLTGKQWQGIRMLDLATYTAGGLPLQVPDEVTDNASLLRFYQNWQPQWKPGTTRLYANASIGLFGALAVKPSGMPYEQAMTTRVLKPLKLDHTWINVPKAEEAHYAWGYRDGKAVRVSPGMLDAQAYGVKTNVQDMANWVMANMAPENVADASLKQGIALAQSRYWRIGSMYQGLGWEMLNWPVEANTVVEGSDSKVALAPLPVVEVNPPAPPVKASWVHKTGSTGGFGSYVAFIPEKQIGIVMLANTSYPNPARVEAAYYILEALQ'},
 'CARD_6': {'Drug Class': 'penicillin beta-lactam',
  'Name': 'CARB-5',
  'Sequence': 'MNVRKHKASFFSVVITFLCLTLSLNANATDSVLEAVTNAETELGARIGLAVHDLETGKRWEHKSNERFPLSSTFKTLACANVLQRVDLGKERIDRVVRFSESNLVTYSPVTEKHVGKKGMSLAELCQATLSTSDNSAANFILQAIGGPKALTKFLRSIGDDTTRLDRWETELNEAVPGDKRDTTTPIAMVTTLEKLLIDETLSIKSRQQLESWLKGNEVGDALFRKGVPSDWIVADRTGAGGYGSRAITAVMWPPNRKPIVAALYITETDASFEERNAVIAKIGEQIAKTVLMENSRN'},
 'CARD_7': {'Drug Class': 'lincosamide antibiotic;macrolide antibiotic;streptogramin A antibiotic;streptogramin B antibiotic;streptogramin antibiotic',
  'Name': 'Erm(34)',
  'Sequence': 'MTKKMNKYNGKKLSRGEPPNFSGQHFMHNKRLLKEIVDKADVSVRDTVLELGAGKGALTTILSERADRVLAVEYDQKCIEALQWKLVGSKNVSILHQDIMKVALPTEPFVVVSNIPYSITTAIMKMLLNNPKNKLQRGAIVMEKGAAKRFTSVSPKDAYVMAWHMWFDIHYERGISRSSFSPPPKVDSALVRIVRKQHPLFPYKEAKAMHDFLSYALNNPRAPLDQVLRGIFTAPQAKKVRQAIGVKPETPVAMLHARQWAMVCDAMVRHVPKVYWPRRKR'},
 'CARD_8': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-126',
  'Sequence': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERETTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW'},
 'CARD_9': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'LRA-12',
  'Sequence': 'MNVQNCMVKAVSVSIILFASLSLAAQKVKEPTVSNADWSKPYRPFRIAGNLYYIGTYDLACYLITTKQGNIIVNTGLAASALQIKNNIKALGFKLTDTKILLTTQAHYDHLGAMAEIKKITGAKLMADEGDATVMADGGSSDYAFGGHGSMFEPIIADRLLHDKDTIQLGDTKLVMLHHPGHTKGSCSFLFDTKDEQRSYRILIANMPTIVIEKKFSEVSSYPGIAKDYAYTLQAMKNLSFDIWVASHASQFSMHSKHKPGDGYNPKSFMDRKGYDESLDKLQKEYEKHLNEN'},
 'CARD_10': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-72',
  'Sequence': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGASKRGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW'},
 'CARD_11': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-59',
  'Sequence': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMGDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAE'},
 'CARD_12': {'Drug Class': 'carbapenem;cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'KPC-10',
  'Sequence': 'MSLYRRLVLLSCLSWPLAGFSATALTNLVAEPFAKLEQDFGGSIGVYAMDTGSGATVSYRAEERFPLCSSFKGFLAAAVLARSQQQAGLLDTPIRYGKNALVRWSPISEKYLTTGMTVAELSAAAVQYSDNAAANLLLKELGGPAGLTAFMRSIGDTTFRLDRWELELNSAIPGDARDTSSPRAVTESLQKLTLGSALAAPQRQQFVDWLKGNTTGNHRIRAAVPADWAVGDKTGTCGVYGTANDYAVVWPTGRAPIVLAVYTRAPNKDDKYSEAVIAAAARLALEGLGVNGQ'},
 'CARD_13': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-212',
  'Sequence': 'MKTLQSGLIALITTFGSACTTISPSVETAKNQQQQSAQQQIQQAFDQLQTTGVIVVKDKHSLHSYGNDLSRAQTPYIPASTFKMLNALIGLEHGKATSTEVFKWDGQKRSFPTWEKDMTLGQAMQASAVPVYQELARRIGLDLMKKEVQRIGYGNQQIGTVVDNFWLVGPLQITPVQEVLFVEKLANTQLAFKPDVQHAVQDMLLIEQKPNYKLYAKSGWGMDLEPQVGWWAGWVETSTGEKVYFALNMHMKTGISASVREQLVKQSLTALGII'},
 'CARD_14': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'IMP-2',
  'Sequence': 'MKKLFVLCVCFLCSITAAGARLPDLKIEKLEEGVYVHTSFEEVNGWGVVSKHGLVVLVNTDAYLIDTPFTATDTEKLVNWFVERGYKIKGTISSHFHSDSTGGIEWLNSQSIPTYASELTNELLKKDGKVQAKNSFSGVSYWLVKNKIEVFYPGPGHTQDNVVVWLPEKKILFGGCFVKPDGLGNLGDANLEAWPKSAKILMSKYVKAKLVVSSHSEIGDASLLKRTWEQAVKGLNESKKPSQPSN'},
 'CARD_15': {'Drug Class': 'cephalosporin',
  'Name': 'CMY-1',
  'Sequence': 'MQQRQSILWGAVATLMWAGLAHAGEASPVDPLRPVVDASIQPLLKEHRIPGMAVAVLKDGKAHYFNYGVANRESGAGVSEQTLFEIGSVSKTLTATLGAYAVVKGAMQLDDKASRHAPWLKGSAFDSITMGELATYSAGGLPLQFPEEVDSSEKMRAYYRQWAPVYSPGSHRQYSNPSIGLFGHLAASSLKQPFAPLMEQTLLPGLGMHHTYVNVPKQAMASYAYGYSKEDKPIRVNPGMLADEAYGIKTSSADLLRFVKANIGGVDDKALQQAISLTHQGHYSVGGMTQGLGWESYAYPVTEQTLLAGNSAKVILEANPTAAPRESGSQVLFNKTGSTNGFGAYVAFVPARGIGIVMLANRNYPNEARIKAAHAILAQLAG'},
 'CARD_16': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-329',
  'Sequence': 'MYKKALIVATSILFLSACSSNTVKQHQIHSISANKNSEAIKSLFDQAQTTGVLVIKRGQTEEIYGNDLKRASTAYVPASTFKMLNALIGLEHHKAITTEVFKWDGQKRLFPDWEKDMTLGDAMKASAIPVYQELARRIGLDLMSKEVKRIGFGNANIGSKVDDFWLVGPLKITPQQETQFAYQLAHKMLPFSKDVQEQVQSMVFIEEKNGRKIYAKSGWGWDIEPQVGWLTGWVVQPQGEIVAFSLNLEMKKGTPSSIRKEIAYKGLEQLGIL'},
 'CARD_17': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'ACT-10',
  'Sequence': 'MMKKSVCCALLLSTSCSVLAAPMSEKQLAEVVERTVTPLMKAQAIPGIAVAVIYQGQPHYFTFGKADVAANKPVTPQTLFELGSISKTFTGVLGGDAIARGEISLGDPVTKYWPELTGKQWKGIRMLDLATYTAGGLPLQVPDEVTDNASLLRFYQNWQPQWKPGTTRLYANASIGLFGALAVKPSGMSYEQAITTRVFKPLKLDHTWINVPKTEEAHYAWGYRDGKAVHVSPGMLDAEAYGVKTNVKDMASWVMVNMKPDSLEDSSLRKGFTLAQSRYWRVGAMYQGLGWEMLNWPVDAKTVVEGSDNKVALAPLPAREVNPPAPPVNASWVHKTGSTGGFGSYVAFIPEKQLGIVMLANKSYPNPARVEAAYRILDALQ'},
 'CARD_18': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-371',
  'Sequence': 'MNIKALLLITSAIFISACSPYIVTANPNHSASKSDDKAEKIKNLFNEAHTTGVLVIHQGQTQQSYGNDLARASTEYVPASTFKMLNALIGLEHHKATTTEVFKWDGEKRLFPEWEKNMTLGDAMKASAIPVYQDLARRIGLELMSKEVKRVGYGNADIGTQVDNFWLVGPLKITPQQEAQFAYKLANKTLPFSQKVQDEVQSMLFIEEKNGNKIYAKSGWGWDVNPQVGWLTGWVVKPQGNIVAFSLNLEMKKGIPSSVRKEITYKSLEQLGIL'},
 'CARD_19': {'Drug Class': 'fusidane antibiotic',
  'Name': 'fusB',
  'Sequence': 'MKTMIYPHQYNYIRSVILRLKNVYKTVNDKETVKVIQSETYNDINEIFGHIDDDIEESLKVLMNIRLSNKEIEAILNKFLEYVVPFELPSPQKLQKVFKKVKKIKIPQFEEYDLKVSSFVGWNELASNRKYIIYYDEKKQLKGLYGEISNQVVKGFCTICNKESNVSLFMKKSKTNSDGQYVKKGDYICRDSIHCNKQLTDINQFYNFIDKLD'},
 'CARD_20': {'Drug Class': 'cephalosporin',
  'Name': 'CTX-M-121',
  'Sequence': 'MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDERFPMCSTSKVMAAAAVLKQSETQKQLLNQPVEIKPADLVNYNPITEKHVNGTMTLAELSAAALQYSDNTAMNKLIAQLGGPGGVTAFARAIGDETFRLDRTEPTLNTAIPGDPRDTTTPRAMAQTLRQLTLGHALGETQRAQLVTWLKGNTTGAASIRAGLPTSWTVGDKTGSGGYGTTNDIAVIWPQGRAPLVLVTYFTQPQQNAESRRDVLASAARIIAEGL'},
 'CARD_21': {'Drug Class': 'cephalosporin;monobactam',
  'Name': 'VEB-3',
  'Sequence': 'MKIVKRILLVLLSLFFTVVYSNAQTDNLTLKIENVLKAKNARIGVAIFNSNEKDTFKINNDFHFPMQSVMKFPIALAVLSEIDKGNLSFEQKIEITPQDLLPKTWSPIKEEFPNGTTLTIEQILNYTVSESDNIGCDILLKLIGGTDSVQKFLNANHFTDISIKANEEQMHKDWNTQYQNWATPTAMNKLLIDTYNNKNQLLSKKSYDFIWKIMRETTTGSNRLKGQLPKNTIVAHKTGTSGINNGIAAATNDVGVITLPNGQLIFISVFVAESKETSEINEKIISDIAKITWNYYLNK'},
 'CARD_22': {'Drug Class': 'lincosamide antibiotic',
  'Name': 'lnuA',
  'Sequence': 'MKNNNVTEKELFYILDLFEHMKVTYWLDGGWGVDVLTGKQQREHRDIDIDFDAQHTQKVIQKLEDIGYKIEVHWMPSRMELKHEEYGYLDIHPINLNDDGSITQANPEGGNYVFQNDWFSETNYKDRKIPCISKEAQLLFHSGYDLTETDHFDIKNLKSIT'},
 'CARD_23': {'Drug Class': 'penicillin beta-lactam',
  'Name': 'OXA-45',
  'Sequence': 'MRGKHTVILGAALSALFAGAAGAQMLECTLVADAASGQELYRKGACDKAFAPMSTFKVPLAVMGYDAGILVDAHNPRWDYKPEFNGYKFQQKTTDPTIWEKDSIVWYSQQLTRKMGQKRFAAYVAGFGYGNGDISGEPGKSNGLTHSWLGSSLKISPEGQVRFVRDLLSAKLPASKDAQQMTVSILPHFAAGDWAVQGKTGTGSFIDARGAKAPLGWFIGWATHEERRVVFARMTAGGKKGEQPAGPAARDAFLKALPDLAKRF'},
 'CARD_24': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OXA-226',
  'Sequence': 'MAIRIFAILFSIFSLATFAHAQEGTLERSDWRKFFSEFQAKGTIVVADERQADRAMLVFDPVRSKKRYSPASTFKIPHTLFALDAGAVRDEFQIFRWDGVNRGFAGHNQDQDLRSAMRNSTVWVYELFAKEIGDDKARRYLKKIDYGNADPSTSNGDYRIEGSLAISAQEQIAFLRKLYRNELPFRVEHQRLVKDLMIVEAGRNWILRAKTGWEGRMGWWVGWVEWPTGSVFFALNIDTPNRMDDLFKREAIVRAILRSIEALPPNPAVNSDAAR'},
 'CARD_25': {'Drug Class': 'cephalosporin',
  'Name': 'CTX-M-155',
  'Sequence': 'MVKKSLRQFTLMATATVTLLLGSVPLYAQTADVQQKLAELERQSGGRLGVALINTADNSQILYRADERFAMCSTSKVMAAAAVLKKSESEPNLLNQRVEIKKSDLVNYNPIAEKHVNGTMSLAELSAAALQYSDNVAMNKLIAHVGGPASVTAFARQLGDETFRLDRTAPTLNTAIPGDPRDTTSPRAMAQTLRNLTLGKALGDSQRAQLVTWMKGNTTGAASIQAGLPASWVVGDKTGSGGYGTTNDIAVIWPKDRAPLILVTYFTQPQPKAESRRDVLASGAKIVTDGL'},
 'CARD_26': {'Drug Class': 'cephalosporin',
  'Name': 'DHA-15',
  'Sequence': 'MKKSLSATLISALLAFSAPGFSAADNVAAVVDSTIKPLMAQQDIPGMAVAVSVKGKPYYFNYGFADIQAKQPVTENTLFELGSVSKTFTGVLGAVSVAKKEMALNDPAAKYQPELALPQWKGITLLDLATYTAGGLPLQVPDAVKSRADLLNFYQQWQPSRKPGYMRLYANSSIGLFGALTANAAGMPYEQLLTARILAPLGLSHTFITVPESAQSQYAYGYKNKKPVRVSPGQLDAESYGVKSASKDMLRWAEMNMEPSRAGNADLEMAMYLAQTRYYKTAAINQGLGWEMYDWPQQKDMIINGVTNEVALQPHPVTDNQVQPYNRASWVHKTGATTGFGAYVAFIPEKQVAIVILANKNYPNTERVKAAQAILSALE'},
 'CARD_27': {'Drug Class': 'macrolide antibiotic;streptogramin antibiotic',
  'Name': 'msrE',
  'Sequence': 'MSLIIKARNIRLDYAGRDVLDIDELEIHSYDRIGLVGDNGAGKSSLLKVLNGEIVLAEATLQRFGDFAHISQLGGIEIETVEDRAMLSRLGVSNVQNDTMSGGEETRAKIAAAFSQQVHGILADEPTSHLDLNGIDLLIGQLKAFDGALLVISHDRYFLDMVVDKIWELKDGKITEYWGGYSDYLRQKEEERQHQAVEYELMMKERERLESAVQEKRQQANRLDNKKKGEKSKNSTESAGRLGHAKMTGTKQRKLYQAAKSMEKRLAALEDIQAPEHLRSIRFRQSSALELHNKFPITADGLSLKFGSRTIFDDANFIIPLGAKVAITGSNGTGKTSLLKMISERADGLTISPKAEIGYFTQTGYKFNTHKSVLSFMQEECEYTVAEIRAVLASMGIGANDIQKNLSDLSGGEIIKLLLSKMLLGKYNILLMDEPGNYLDLKSIAALETMMKSYAGTIIFVSHDKQLVDNIADIIYEIKDHKIIKTFERDC'},
 'CARD_28': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OXY-6-3',
  'Sequence': 'MLKSSWRKSALMAAAAVPLLLASGSLWASADAIQQKLADLEKRSGGRLGVALINTTDDSQTLYRGDERFAMCSTGKVMAAAAVLKQSESHPDVVNKRLEIKKSDLVVWSPITEKHLQSGMTLAELSAAALQYSDNTAMNKMISYLGGPEKVTAFAQSIGDVTFRLDRTEPALNSAIPGDKRDTTTPLAMAESLRKLTLGNALGEQQRAQLVTWLKGNTTGGQSIRAGLPASWAVGDKTGAGDYGTTNDIAVIWPENHAPLVLVTYFTQPQQDAKSRKEVLAAAAKIVTEGL'},
 'CARD_29': {'Drug Class': 'phosphonic acid antibiotic',
  'Name': 'FosA2',
  'Sequence': 'MLQSLNHLTLAVSDLQKSVTFWHELLGLTLHARWNTGAYLTCGDLWVCLSYDEARGYVPPQESDYTHYAFTVAAEDFEPFSHKLEQAGVTVWKQNKSEGASFYFLDPDGHKLELHVGSLAARLAACREKPYAGMVFTSDEA'},
 'CARD_30': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': "APH(3')-Va",
  'Sequence': 'MDDSTLRRKYPHHEWHAVNEGDSGAFVYQLTGGPEPQPELYAKIAPRAPENSAFDLSGEADRLEWLHRHGIPVPRVVERGADDTAAWLVTEAVPGVAAAEEWPEHQRFAVVEAMAELARALHELPVEDCPSDRRLDAAVAEARRNVAEGLVDLDDLQEERAGWTGDQLLAELDRTRPEKEDLVVCHGDLCPNNVLLDPGTCRVTGVIDVGRLGVADRHADIALAARELEIDEDPWFGPAYAERFLERYGAHRVDKEKLAFYQLLDEFF'},
 'CARD_31': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': 'AAC(3)-Ia',
  'Sequence': 'MGIIRTCRLGPDQVKSMRAALDLFGREFGDVATYSQHQPDSDYLGNLLRSKTFIALAAFDQEAVVGALAAYVLPRFEQPRSEIYIYDLAVSGEHRRQGIATALINLLKHEANALGAYVIYVQADYGDDPAVALYTKLGIREEVMHFDIDPSTAT'},
 'CARD_32': {'Drug Class': 'fluoroquinolone antibiotic',
  'Name': 'QnrB58',
  'Sequence': 'MTPLLYKKTGTNMALALVGEKIDRNRFTGEKIDNSTFFNCDFSGADLSGTEFIGCQFYDRESQKGCNFSRAMLKDAIFKSCDLSMADFRNASALGIEIRHCRAQGADFRGASFMNMITTRTWFCSAYITNTNLSYANFSKVVLEKCELWENRWMGAQVLGATFSGSDLSGGEFSTFDWRAANFTHCDLTNSELGDLDIRGVDLQGVKLDNYQASLLMERLGIAIIG'},
 'CARD_33': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': 'rmtH',
  'Sequence': 'MTIEQAAADILSSKKYQLLCPDTVVRILTQEWGRHKKPKQAVERTRERLHGICGAYLAPQVEKQASTALAAGDVQKALALHASTRERLDTYPQLYQFVFENNLPARVLDIACGLNPLMLHRQGVASVWGCDIHQGLGNVLTPYAQKHGWDFTFALHDVLCAPVAASGDMALVFKLLPLLEREQPGAALALLRTLDAPVICVSFPTRSLGGRGKGMHQHYATWFEGLVAPHFTVQHHTLIGDELLYRIQPNPA'},
 'CARD_34': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OXY-6-1',
  'Sequence': 'MLKSSWRKSALMAAAAVPLLLASGSLWASADAIQQKLADLEKRSGGRLGVALINTADDSQTLYRGDERFAMCSTGKVMAAAAVLKQSESHPDVVNKRLEIKKSDLVVWSPITEKHLQSGMTLAELSAAALQYSDNTAMNKMISYLGGPEKVTAFAQSIGDVTFRLDRTEPALNSAIPGDKRDTTTPLAMAESLRKLTLGNALGEQQRAQLVTWLKGNTTGGQSIRAGLPASWAVGDKTGAGDYGTTNDIAVIWPENHAPLVLVTYFTQPQQDAKSRKEVLAAAAKIVTEGL'},
 'CARD_35': {'Drug Class': 'carbapenem;cephalosporin;monobactam;penicillin beta-lactam;phenicol antibiotic',
  'Name': 'golS',
  'Sequence': 'MNIGKAAKASKVSAKMIRYYEQIGLIPAASRTDSGYRAYTQADVNQLHFIRRARDLGFSVAEISDLLNLWNNQSRQSADVKRLAQTHIDELDRRIQNMQHMAQTLKALIHCCAGDALPDCPILHTLGQPDDSEPEARTGAVLRRPRRHGLAKRL'},
 'CARD_36': {'Drug Class': 'disinfecting agents and antiseptics;nucleoside antibiotic',
  'Name': 'mdtP',
  'Sequence': 'MINRQLSRLLLCSILGSTTLISGCALVRKDSAPHQQLKPEQIKLADDIHLASSGWPQAQWWKQLNDPQLDALIQRTLSGSHTLAEAKLREEKAQSQADLLDAGSQLQVAALGMLNRQRVSANGFLSPYSMDAPALGMDGPYYTEATVGLFAGLDLDLWGVHRSAVAAAIGAHNAALAETAAVELSLATGVAQLYYSMQASYQMLDLLEQTHDVIDYAVKAHQSKVAHGLEAQVPFHGARAQILAVDKQIVAVKGQITETRESLRALIGAGASDMPEIRPVALPQVQTGIPATLSYELLARRPDLQAMRWYVQASLDQVDSARALFYPSFDIKAFFGLDSIHLHTLFKKTSRQFNFIPGLKLPLFDGGRLNANLEGTRAASNMMIERYNQSVLNAVRDVAVNGTRLQTLNDEREMQAERVEATRFTQRAAEAAYQRGLTSRLQATEARLPVLAEEMSLLMLDSRRVIQSIQLMKSLGGGYQAGPVVEKK'},
 'CARD_37': {'Drug Class': 'cephalosporin',
  'Name': 'CMY-114',
  'Sequence': 'MMKKSLCCALLLTASFSTFAAAKTEQQIADIVNRTITPLMQEQAIPGMAVAIIYEGKPYYFTWGKADIANNHPVTQQTLFELGSVSKTFNGVLGGDAIARGEIKLSDPVTKYWPELTGKQWRGISLLHLATYTAGGLPLQIPDYVTDKAELLRFYQNWQPQWTPGAKRLYANSSIGLFGALVVKPSGMSYEEAMTRRVLQPLKLAHTWITVPQSEQKNYAWGYREGKPVHVSPGQLDAEAYGVKSSVIDMARWVQANMDASHVQEKTLQQGIELAQSRYWRIGDMYQGLGWEMLNWPLKADSIINGSDSKVALAALPAVEVNPPAPAVKASWVHKTGSTGGFGSYVAFVPEKNLGIVMLANKSYPNPARVEAAWRILEKLQ'},
 'CARD_38': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-60',
  'Sequence': 'MLSRYSKTLAFAVVACTLAISTATAHAELVVRNDLKRVFDDAGVSGTFVLMDITADRTYVVDPARAARSIHPASTFKIPNSLIAFDTGAVRDDQEVLPYGGKPQPYEQWEHDMALPEAIRLSAVPIYQEVARRVGFERMQAYVDAFDYGNRQLGSAIDQFWLRGPLEISAFEEARFTSRMALKQLPVKPRTWDMVQRMLLIEQQGDAALYAKTGVATEYQPEIGWWAGWVERAGHVYAFALNIDMPREGDMAKRIPLGKQLMRALEVWPAP'},
 'CARD_39': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-90',
  'Sequence': 'MNIKALLLITSAIFISACSPYIVTANPNHSASKSDEKAEKIKNLFNEAHTTGVLVIQQGQTQQSYGNDLARASTEYVPASTFKMLNALIGLEHHKATTTEVFKWDGKKRLFPEWEKDMTLGDAMKASAIPVYQDLARRIGLELMSKEVKRVGYGNADIGTQVDNFWLVGPLKITPQQEAQFAYKLANKTLPFSQKVQDEVQSMLFIEEKNGNKIYAKSGWGWDVDPQVGWLTGWVVQPQGNIVAFSLNLEMKKGIPSSVRKEITYKSLEQLGIL'},
 'CARD_40': {'Drug Class': 'carbapenem',
  'Name': 'SME-2',
  'Sequence': 'MSNKVNFKTASFLFSVCLALSAFNAHANKSDAAAKQIKKLEEDFDGRIGVFAIDTGSGNTFGYRSDERFPLCSSFKGFLAAAVLERVQQKKLDINQKVKYESRDLEYHSPITTKYKGSGMTLGDMASAALQYSDNGATNIIMERFLGGPEGMTKFMRSIGDNEFRLDRWELELNTAIPGDKRDTSTPKAVANSLNKLALGNVLNAKEKAIYQNWLKGNTTGDARIRASVPADWVVGDKTGSCGAYGTANDYAVIWPKNRAPLIVSIYTTRKSKDDKHSDKTIAEASRIAIQAID'},
 'CARD_41': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': 'AAC(3)-IIIc',
  'Sequence': 'MFSRWSKPLVLAAVTRASLAADLAALGLAAGDAVMVHAAVSKVGRLLDGPDTIIAALSDAGRPAGTILAYADWEARYEDLVDEDGRVPQEWREHIPPFDPRRSRAIRDNGVLPEFLRTTPGALRSGNPGASMVGLGARAEWFTADHPLDYGYGEGSPLARLVEAGGKVLMLGAPLDTLTLLHHAEHLADIPGKRIRRIEVPLATPTGTQWRMIEEFDTGDPIVEGLAEDYFAEIVTAFLAGGRGRQGLIGTAPSVLVDAAAITAFGVAWLESRFGSPSS'},
 'CARD_42': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OXY-2-2',
  'Sequence': 'MIKSSWRKIAMLAAAVPLLLASGALWASTDAIHQKLTDLEKRSGGRLGVALINTADNSQILYRGDERFAMCSTSKVMAAAAVLKQSESNKEVVNKRLEINAADLVVWSPITEKHLQSGMTLAELSAATLQYSDNTAMNLIIGYLGGPEKVTAFARSIGDATFRLDRTEPTLNTAIPGDERDTSTPLAMAESLRKLTLGDALGEQQRAQLVTWLKGNTTGGQSIRAGLPESWVVGDKTGAGDYGTTNDIAVIWPEDHAPLILVTYFTQPQQDAKNRKEVLAAAAKIVTEGL'},
 'CARD_43': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'MOX-5',
  'Sequence': 'MQQRQSILWGALATLMWAGLAHAGDKAATDPLRPVVDASIRPLLKEHRIPGMAVAVLKDGKAHYFNYGVADRERAVGVSEQTLFEIGSVSKTLTATLGAYAVVQGGFELDDKASLFAPWLKGSAFDNITMGELATYSAGGLPLQFPEEVDSLEKMQAYYRQWTPAYSRGSHRQYANPSIGLFGYLAASSMKQPFDRLMEQTMLPGLGLYHTYLNVPEQPMGHYAYGYWKEDKPFRVTPAMLAEEPYGIKTSSADLLRFVKANISGVDNAAMQQAIDLTHQGQYAVGEMTQGLGWERYPYPVSEQTLLAGNSPAMIYNANPAAPAPAAAGHPVLFKKTGSTNGFGAYVAFVPAKGIGVVMLANRNYPNEGTLKAGHAILTQLAR'},
 'CARD_44': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-34',
  'Sequence': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMVSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW'},
 'CARD_45': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-69',
  'Sequence': 'MNIKALLLITSAIFISACSPYIVTANPNHSASKSDDKAEKIKNLFNEAHTTGVLVIHQGQTQQSYGNDLARASTEYVPASTFKMLNALIGLEHHKATTTEVFKWDGEKRLFPEWEKNMTLGDAMKASAIPVYQDLARRIGLELMSKEVKRVGYGNADIGTQVDNFWLVGPLKITPQQEAQFAYKLANKTLPFSQKVQDEVQSMLFIEEKNGNKIYAKSGWGWDVNPQVGWLTGWVVQPQGNIVAFSLNLEMKKGIPSSVRKEITYKSLEQLGIL'},
 'CARD_46': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-7',
  'Sequence': 'FFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDSWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNR'},
 'CARD_47': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-24',
  'Sequence': 'MRYIRLCIISLLATLPLAVHASPQPLEQIKLSESQLSGRVGMIEMDLASGRTLTAWRADERFPMMSTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLATVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARGTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR'},
 'CARD_48': {'Drug Class': 'fluoroquinolone antibiotic',
  'Name': 'QnrB47',
  'Sequence': 'MTLALVGEKIDRNRFTGEKVENSTFFNCDFSGADLSGTEFIGCQFYDRESQKGCNFSRAMLRDAIFKSCDLSMADFRNVSALGIEIRHCRAQGADFRGASFMNMITTRTWFCSAYITNTNLSYANFSKVVLEKCELWENRWMGTQVLGATFSGSDLSGGEFSTFDWRAANFTHCDLTNSELGDLDIRGVDLQGVKLDNYQASLLMERLGIAVIG'},
 'CARD_49': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OXA-256',
  'Sequence': 'MKTFAAYVIIACLSSTALAGSITENTSWNKEFSAEAVNGVFVLCKSSSKSCATNDLARASKEYLPASTFKIPDAIIGLETGVIKNEHQVFKWDGKPRAMKQWERDLTLRGAIQVSAVPVFQQIAREVGEVRMQKYLKKFSYGNQNISGGIDKFWLEGQLRISAVNQVEFLESLYLNKLSASKENQLIVKEALVTEAAPEYLVHSKTGFSGVGTESNPGVAWWVGWVEKETEVYFFAFNMDIDNESKLPLRKSIPTKIMESEGIIGG'},
 'CARD_50': {'Drug Class': 'fluoroquinolone antibiotic',
  'Name': 'QnrS6',
  'Sequence': 'METYRHTYRHHSFSHQDLSDITFTACTFIRCDFRRANLRDATFINCKFIEQGDIEGCHFDVADLRDASFQQCQLAMANFSNANCYGIELRECDLKGANFSRANFANQVSNRMYFCSAFITGCNLSYANMERVCLEKCELYENRWIGTHLAGASLKESDLSRGVFSEDVWGQFSLQGANLCHAELDGLDPRKVDTSGIKIASWQQEQLLEALGIVVFPD'},
 'CARD_51': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-330',

In [44]:
def CreateGeneralClass(base):
    for key, value in base.items():
        print(key)
        DrugClass = base[key]["Drug Class"]
        DrugClass = DrugClass.replace("antibiotic", "").lower().strip()
        base[key].update({"Drug Class": DrugClass.rstrip('s')})

        if "cephalosporin" in DrugClass:
            base[key].update({"Drug Class": "beta-lactam"})
        if "carbapenem" in DrugClass:
            base[key].update({"Drug Class": "beta-lactam"})
        if "penicillin" in DrugClass:
            base[key].update({"Drug Class": "beta-lactam"})
        if "beta_lactam" in DrugClass:
            base[key].update({"Drug Class": "beta-lactam"})
        if "betalactams" in DrugClass:
            base[key].update({"Drug Class": "beta-lactam"})
        if "penicillin" in DrugClass:
            base[key].update({"Drug Class": "beta-lactam"})
        if "phosphonic acid" in DrugClass:
            base[key].update({"Drug Class": "phosphonic acid"})

        Macrolide = bool(re.search(rf'\b{re.escape("macrolide")}\b', DrugClass))
        Lincosamide = bool(re.search(rf'\b{re.escape("lincosamide")}\b', DrugClass))
        Streptogramin = bool(re.search(rf'\b{re.escape("streptogramin")}\b', DrugClass))
        if Macrolide and Lincosamide and Streptogramin:
            base[key].update({"Drug Class": "MLS"})


    return base

In [45]:
MetaDict.keys()

dict_keys(['CARD_0', 'CARD_1', 'CARD_2', 'CARD_3', 'CARD_4', 'CARD_5', 'CARD_6', 'CARD_7', 'CARD_8', 'CARD_9', 'CARD_10', 'CARD_11', 'CARD_12', 'CARD_13', 'CARD_14', 'CARD_15', 'CARD_16', 'CARD_17', 'CARD_18', 'CARD_19', 'CARD_20', 'CARD_21', 'CARD_22', 'CARD_23', 'CARD_24', 'CARD_25', 'CARD_26', 'CARD_27', 'CARD_28', 'CARD_29', 'CARD_30', 'CARD_31', 'CARD_32', 'CARD_33', 'CARD_34', 'CARD_35', 'CARD_36', 'CARD_37', 'CARD_38', 'CARD_39', 'CARD_40', 'CARD_41', 'CARD_42', 'CARD_43', 'CARD_44', 'CARD_45', 'CARD_46', 'CARD_47', 'CARD_48', 'CARD_49', 'CARD_50', 'CARD_51', 'CARD_52', 'CARD_53', 'CARD_54', 'CARD_55', 'CARD_56', 'CARD_57', 'CARD_58', 'CARD_59', 'CARD_60', 'CARD_61', 'CARD_62', 'CARD_63', 'CARD_64', 'CARD_65', 'CARD_66', 'CARD_67', 'CARD_68', 'CARD_69', 'CARD_70', 'CARD_71', 'CARD_72', 'CARD_73', 'CARD_74', 'CARD_75', 'CARD_76', 'CARD_77', 'CARD_78', 'CARD_79', 'CARD_80', 'CARD_81', 'CARD_82', 'CARD_83', 'CARD_84', 'CARD_85', 'CARD_86', 'CARD_87', 'CARD_88', 'CARD_89', 'CARD_90', 'CARD_91', 'CARD_92', 'CARD_93', 'CARD_94', 'CARD_95', 'CARD_96', 'CARD_97', 'CARD_98', 'CARD_99', 'CARD_100', 'CARD_101', 'CARD_102', 'CARD_103', 'CARD_104', 'CARD_105', 'CARD_106', 'CARD_107', 'CARD_108', 'CARD_109', 'CARD_110', 'CARD_111', 'CARD_112', 'CARD_113', 'CARD_114', 'CARD_115', 'CARD_116', 'CARD_117', 'CARD_118', 'CARD_119', 'CARD_120', 'CARD_121', 'CARD_122', 'CARD_123', 'CARD_124', 'CARD_125', 'CARD_126', 'CARD_127', 'CARD_128', 'CARD_129', 'CARD_130', 'CARD_131', 'CARD_132', 'CARD_133', 'CARD_134', 'CARD_135', 'CARD_136', 'CARD_137', 'CARD_138', 'CARD_139', 'CARD_140', 'CARD_141', 'CARD_142', 'CARD_143', 'CARD_144', 'CARD_145', 'CARD_146', 'CARD_147', 'CARD_148', 'CARD_149', 'CARD_150', 'CARD_151', 'CARD_152', 'CARD_153', 'CARD_154', 'CARD_155', 'CARD_156', 'CARD_157', 'CARD_158', 'CARD_159', 'CARD_160', 'CARD_161', 'CARD_162', 'CARD_163', 'CARD_164', 'CARD_165', 'CARD_166', 'CARD_167', 'CARD_168', 'CARD_169', 'CARD_170', 'CARD_171', 'CARD_172', 'CARD_173', 'CARD_174', 'CARD_175', 'CARD_176', 'CARD_177', 'CARD_178', 'CARD_179', 'CARD_180', 'CARD_181', 'CARD_182', 'CARD_183', 'CARD_184', 'CARD_185', 'CARD_186', 'CARD_187', 'CARD_188', 'CARD_189', 'CARD_190', 'CARD_191', 'CARD_192', 'CARD_193', 'CARD_194', 'CARD_195', 'CARD_196', 'CARD_197', 'CARD_198', 'CARD_199', 'CARD_200', 'CARD_201', 'CARD_202', 'CARD_203', 'CARD_204', 'CARD_205', 'CARD_206', 'CARD_207', 'CARD_208', 'CARD_209', 'CARD_210', 'CARD_211', 'CARD_212', 'CARD_213', 'CARD_214', 'CARD_215', 'CARD_216', 'CARD_217', 'CARD_218', 'CARD_219', 'CARD_220', 'CARD_221', 'CARD_222', 'CARD_223', 'CARD_224', 'CARD_225', 'CARD_226', 'CARD_227', 'CARD_228', 'CARD_229', 'CARD_230', 'CARD_231', 'CARD_232', 'CARD_233', 'CARD_234', 'CARD_235', 'CARD_236', 'CARD_237', 'CARD_238', 'CARD_239', 'CARD_240', 'CARD_241', 'CARD_242', 'CARD_243', 'CARD_244', 'CARD_245', 'CARD_246', 'CARD_247', 'CARD_248', 'CARD_249', 'CARD_250', 'CARD_251', 'CARD_252', 'CARD_253', 'CARD_254', 'CARD_255', 'CARD_256', 'CARD_257', 'CARD_258', 'CARD_259', 'CARD_260', 'CARD_261', 'CARD_262', 'CARD_263', 'CARD_264', 'CARD_265', 'CARD_266', 'CARD_267', 'CARD_268', 'CARD_269', 'CARD_270', 'CARD_271', 'CARD_272', 'CARD_273', 'CARD_274', 'CARD_275', 'CARD_276', 'CARD_277', 'CARD_278', 'CARD_279', 'CARD_280', 'CARD_281', 'CARD_282', 'CARD_283', 'CARD_284', 'CARD_285', 'CARD_286', 'CARD_287', 'CARD_288', 'CARD_289', 'CARD_290', 'CARD_291', 'CARD_292', 'CARD_293', 'CARD_294', 'CARD_295', 'CARD_296', 'CARD_297', 'CARD_298', 'CARD_299', 'CARD_300', 'CARD_301', 'CARD_302', 'CARD_303', 'CARD_304', 'CARD_305', 'CARD_306', 'CARD_307', 'CARD_308', 'CARD_309', 'CARD_310', 'CARD_311', 'CARD_312', 'CARD_313', 'CARD_314', 'CARD_315', 'CARD_316', 'CARD_317', 'CARD_318', 'CARD_319', 'CARD_320', 'CARD_321', 'CARD_322', 'CARD_323', 'CARD_324', 'CARD_325', 'CARD_326', 'CARD_327', 'CARD_328', 'CARD_329', 'CARD_330', 'CARD_331', 'CARD_332', 'CARD_333', 'CARD_334', 'CARD_335', 'CARD_336', 'CARD_337', 'CARD_338', 'CARD_339', 'CARD_340', 'CARD_341', 'CARD_342', 'CARD_343', 'CARD_344', 'CARD_345', 'CARD_346', 'CARD_347', 'CARD_348', 'CARD_349', 'CARD_350', 'CARD_351', 'CARD_352', 'CARD_353', 'CARD_354', 'CARD_355', 'CARD_356', 'CARD_357', 'CARD_358', 'CARD_359', 'CARD_360', 'CARD_361', 'CARD_362', 'CARD_363', 'CARD_364', 'CARD_365', 'CARD_366', 'CARD_367', 'CARD_368', 'CARD_369', 'CARD_370', 'CARD_371', 'CARD_372', 'CARD_373', 'CARD_374', 'CARD_375', 'CARD_376', 'CARD_377', 'CARD_378', 'CARD_379', 'CARD_380', 'CARD_381', 'CARD_382', 'CARD_383', 'CARD_384', 'CARD_385', 'CARD_386', 'CARD_387', 'CARD_388', 'CARD_389', 'CARD_390', 'CARD_391', 'CARD_392', 'CARD_393', 'CARD_394', 'CARD_395', 'CARD_396', 'CARD_397', 'CARD_398', 'CARD_399', 'CARD_400', 'CARD_401', 'CARD_402', 'CARD_403', 'CARD_404', 'CARD_405', 'CARD_406', 'CARD_407', 'CARD_408', 'CARD_409', 'CARD_410', 'CARD_411', 'CARD_412', 'CARD_413', 'CARD_414', 'CARD_415', 'CARD_416', 'CARD_417', 'CARD_418', 'CARD_419', 'CARD_420', 'CARD_421', 'CARD_422', 'CARD_423', 'CARD_424', 'CARD_425', 'CARD_426', 'CARD_427', 'CARD_428', 'CARD_429', 'CARD_430', 'CARD_431', 'CARD_432', 'CARD_433', 'CARD_434', 'CARD_435', 'CARD_436', 'CARD_437', 'CARD_438', 'CARD_439', 'CARD_440', 'CARD_441', 'CARD_442', 'CARD_443', 'CARD_444', 'CARD_445', 'CARD_446', 'CARD_447', 'CARD_448', 'CARD_449', 'CARD_450', 'CARD_451', 'CARD_452', 'CARD_453', 'CARD_454', 'CARD_455', 'CARD_456', 'CARD_457', 'CARD_458', 'CARD_459', 'CARD_460', 'CARD_461', 'CARD_462', 'CARD_463', 'CARD_464', 'CARD_465', 'CARD_466', 'CARD_467', 'CARD_468', 'CARD_469', 'CARD_470', 'CARD_471', 'CARD_472', 'CARD_473', 'CARD_474', 'CARD_475', 'CARD_476', 'CARD_477', 'CARD_478', 'CARD_479', 'CARD_480', 'CARD_481', 'CARD_482', 'CARD_483', 'CARD_484', 'CARD_485', 'CARD_486', 'CARD_487', 'CARD_488', 'CARD_489', 'CARD_490', 'CARD_491', 'CARD_492', 'CARD_493', 'CARD_494', 'CARD_495', 'CARD_496', 'CARD_497', 'CARD_498', 'CARD_499', 'CARD_500', 'CARD_501', 'CARD_502', 'CARD_503', 'CARD_504', 'CARD_505', 'CARD_506', 'CARD_507', 'CARD_508', 'CARD_509', 'CARD_510', 'CARD_511', 'CARD_512', 'CARD_513', 'CARD_514', 'CARD_515', 'CARD_516', 'CARD_517', 'CARD_518', 'CARD_519', 'CARD_520', 'CARD_521', 'CARD_522', 'CARD_523', 'CARD_524', 'CARD_525', 'CARD_526', 'CARD_527', 'CARD_528', 'CARD_529', 'CARD_530', 'CARD_531', 'CARD_532', 'CARD_533', 'CARD_534', 'CARD_535', 'CARD_536', 'CARD_537', 'CARD_538', 'CARD_539', 'CARD_540', 'CARD_541', 'CARD_542', 'CARD_543', 'CARD_544', 'CARD_545', 'CARD_546', 'CARD_547', 'CARD_548', 'CARD_549', 'CARD_550', 'CARD_551', 'CARD_552', 'CARD_553', 'CARD_554', 'CARD_555', 'CARD_556', 'CARD_557', 'CARD_558', 'CARD_559', 'CARD_560', 'CARD_561', 'CARD_562', 'CARD_563', 'CARD_564', 'CARD_565', 'CARD_566', 'CARD_567', 'CARD_568', 'CARD_569', 'CARD_570', 'CARD_571', 'CARD_572', 'CARD_573', 'CARD_574', 'CARD_575', 'CARD_576', 'CARD_577', 'CARD_578', 'CARD_579', 'CARD_580', 'CARD_581', 'CARD_582', 'CARD_583', 'CARD_584', 'CARD_585', 'CARD_586', 'CARD_587', 'CARD_588', 'CARD_589', 'CARD_590', 'CARD_591', 'CARD_592', 'CARD_593', 'CARD_594', 'CARD_595', 'CARD_596', 'CARD_597', 'CARD_598', 'CARD_599', 'CARD_600', 'CARD_601', 'CARD_602', 'CARD_603', 'CARD_604', 'CARD_605', 'CARD_606', 'CARD_607', 'CARD_608', 'CARD_609', 'CARD_610', 'CARD_611', 'CARD_612', 'CARD_613', 'CARD_614', 'CARD_615', 'CARD_616', 'CARD_617', 'CARD_618', 'CARD_619', 'CARD_620', 'CARD_621', 'CARD_622', 'CARD_623', 'CARD_624', 'CARD_625', 'CARD_626', 'CARD_627', 'CARD_628', 'CARD_629', 'CARD_630', 'CARD_631', 'CARD_632', 'CARD_633', 'CARD_634', 'CARD_635', 'CARD_636', 'CARD_637', 'CARD_638', 'CARD_639', 'CARD_640', 'CARD_641', 'CARD_642', 'CARD_643', 'CARD_644', 'CARD_645', 'CARD_646', 'CARD_647', 'CARD_648', 'CARD_649', 'CARD_650', 'CARD_651', 'CARD_652', 'CARD_653', 'CARD_654', 'CARD_655', 'CARD_656', 'CARD_657', 'CARD_658', 'CARD_659', 'CARD_660', 'CARD_661', 'CARD_662', 'CARD_663', 'CARD_664', 'CARD_665', 'CARD_666', 'CARD_667', 'CARD_668', 'CARD_669', 'CARD_670', 'CARD_671', 'CARD_672', 'CARD_673', 'CARD_674', 'CARD_675', 'CARD_676', 'CARD_677', 'CARD_678', 'CARD_679', 'CARD_680', 'CARD_681', 'CARD_682', 'CARD_683', 'CARD_684', 'CARD_685', 'CARD_686', 'CARD_687', 'CARD_688', 'CARD_689', 'CARD_690', 'CARD_691', 'CARD_692', 'CARD_693', 'CARD_694', 'CARD_695', 'CARD_696', 'CARD_697', 'CARD_698', 'CARD_699', 'CARD_700', 'CARD_701', 'CARD_702', 'CARD_703', 'CARD_704', 'CARD_705', 'CARD_706', 'CARD_707', 'CARD_708', 'CARD_709', 'CARD_710', 'CARD_711', 'CARD_712', 'CARD_713', 'CARD_714', 'CARD_715', 'CARD_716', 'CARD_717', 'CARD_718', 'CARD_719', 'CARD_720', 'CARD_721', 'CARD_722', 'CARD_723', 'CARD_724', 'CARD_725', 'CARD_726', 'CARD_727', 'CARD_728', 'CARD_729', 'CARD_730', 'CARD_731', 'CARD_732', 'CARD_733', 'CARD_734', 'CARD_735', 'CARD_736', 'CARD_737', 'CARD_738', 'CARD_739', 'CARD_740', 'CARD_741', 'CARD_742', 'CARD_743', 'CARD_744', 'CARD_745', 'CARD_746', 'CARD_747', 'CARD_748', 'CARD_749', 'CARD_750', 'CARD_751', 'CARD_752', 'CARD_753', 'CARD_754', 'CARD_755', 'CARD_756', 'CARD_757', 'CARD_758', 'CARD_759', 'CARD_760', 'CARD_761', 'CARD_762', 'CARD_763', 'CARD_764', 'CARD_765', 'CARD_766', 'CARD_767', 'CARD_768', 'CARD_769', 'CARD_770', 'CARD_771', 'CARD_772', 'CARD_773', 'CARD_774', 'CARD_775', 'CARD_776', 'CARD_777', 'CARD_778', 'CARD_779', 'CARD_780', 'CARD_781', 'CARD_782', 'CARD_783', 'CARD_784', 'CARD_785', 'CARD_786', 'CARD_787', 'CARD_788', 'CARD_789', 'CARD_790', 'CARD_791', 'CARD_792', 'CARD_793', 'CARD_794', 'CARD_795', 'CARD_796', 'CARD_797', 'CARD_798', 'CARD_799', 'CARD_800', 'CARD_801', 'CARD_802', 'CARD_803', 'CARD_804', 'CARD_805', 'CARD_806', 'CARD_807', 'CARD_808', 'CARD_809', 'CARD_810', 'CARD_811', 'CARD_812', 'CARD_813', 'CARD_814', 'CARD_815', 'CARD_816', 'CARD_817', 'CARD_818', 'CARD_819', 'CARD_820', 'CARD_821', 'CARD_822', 'CARD_823', 'CARD_824', 'CARD_825', 'CARD_826', 'CARD_827', 'CARD_828', 'CARD_829', 'CARD_830', 'CARD_831', 'CARD_832', 'CARD_833', 'CARD_834', 'CARD_835', 'CARD_836', 'CARD_837', 'CARD_838', 'CARD_839', 'CARD_840', 'CARD_841', 'CARD_842', 'CARD_843', 'CARD_844', 'CARD_845', 'CARD_846', 'CARD_847', 'CARD_848', 'CARD_849', 'CARD_850', 'CARD_851', 'CARD_852', 'CARD_853', 'CARD_854', 'CARD_855', 'CARD_856', 'CARD_857', 'CARD_858', 'CARD_859', 'CARD_860', 'CARD_861', 'CARD_862', 'CARD_863', 'CARD_864', 'CARD_865', 'CARD_866', 'CARD_867', 'CARD_868', 'CARD_869', 'CARD_870', 'CARD_871', 'CARD_872', 'CARD_873', 'CARD_874', 'CARD_875', 'CARD_876', 'CARD_877', 'CARD_878', 'CARD_879', 'CARD_880', 'CARD_881', 'CARD_882', 'CARD_883', 'CARD_884', 'CARD_885', 'CARD_886', 'CARD_887', 'CARD_888', 'CARD_889', 'CARD_890', 'CARD_891', 'CARD_892', 'CARD_893', 'CARD_894', 'CARD_895', 'CARD_896', 'CARD_897', 'CARD_898', 'CARD_899', 'CARD_900', 'CARD_901', 'CARD_902', 'CARD_903', 'CARD_904', 'CARD_905', 'CARD_906', 'CARD_907', 'CARD_908', 'CARD_909', 'CARD_910', 'CARD_911', 'CARD_912', 'CARD_913', 'CARD_914', 'CARD_915', 'CARD_916', 'CARD_917', 'CARD_918', 'CARD_919', 'CARD_920', 'CARD_921', 'CARD_922', 'CARD_923', 'CARD_924', 'CARD_925', 'CARD_926', 'CARD_927', 'CARD_928', 'CARD_929', 'CARD_930', 'CARD_931', 'CARD_932', 'CARD_933', 'CARD_934', 'CARD_935', 'CARD_936', 'CARD_937', 'CARD_938', 'CARD_939', 'CARD_940', 'CARD_941', 'CARD_942', 'CARD_943', 'CARD_944', 'CARD_945', 'CARD_946', 'CARD_947', 'CARD_948', 'CARD_949', 'CARD_950', 'CARD_951', 'CARD_952', 'CARD_953', 'CARD_954', 'CARD_955', 'CARD_956', 'CARD_957', 'CARD_958', 'CARD_959', 'CARD_960', 'CARD_961', 'CARD_962', 'CARD_963', 'CARD_964', 'CARD_965', 'CARD_966', 'CARD_967', 'CARD_968', 'CARD_969', 'CARD_970', 'CARD_971', 'CARD_972', 'CARD_973', 'CARD_974', 'CARD_975', 'CARD_976', 'CARD_977', 'CARD_978', 'CARD_979', 'CARD_980', 'CARD_981', 'CARD_982', 'CARD_983', 'CARD_984', 'CARD_985', 'CARD_986', 'CARD_987', 'CARD_988', 'CARD_989', 'CARD_990', 'CARD_991', 'CARD_992', 'CARD_993', 'CARD_994', 'CARD_995', 'CARD_996', 'CARD_997', 'CARD_998', 'CARD_999', 'CARD_1000', 'CARD_1001', 'CARD_1002', 'CARD_1003', 'CARD_1004', 'CARD_1005', 'CARD_1006', 'CARD_1007', 'CARD_1008', 'CARD_1009', 'CARD_1010', 'CARD_1011', 'CARD_1012', 'CARD_1013', 'CARD_1014', 'CARD_1015', 'CARD_1016', 'CARD_1017', 'CARD_1018', 'CARD_1019', 'CARD_1020', 'CARD_1021', 'CARD_1022', 'CARD_1023', 'CARD_1024', 'CARD_1025', 'CARD_1026', 'CARD_1027', 'CARD_1028', 'CARD_1029', 'CARD_1030', 'CARD_1031', 'CARD_1032', 'CARD_1033', 'CARD_1034', 'CARD_1035', 'CARD_1036', 'CARD_1037', 'CARD_1038', 'CARD_1039', 'CARD_1040', 'CARD_1041', 'CARD_1042', 'CARD_1043', 'CARD_1044', 'CARD_1045', 'CARD_1046', 'CARD_1047', 'CARD_1048', 'CARD_1049', 'CARD_1050', 'CARD_1051', 'CARD_1052', 'CARD_1053', 'CARD_1054', 'CARD_1055', 'CARD_1056', 'CARD_1057', 'CARD_1058', 'CARD_1059', 'CARD_1060', 'CARD_1061', 'CARD_1062', 'CARD_1063', 'CARD_1064', 'CARD_1065', 'CARD_1066', 'CARD_1067', 'CARD_1068', 'CARD_1069', 'CARD_1070', 'CARD_1071', 'CARD_1072', 'CARD_1073', 'CARD_1074', 'CARD_1075', 'CARD_1076', 'CARD_1077', 'CARD_1078', 'CARD_1079', 'CARD_1080', 'CARD_1081', 'CARD_1082', 'CARD_1083', 'CARD_1084', 'CARD_1085', 'CARD_1086', 'CARD_1087', 'CARD_1088', 'CARD_1089', 'CARD_1090', 'CARD_1091', 'CARD_1092', 'CARD_1093', 'CARD_1094', 'CARD_1095', 'CARD_1096', 'CARD_1097', 'CARD_1098', 'CARD_1099', 'CARD_1100', 'CARD_1101', 'CARD_1102', 'CARD_1103', 'CARD_1104', 'CARD_1105', 'CARD_1106', 'CARD_1107', 'CARD_1108', 'CARD_1109', 'CARD_1110', 'CARD_1111', 'CARD_1112', 'CARD_1113', 'CARD_1114', 'CARD_1115', 'CARD_1116', 'CARD_1117', 'CARD_1118', 'CARD_1119', 'CARD_1120', 'CARD_1121', 'CARD_1122', 'CARD_1123', 'CARD_1124', 'CARD_1125', 'CARD_1126', 'CARD_1127', 'CARD_1128', 'CARD_1129', 'CARD_1130', 'CARD_1131', 'CARD_1132', 'CARD_1133', 'CARD_1134', 'CARD_1135', 'CARD_1136', 'CARD_1137', 'CARD_1138', 'CARD_1139', 'CARD_1140', 'CARD_1141', 'CARD_1142', 'CARD_1143', 'CARD_1144', 'CARD_1145', 'CARD_1146', 'CARD_1147', 'CARD_1148', 'CARD_1149', 'CARD_1150', 'CARD_1151', 'CARD_1152', 'CARD_1153', 'CARD_1154', 'CARD_1155', 'CARD_1156', 'CARD_1157', 'CARD_1158', 'CARD_1159', 'CARD_1160', 'CARD_1161', 'CARD_1162', 'CARD_1163', 'CARD_1164', 'CARD_1165', 'CARD_1166', 'CARD_1167', 'CARD_1168', 'CARD_1169', 'CARD_1170', 'CARD_1171', 'CARD_1172', 'CARD_1173', 'CARD_1174', 'CARD_1175', 'CARD_1176', 'CARD_1177', 'CARD_1178', 'CARD_1179', 'CARD_1180', 'CARD_1181', 'CARD_1182', 'CARD_1183', 'CARD_1184', 'CARD_1185', 'CARD_1186', 'CARD_1187', 'CARD_1188', 'CARD_1189', 'CARD_1190', 'CARD_1191', 'CARD_1192', 'CARD_1193', 'CARD_1194', 'CARD_1195', 'CARD_1196', 'CARD_1197', 'CARD_1198', 'CARD_1199', 'CARD_1200', 'CARD_1201', 'CARD_1202', 'CARD_1203', 'CARD_1204', 'CARD_1205', 'CARD_1206', 'CARD_1207', 'CARD_1208', 'CARD_1209', 'CARD_1210', 'CARD_1211', 'CARD_1212', 'CARD_1213', 'CARD_1214', 'CARD_1215', 'CARD_1216', 'CARD_1217', 'CARD_1218', 'CARD_1219', 'CARD_1220', 'CARD_1221', 'CARD_1222', 'CARD_1223', 'CARD_1224', 'CARD_1225', 'CARD_1226', 'CARD_1227', 'CARD_1228', 'CARD_1229', 'CARD_1230', 'CARD_1231', 'CARD_1232', 'CARD_1233', 'CARD_1234', 'CARD_1235', 'CARD_1236', 'CARD_1237', 'CARD_1238', 'CARD_1239', 'CARD_1240', 'CARD_1241', 'CARD_1242', 'CARD_1243', 'CARD_1244', 'CARD_1245', 'CARD_1246', 'CARD_1247', 'CARD_1248', 'CARD_1249', 'CARD_1250', 'CARD_1251', 'CARD_1252', 'CARD_1253', 'CARD_1254', 'CARD_1255', 'CARD_1256', 'CARD_1257', 'CARD_1258', 'CARD_1259', 'CARD_1260', 'CARD_1261', 'CARD_1262', 'CARD_1263', 'CARD_1264', 'CARD_1265', 'CARD_1266', 'CARD_1267', 'CARD_1268', 'CARD_1269', 'CARD_1270', 'CARD_1271', 'CARD_1272', 'CARD_1273', 'CARD_1274', 'CARD_1275', 'CARD_1276', 'CARD_1277', 'CARD_1278', 'CARD_1279', 'CARD_1280', 'CARD_1281', 'CARD_1282', 'CARD_1283', 'CARD_1284', 'CARD_1285', 'CARD_1286', 'CARD_1287', 'CARD_1288', 'CARD_1289', 'CARD_1290', 'CARD_1291', 'CARD_1292', 'CARD_1293', 'CARD_1294', 'CARD_1295', 'CARD_1296', 'CARD_1297', 'CARD_1298', 'CARD_1299', 'CARD_1300', 'CARD_1301', 'CARD_1302', 'CARD_1303', 'CARD_1304', 'CARD_1305', 'CARD_1306', 'CARD_1307', 'CARD_1308', 'CARD_1309', 'CARD_1310', 'CARD_1311', 'CARD_1312', 'CARD_1313', 'CARD_1314', 'CARD_1315', 'CARD_1316', 'CARD_1317', 'CARD_1318', 'CARD_1319', 'CARD_1320', 'CARD_1321', 'CARD_1322', 'CARD_1323', 'CARD_1324', 'CARD_1325', 'CARD_1326', 'CARD_1327', 'CARD_1328', 'CARD_1329', 'CARD_1330', 'CARD_1331', 'CARD_1332', 'CARD_1333', 'CARD_1334', 'CARD_1335', 'CARD_1336', 'CARD_1337', 'CARD_1338', 'CARD_1339', 'CARD_1340', 'CARD_1341', 'CARD_1342', 'CARD_1343', 'CARD_1344', 'CARD_1345', 'CARD_1346', 'CARD_1347', 'CARD_1348', 'CARD_1349', 'CARD_1350', 'CARD_1351', 'CARD_1352', 'CARD_1353', 'CARD_1354', 'CARD_1355', 'CARD_1356', 'CARD_1357', 'CARD_1358', 'CARD_1359', 'CARD_1360', 'CARD_1361', 'CARD_1362', 'CARD_1363', 'CARD_1364', 'CARD_1365', 'CARD_1366', 'CARD_1367', 'CARD_1368', 'CARD_1369', 'CARD_1370', 'CARD_1371', 'CARD_1372', 'CARD_1373', 'CARD_1374', 'CARD_1375', 'CARD_1376', 'CARD_1377', 'CARD_1378', 'CARD_1379', 'CARD_1380', 'CARD_1381', 'CARD_1382', 'CARD_1383', 'CARD_1384', 'CARD_1385', 'CARD_1386', 'CARD_1387', 'CARD_1388', 'CARD_1389', 'CARD_1390', 'CARD_1391', 'CARD_1392', 'CARD_1393', 'CARD_1394', 'CARD_1395', 'CARD_1396', 'CARD_1397', 'CARD_1398', 'CARD_1399', 'CARD_1400', 'CARD_1401', 'CARD_1402', 'CARD_1403', 'CARD_1404', 'CARD_1405', 'CARD_1406', 'CARD_1407', 'CARD_1408', 'CARD_1409', 'CARD_1410', 'CARD_1411', 'CARD_1412', 'CARD_1413', 'CARD_1414', 'CARD_1415', 'CARD_1416', 'CARD_1417', 'CARD_1418', 'CARD_1419', 'CARD_1420', 'CARD_1421', 'CARD_1422', 'CARD_1423', 'CARD_1424', 'CARD_1425', 'CARD_1426', 'CARD_1427', 'CARD_1428', 'CARD_1429', 'CARD_1430', 'CARD_1431', 'CARD_1432', 'CARD_1433', 'CARD_1434', 'CARD_1435', 'CARD_1436', 'CARD_1437', 'CARD_1438', 'CARD_1439', 'CARD_1440', 'CARD_1441', 'CARD_1442', 'CARD_1443', 'CARD_1444', 'CARD_1445', 'CARD_1446', 'CARD_1447', 'CARD_1448', 'CARD_1449', 'CARD_1450', 'CARD_1451', 'CARD_1452', 'CARD_1453', 'CARD_1454', 'CARD_1455', 'CARD_1456', 'CARD_1457', 'CARD_1458', 'CARD_1459', 'CARD_1460', 'CARD_1461', 'CARD_1462', 'CARD_1463', 'CARD_1464', 'CARD_1465', 'CARD_1466', 'CARD_1467', 'CARD_1468', 'CARD_1469', 'CARD_1470', 'CARD_1471', 'CARD_1472', 'CARD_1473', 'CARD_1474', 'CARD_1475', 'CARD_1476', 'CARD_1477', 'CARD_1478', 'CARD_1479', 'CARD_1480', 'CARD_1481', 'CARD_1482', 'CARD_1483', 'CARD_1484', 'CARD_1485', 'CARD_1486', 'CARD_1487', 'CARD_1488', 'CARD_1489', 'CARD_1490', 'CARD_1491', 'CARD_1492', 'CARD_1493', 'CARD_1494', 'CARD_1495', 'CARD_1496', 'CARD_1497', 'CARD_1498', 'CARD_1499', 'CARD_1500', 'CARD_1501', 'CARD_1502', 'CARD_1503', 'CARD_1504', 'CARD_1505', 'CARD_1506', 'CARD_1507', 'CARD_1508', 'CARD_1509', 'CARD_1510', 'CARD_1511', 'CARD_1512', 'CARD_1513', 'CARD_1514', 'CARD_1515', 'CARD_1516', 'CARD_1517', 'CARD_1518', 'CARD_1519', 'CARD_1520', 'CARD_1521', 'CARD_1522', 'CARD_1523', 'CARD_1524', 'CARD_1525', 'CARD_1526', 'CARD_1527', 'CARD_1528', 'CARD_1529', 'CARD_1530', 'CARD_1531', 'CARD_1532', 'CARD_1533', 'CARD_1534', 'CARD_1535', 'CARD_1536', 'CARD_1537', 'CARD_1538', 'CARD_1539', 'CARD_1540', 'CARD_1541', 'CARD_1542', 'CARD_1543', 'CARD_1544', 'CARD_1545', 'CARD_1546', 'CARD_1547', 'CARD_1548', 'CARD_1549', 'CARD_1550', 'CARD_1551', 'CARD_1552', 'CARD_1553', 'CARD_1554', 'CARD_1555', 'CARD_1556', 'CARD_1557', 'CARD_1558', 'CARD_1559', 'CARD_1560', 'CARD_1561', 'CARD_1562', 'CARD_1563', 'CARD_1564', 'CARD_1565', 'CARD_1566', 'CARD_1567', 'CARD_1568', 'CARD_1569', 'CARD_1570', 'CARD_1571', 'CARD_1572', 'CARD_1573', 'CARD_1574', 'CARD_1575', 'CARD_1576', 'CARD_1577', 'CARD_1578', 'CARD_1579', 'CARD_1580', 'CARD_1581', 'CARD_1582', 'CARD_1583', 'CARD_1584', 'CARD_1585', 'CARD_1586', 'CARD_1587', 'CARD_1588', 'CARD_1589', 'CARD_1590', 'CARD_1591', 'CARD_1592', 'CARD_1593', 'CARD_1594', 'CARD_1595', 'CARD_1596', 'CARD_1597', 'CARD_1598', 'CARD_1599', 'CARD_1600', 'CARD_1601', 'CARD_1602', 'CARD_1603', 'CARD_1604', 'CARD_1605', 'CARD_1606', 'CARD_1607', 'CARD_1608', 'CARD_1609', 'CARD_1610', 'CARD_1611', 'CARD_1612', 'CARD_1613', 'CARD_1614', 'CARD_1615', 'CARD_1616', 'CARD_1617', 'CARD_1618', 'CARD_1619', 'CARD_1620', 'CARD_1621', 'CARD_1622', 

In [46]:
MetaDict = CreateGeneralClass(MetaDict)

CARD_0
CARD_1
CARD_2
CARD_3
CARD_4
CARD_5
CARD_6
CARD_7
CARD_8
CARD_9
CARD_10
CARD_11
CARD_12
CARD_13
CARD_14
CARD_15
CARD_16
CARD_17
CARD_18
CARD_19
CARD_20
CARD_21
CARD_22
CARD_23
CARD_24
CARD_25
CARD_26
CARD_27
CARD_28
CARD_29
CARD_30
CARD_31
CARD_32
CARD_33
CARD_34
CARD_35
CARD_36
CARD_37
CARD_38
CARD_39
CARD_40
CARD_41
CARD_42
CARD_43
CARD_44
CARD_45
CARD_46
CARD_47
CARD_48
CARD_49
CARD_50
CARD_51
CARD_52
CARD_53
CARD_54
CARD_55
CARD_56
CARD_57
CARD_58
CARD_59
CARD_60
CARD_61
CARD_62
CARD_63
CARD_64
CARD_65
CARD_66
CARD_67
CARD_68
CARD_69
CARD_70
CARD_71
CARD_72
CARD_73
CARD_74
CARD_75
CARD_76
CARD_77
CARD_78
CARD_79
CARD_80
CARD_81
CARD_82
CARD_83
CARD_84
CARD_85
CARD_86
CARD_87
CARD_88
CARD_89
CARD_90
CARD_91
CARD_92
CARD_93
CARD_94
CARD_95
CARD_96
CARD_97
CARD_98
CARD_99
CARD_100
CARD_101
CARD_102
CARD_103
CARD_104
CARD_105
CARD_106
CARD_107
CARD_108
CARD_109
CARD_110
CARD_111
CARD_112
CARD_113
CARD_114
CARD_115
CARD_116
CARD_117
CARD_118
CARD_119
CARD_120
CARD_121
CARD_122
CARD_123
CARD_124
CARD_125
CARD_126
CARD_127
CARD_128
CARD_129
CARD_130
CARD_131
CARD_132
CARD_133
CARD_134
CARD_135
CARD_136
CARD_137
CARD_138
CARD_139
CARD_140
CARD_141
CARD_142
CARD_143
CARD_144
CARD_145
CARD_146
CARD_147
CARD_148
CARD_149
CARD_150
CARD_151
CARD_152
CARD_153
CARD_154
CARD_155
CARD_156
CARD_157
CARD_158
CARD_159
CARD_160
CARD_161
CARD_162
CARD_163
CARD_164
CARD_165
CARD_166
CARD_167
CARD_168
CARD_169
CARD_170
CARD_171
CARD_172
CARD_173
CARD_174
CARD_175
CARD_176
CARD_177
CARD_178
CARD_179
CARD_180
CARD_181
CARD_182
CARD_183
CARD_184
CARD_185
CARD_186
CARD_187
CARD_188
CARD_189
CARD_190
CARD_191
CARD_192
CARD_193
CARD_194
CARD_195
CARD_196
CARD_197
CARD_198
CARD_199
CARD_200
CARD_201
CARD_202
CARD_203
CARD_204
CARD_205
CARD_206
CARD_207
CARD_208
CARD_209
CARD_210
CARD_211
CARD_212
CARD_213
CARD_214
CARD_215
CARD_216
CARD_217
CARD_218
CARD_219
CARD_220
CARD_221
CARD_222
CARD_223
CARD_224
CARD_225
CARD_226
CARD_227
CARD_228
CARD_229
CARD_230
CARD_231
CARD_232
CARD_233
CARD_234
CARD_235
CARD_236
CARD_237
CARD_238
CARD_239
CARD_240
CARD_241
CARD_242
CARD_243
CARD_244
CARD_245
CARD_246
CARD_247
CARD_248
CARD_249
CARD_250
CARD_251
CARD_252
CARD_253
CARD_254
CARD_255
CARD_256
CARD_257
CARD_258
CARD_259
CARD_260
CARD_261
CARD_262
CARD_263
CARD_264
CARD_265
CARD_266
CARD_267
CARD_268
CARD_269
CARD_270
CARD_271
CARD_272
CARD_273
CARD_274
CARD_275
CARD_276
CARD_277
CARD_278
CARD_279
CARD_280
CARD_281
CARD_282
CARD_283
CARD_284
CARD_285
CARD_286
CARD_287
CARD_288
CARD_289
CARD_290
CARD_291
CARD_292
CARD_293
CARD_294
CARD_295
CARD_296
CARD_297
CARD_298
CARD_299
CARD_300
CARD_301
CARD_302
CARD_303
CARD_304
CARD_305
CARD_306
CARD_307
CARD_308
CARD_309
CARD_310
CARD_311
CARD_312
CARD_313
CARD_314
CARD_315
CARD_316
CARD_317
CARD_318
CARD_319
CARD_320
CARD_321
CARD_322
CARD_323
CARD_324
CARD_325
CARD_326
CARD_327
CARD_328
CARD_329
CARD_330
CARD_331
CARD_332
CARD_333
CARD_334
CARD_335
CARD_336
CARD_337
CARD_338
CARD_339
CARD_340
CARD_341
CARD_342
CARD_343
CARD_344
CARD_345
CARD_346
CARD_347
CARD_348
CARD_349
CARD_350
CARD_351
CARD_352
CARD_353
CARD_354
CARD_355
CARD_356
CARD_357
CARD_358
CARD_359
CARD_360
CARD_361
CARD_362
CARD_363
CARD_364
CARD_365
CARD_366
CARD_367
CARD_368
CARD_369
CARD_370
CARD_371
CARD_372
CARD_373
CARD_374
CARD_375
CARD_376
CARD_377
CARD_378
CARD_379
CARD_380
CARD_381
CARD_382
CARD_383
CARD_384
CARD_385
CARD_386
CARD_387
CARD_388
CARD_389
CARD_390
CARD_391
CARD_392
CARD_393
CARD_394
CARD_395
CARD_396
CARD_397
CARD_398
CARD_399
CARD_400
CARD_401
CARD_402
CARD_403
CARD_404
CARD_405
CARD_406
CARD_407
CARD_408
CARD_409
CARD_410
CARD_411
CARD_412
CARD_413
CARD_414
CARD_415
CARD_416
CARD_417
CARD_418
CARD_419
CARD_420
CARD_421
CARD_422
CARD_423
CARD_424
CARD_425
CARD_426
CARD_427
CARD_428
CARD_429
CARD_430
CARD_431
CARD_432
CARD_433
CARD_434
CARD_435
CARD_436
CARD_437
CARD_438
CARD_439
CARD_440
CARD_441
CARD_442
CARD_443
CARD_444
CARD_445
CARD_446
CARD_447
CARD_448
CARD_449
CARD_450
CARD_451
CARD_452
CARD_453
CARD_454
CARD_455
CARD_456
CARD_457
CARD_458
CARD_459
CARD_460
CARD_461
CARD_462
CARD_463
CARD_464
CARD_465
CARD_466
CARD_467
CARD_468
CARD_469
CARD_470
CARD_471
CARD_472
CARD_473
CARD_474
CARD_475
CARD_476
CARD_477
CARD_478
CARD_479
CARD_480
CARD_481
CARD_482
CARD_483
CARD_484
CARD_485
CARD_486
CARD_487
CARD_488
CARD_489
CARD_490
CARD_491
CARD_492
CARD_493
CARD_494
CARD_495
CARD_496
CARD_497
CARD_498
CARD_499
CARD_500
CARD_501
CARD_502
CARD_503
CARD_504
CARD_505
CARD_506
CARD_507
CARD_508
CARD_509
CARD_510
CARD_511
CARD_512
CARD_513
CARD_514
CARD_515
CARD_516
CARD_517
CARD_518
CARD_519
CARD_520
CARD_521
CARD_522
CARD_523
CARD_524
CARD_525
CARD_526
CARD_527
CARD_528
CARD_529
CARD_530
CARD_531
CARD_532
CARD_533
CARD_534
CARD_535
CARD_536
CARD_537
CARD_538
CARD_539
CARD_540
CARD_541
CARD_542
CARD_543
CARD_544
CARD_545
CARD_546
CARD_547
CARD_548
CARD_549
CARD_550
CARD_551
CARD_552
CARD_553
CARD_554
CARD_555
CARD_556
CARD_557
CARD_558
CARD_559
CARD_560
CARD_561
CARD_562
CARD_563
CARD_564
CARD_565
CARD_566
CARD_567
CARD_568
CARD_569
CARD_570
CARD_571
CARD_572
CARD_573
CARD_574
CARD_575
CARD_576
CARD_577
CARD_578
CARD_579
CARD_580
CARD_581
CARD_582
CARD_583
CARD_584
CARD_585
CARD_586
CARD_587
CARD_588
CARD_589
CARD_590
CARD_591
CARD_592
CARD_593
CARD_594
CARD_595
CARD_596
CARD_597
CARD_598
CARD_599
CARD_600
CARD_601
CARD_602
CARD_603
CARD_604
CARD_605
CARD_606
CARD_607
CARD_608
CARD_609
CARD_610
CARD_611
CARD_612
CARD_613
CARD_614
CARD_615
CARD_616
CARD_617
CARD_618
CARD_619
CARD_620
CARD_621
CARD_622
CARD_623
CARD_624
CARD_625
CARD_626
CARD_627
CARD_628
CARD_629
CARD_630
CARD_631
CARD_632
CARD_633
CARD_634
CARD_635
CARD_636
CARD_637
CARD_638
CARD_639
CARD_640
CARD_641
CARD_642
CARD_643
CARD_644
CARD_645
CARD_646
CARD_647
CARD_648
CARD_649
CARD_650
CARD_651
CARD_652
CARD_653
CARD_654
CARD_655
CARD_656
CARD_657
CARD_658
CARD_659
CARD_660
CARD_661
CARD_662
CARD_663
CARD_664
CARD_665
CARD_666
CARD_667
CARD_668
CARD_669
CARD_670
CARD_671
CARD_672
CARD_673
CARD_674
CARD_675
CARD_676
CARD_677
CARD_678
CARD_679
CARD_680
CARD_681
CARD_682
CARD_683
CARD_684
CARD_685
CARD_686
CARD_687
CARD_688
CARD_689
CARD_690
CARD_691
CARD_692
CARD_693
CARD_694
CARD_695
CARD_696
CARD_697
CARD_698
CARD_699
CARD_700
CARD_701
CARD_702
CARD_703
CARD_704
CARD_705
CARD_706
CARD_707
CARD_708
CARD_709
CARD_710
CARD_711
CARD_712
CARD_713
CARD_714
CARD_715
CARD_716
CARD_717
CARD_718
CARD_719
CARD_720
CARD_721
CARD_722
CARD_723
CARD_724
CARD_725
CARD_726
CARD_727
CARD_728
CARD_729
CARD_730
CARD_731
CARD_732
CARD_733
CARD_734
CARD_735
CARD_736
CARD_737
CARD_738
CARD_739
CARD_740
CARD_741
CARD_742
CARD_743
CARD_744
CARD_745
CARD_746
CARD_747
CARD_748
CARD_749
CARD_750
CARD_751
CARD_752
CARD_753
CARD_754
CARD_755
CARD_756
CARD_757
CARD_758
CARD_759
CARD_760
CARD_761
CARD_762
CARD_763
CARD_764
CARD_765
CARD_766
CARD_767
CARD_768
CARD_769
CARD_770
CARD_771
CARD_772
CARD_773
CARD_774
CARD_775
CARD_776
CARD_777
CARD_778
CARD_779
CARD_780
CARD_781
CARD_782
CARD_783
CARD_784
CARD_785
CARD_786
CARD_787
CARD_788
CARD_789
CARD_790
CARD_791
CARD_792
CARD_793
CARD_794
CARD_795
CARD_796
CARD_797
CARD_798
CARD_799
CARD_800
CARD_801
CARD_802
CARD_803
CARD_804
CARD_805
CARD_806
CARD_807
CARD_808
CARD_809
CARD_810
CARD_811
CARD_812
CARD_813
CARD_814
CARD_815
CARD_816
CARD_817
CARD_818
CARD_819
CARD_820
CARD_821
CARD_822
CARD_823
CARD_824
CARD_825
CARD_826
CARD_827
CARD_828
CARD_829
CARD_830
CARD_831
CARD_832
CARD_833
CARD_834
CARD_835
CARD_836
CARD_837
CARD_838
CARD_839
CARD_840
CARD_841
CARD_842
CARD_843
CARD_844
CARD_845
CARD_846
CARD_847
CARD_848
CARD_849
CARD_850
CARD_851
CARD_852
CARD_853
CARD_854
CARD_855
CARD_856
CARD_857
CARD_858
CARD_859
CARD_860
CARD_861
CARD_862
CARD_863
CARD_864
CARD_865
CARD_866
CARD_867
CARD_868
CARD_869
CARD_870
CARD_871
CARD_872
CARD_873
CARD_874
CARD_875
CARD_876
CARD_877
CARD_878
CARD_879
CARD_880
CARD_881
CARD_882
CARD_883
CARD_884
CARD_885
CARD_886
CARD_887
CARD_888
CARD_889
CARD_890
CARD_891
CARD_892
CARD_893
CARD_894
CARD_895
CARD_896
CARD_897
CARD_898
CARD_899
CARD_900
CARD_901
CARD_902
CARD_903
CARD_904
CARD_905
CARD_906
CARD_907
CARD_908
CARD_909
CARD_910
CARD_911
CARD_912
CARD_913
CARD_914
CARD_915
CARD_916
CARD_917
CARD_918
CARD_919
CARD_920
CARD_921
CARD_922
CARD_923
CARD_924
CARD_925
CARD_926
CARD_927
CARD_928
CARD_929
CARD_930
CARD_931
CARD_932
CARD_933
CARD_934
CARD_935
CARD_936
CARD_937
CARD_938
CARD_939
CARD_940
CARD_941
CARD_942
CARD_943
CARD_944
CARD_945
CARD_946
CARD_947
CARD_948
CARD_949
CARD_950
CARD_951
CARD_952
CARD_953
CARD_954
CARD_955
CARD_956
CARD_957
CARD_958
CARD_959
CARD_960
CARD_961
CARD_962
CARD_963
CARD_964
CARD_965
CARD_966
CARD_967
CARD_968
CARD_969
CARD_970
CARD_971
CARD_972
CARD_973
CARD_974
CARD_975
CARD_976
CARD_977
CARD_978
CARD_979
CARD_980
CARD_981
CARD_982
CARD_983
CARD_984
CARD_985
CARD_986
CARD_987
CARD_988
CARD_989
CARD_990
CARD_991
CARD_992
CARD_993
CARD_994
CARD_995
CARD_996
CARD_997
CARD_998
CARD_999
CARD_1000
CARD_1001
CARD_1002
CARD_1003
CARD_1004
CARD_1005
CARD_1006
CARD_1007
CARD_1008
CARD_1009
CARD_1010
CARD_1011
CARD_1012
CARD_1013
CARD_1014
CARD_1015
CARD_1016
CARD_1017
CARD_1018
CARD_1019
CARD_1020
CARD_1021
CARD_1022
CARD_1023
CARD_1024
CARD_1025
CARD_1026
CARD_1027
CARD_1028
CARD_1029
CARD_1030
CARD_1031
CARD_1032
CARD_1033
CARD_1034
CARD_1035
CARD_1036
CARD_1037
CARD_1038
CARD_1039
CARD_1040
CARD_1041
CARD_1042
CARD_1043
CARD_1044
CARD_1045
CARD_1046
CARD_1047
CARD_1048
CARD_1049
CARD_1050
CARD_1051
CARD_1052
CARD_1053
CARD_1054
CARD_1055
CARD_1056
CARD_1057
CARD_1058
CARD_1059
CARD_1060
CARD_1061
CARD_1062
CARD_1063
CARD_1064
CARD_1065
CARD_1066
CARD_1067
CARD_1068
CARD_1069
CARD_1070
CARD_1071
CARD_1072
CARD_1073
CARD_1074
CARD_1075
CARD_1076
CARD_1077
CARD_1078
CARD_1079
CARD_1080
CARD_1081
CARD_1082
CARD_1083
CARD_1084
CARD_1085
CARD_1086
CARD_1087
CARD_1088
CARD_1089
CARD_1090
CARD_1091
CARD_1092
CARD_1093
CARD_1094
CARD_1095
CARD_1096
CARD_1097
CARD_1098
CARD_1099
CARD_1100
CARD_1101
CARD_1102
CARD_1103
CARD_1104
CARD_1105
CARD_1106
CARD_1107
CARD_1108
CARD_1109
CARD_1110
CARD_1111
CARD_1112
CARD_1113
CARD_1114
CARD_1115
CARD_1116
CARD_1117
CARD_1118
CARD_1119
CARD_1120
CARD_1121
CARD_1122
CARD_1123
CARD_1124
CARD_1125
CARD_1126
CARD_1127
CARD_1128
CARD_1129
CARD_1130
CARD_1131
CARD_1132
CARD_1133
CARD_1134
CARD_1135
CARD_1136
CARD_1137
CARD_1138
CARD_1139
CARD_1140
CARD_1141
CARD_1142
CARD_1143
CARD_1144
CARD_1145
CARD_1146
CARD_1147
CARD_1148
CARD_1149
CARD_1150
CARD_1151
CARD_1152
CARD_1153
CARD_1154
CARD_1155
CARD_1156
CARD_1157
CARD_1158
CARD_1159
CARD_1160
CARD_1161
CARD_1162
CARD_1163
CARD_1164
CARD_1165
CARD_1166
CARD_1167
CARD_1168
CARD_1169
CARD_1170
CARD_1171
CARD_1172
CARD_1173
CARD_1174
CARD_1175
CARD_1176
CARD_1177
CARD_1178
CARD_1179
CARD_1180
CARD_1181
CARD_1182
CARD_1183
CARD_1184
CARD_1185
CARD_1186
CARD_1187
CARD_1188
CARD_1189
CARD_1190
CARD_1191
CARD_1192
CARD_1193
CARD_1194
CARD_1195
CARD_1196
CARD_1197
CARD_1198
CARD_1199
CARD_1200
CARD_1201
CARD_1202
CARD_1203
CARD_1204
CARD_1205
CARD_1206
CARD_1207
CARD_1208
CARD_1209
CARD_1210
CARD_1211
CARD_1212
CARD_1213
CARD_1214
CARD_1215
CARD_1216
CARD_1217
CARD_1218
CARD_1219
CARD_1220
CARD_1221
CARD_1222
CARD_1223
CARD_1224
CARD_1225
CARD_1226
CARD_1227
CARD_1228
CARD_1229
CARD_1230
CARD_1231
CARD_1232
CARD_1233
CARD_1234
CARD_1235
CARD_1236
CARD_1237
CARD_1238
CARD_1239
CARD_1240
CARD_1241
CARD_1242
CARD_1243
CARD_1244
CARD_1245
CARD_1246
CARD_1247
CARD_1248
CARD_1249
CARD_1250
CARD_1251
CARD_1252
CARD_1253
CARD_1254
CARD_1255
CARD_1256
CARD_1257
CARD_1258
CARD_1259
CARD_1260
CARD_1261
CARD_1262
CARD_1263
CARD_1264
CARD_1265
CARD_1266
CARD_1267
CARD_1268
CARD_1269
CARD_1270
CARD_1271
CARD_1272
CARD_1273
CARD_1274
CARD_1275
CARD_1276
CARD_1277
CARD_1278
CARD_1279
CARD_1280
CARD_1281
CARD_1282
CARD_1283
CARD_1284
CARD_1285
CARD_1286
CARD_1287
CARD_1288
CARD_1289
CARD_1290
CARD_1291
CARD_1292
CARD_1293
CARD_1294
CARD_1295
CARD_1296
CARD_1297
CARD_1298
CARD_1299
CARD_1300
CARD_1301
CARD_1302
CARD_1303
CARD_1304
CARD_1305
CARD_1306
CARD_1307
CARD_1308
CARD_1309
CARD_1310
CARD_1311
CARD_1312
CARD_1313
CARD_1314
CARD_1315
CARD_1316
CARD_1317
CARD_1318
CARD_1319
CARD_1320
CARD_1321
CARD_1322
CARD_1323
CARD_1324
CARD_1325
CARD_1326
CARD_1327
CARD_1328
CARD_1329
CARD_1330
CARD_1331
CARD_1332
CARD_1333
CARD_1334
CARD_1335
CARD_1336
CARD_1337
CARD_1338
CARD_1339
CARD_1340
CARD_1341
CARD_1342
CARD_1343
CARD_1344
CARD_1345
CARD_1346
CARD_1347
CARD_1348
CARD_1349
CARD_1350
CARD_1351
CARD_1352
CARD_1353
CARD_1354
CARD_1355
CARD_1356
CARD_1357
CARD_1358
CARD_1359
CARD_1360
CARD_1361
CARD_1362
CARD_1363
CARD_1364
CARD_1365
CARD_1366
CARD_1367
CARD_1368
CARD_1369
CARD_1370
CARD_1371
CARD_1372
CARD_1373
CARD_1374
CARD_1375
CARD_1376
CARD_1377
CARD_1378
CARD_1379
CARD_1380
CARD_1381
CARD_1382
CARD_1383
CARD_1384
CARD_1385
CARD_1386
CARD_1387
CARD_1388
CARD_1389
CARD_1390
CARD_1391
CARD_1392
CARD_1393
CARD_1394
CARD_1395
CARD_1396
CARD_1397
CARD_1398
CARD_1399
CARD_1400
CARD_1401
CARD_1402
CARD_1403
CARD_1404
CARD_1405
CARD_1406
CARD_1407
CARD_1408
CARD_1409
CARD_1410
CARD_1411
CARD_1412
CARD_1413
CARD_1414
CARD_1415
CARD_1416
CARD_1417
CARD_1418
CARD_1419
CARD_1420
CARD_1421
CARD_1422
CARD_1423
CARD_1424
CARD_1425
CARD_1426
CARD_1427
CARD_1428
CARD_1429
CARD_1430
CARD_1431
CARD_1432
CARD_1433
CARD_1434
CARD_1435
CARD_1436
CARD_1437
CARD_1438
CARD_1439
CARD_1440
CARD_1441
CARD_1442
CARD_1443
CARD_1444
CARD_1445
CARD_1446
CARD_1447
CARD_1448
CARD_1449
CARD_1450
CARD_1451
CARD_1452
CARD_1453
CARD_1454
CARD_1455
CARD_1456
CARD_1457
CARD_1458
CARD_1459
CARD_1460
CARD_1461
CARD_1462
CARD_1463
CARD_1464
CARD_1465
CARD_1466
CARD_1467
CARD_1468
CARD_1469
CARD_1470
CARD_1471
CARD_1472
CARD_1473
CARD_1474
CARD_1475
CARD_1476
CARD_1477
CARD_1478
CARD_1479
CARD_1480
CARD_1481
CARD_1482
CARD_1483
CARD_1484
CARD_1485
CARD_1486
CARD_1487
CARD_1488
CARD_1489
CARD_1490
CARD_1491
CARD_1492
CARD_1493
CARD_1494
CARD_1495
CARD_1496
CARD_1497
CARD_1498
CARD_1499
CARD_1500
CARD_1501
CARD_1502
CARD_1503
CARD_1504
CARD_1505
CARD_1506
CARD_1507
CARD_1508
CARD_1509
CARD_1510
CARD_1511
CARD_1512
CARD_1513
CARD_1514
CARD_1515
CARD_1516
CARD_1517
CARD_1518
CARD_1519
CARD_1520
CARD_1521
CARD_1522
CARD_1523
CARD_1524
CARD_1525
CARD_1526
CARD_1527
CARD_1528
CARD_1529
CARD_1530
CARD_1531
CARD_1532
CARD_1533
CARD_1534
CARD_1535
CARD_1536
CARD_1537
CARD_1538
CARD_1539
CARD_1540
CARD_1541
CARD_1542
CARD_1543
CARD_1544
CARD_1545
CARD_1546
CARD_1547
CARD_1548
CARD_1549
CARD_1550
CARD_1551
CARD_1552
CARD_1553
CARD_1554
CARD_1555
CARD_1556
CARD_1557
CARD_1558
CARD_1559
CARD_1560
CARD_1561
CARD_1562
CARD_1563
CARD_1564
CARD_1565
CARD_1566
CARD_1567
CARD_1568
CARD_1569
CARD_1570
CARD_1571
CARD_1572
CARD_1573
CARD_1574
CARD_1575
CARD_1576
CARD_1577
CARD_1578
CARD_1579
CARD_1580
CARD_1581
CARD_1582
CARD_1583
CARD_1584
CARD_1585
CARD_1586
CARD_1587
CARD_1588
CARD_1589
CARD_1590
CARD_1591
CARD_1592
CARD_1593
CARD_1594
CARD_1595
CARD_1596
CARD_1597
CARD_1598
CARD_1599
CARD_1600
CARD_1601
CARD_1602
CARD_1603
CARD_1604
CARD_1605
CARD_1606
CARD_1607
CARD_1608
CARD_1609
CARD_1610
CARD_1611
CARD_1612
CARD_1613
CARD_1614
CARD_1615
CARD_1616
CARD_1617
CARD_1618
CARD_1619
CARD_1620
CARD_1621
CARD_1622
CARD_1623
CARD_1624
CARD_1625
CARD_1626
CARD_1627
CARD_1628
CARD_1629
CARD_1630
CARD_1631
CARD_1632
CARD_1633
CARD_1634
CARD_1635
CARD_1636
CARD_1637
CARD_1638
CARD_1639
CARD_1640
CARD_1641
CARD_1642
CARD_1643
CARD_1644
CARD_1645
CARD_1646
CARD_1647
CARD_1648
CARD_1649
CARD_1650
CARD_1651
CARD_1652
CARD_1653
CARD_1654
CARD_1655
CARD_1656
CARD_1657
CARD_1658
CARD_1659
CARD_1660
CARD_1661
CARD_1662
CARD_1663
CARD_1664
CARD_1665
CARD_1666
CARD_1667
CARD_1668
CARD_1669
CARD_1670
CARD_1671
CARD_1672
CARD_1673
CARD_1674
CARD_1675
CARD_1676
CARD_1677
CARD_1678
CARD_1679
CARD_1680
CARD_1681
CARD_1682
CARD_1683
CARD_1684
CARD_1685
CARD_1686
CARD_1687
CARD_1688
CARD_1689
CARD_1690
CARD_1691
CARD_1692
CARD_1693
CARD_1694
CARD_1695
CARD_1696
CARD_1697
CARD_1698
CARD_1699
CARD_1700
CARD_1701
CARD_1702
CARD_1703
CARD_1704
CARD_1705
CARD_1706
CARD_1707
CARD_1708
CARD_1709
CARD_1710
CARD_1711
CARD_1712
CARD_1713
CARD_1714
CARD_1715
CARD_1716
CARD_1717
CARD_1718
CARD_1719
CARD_1720
CARD_1721
CARD_1722
CARD_1723
CARD_1724
CARD_1725
CARD_1726
CARD_1727
CARD_1728
CARD_1729
CARD_1730
CARD_1731
CARD_1732
CARD_1733
CARD_1734
CARD_1735
CARD_1736
CARD_1737
CARD_1738
CARD_1739
CARD_1740
CARD_1741
CARD_1742
CARD_1743
CARD_1744
CARD_1745
CARD_1746
CARD_1747
CARD_1748
CARD_1749
CARD_1750
CARD_1751
CARD_1752
CARD_1753
CARD_1754
CARD_1755
CARD_1756
CARD_1757
CARD_1758
CARD_1759
CARD_1760
CARD_1761
CARD_1762
CARD_1763
CARD_1764
CARD_1765
CARD_1766
CARD_1767
CARD_1768
CARD_1769
CARD_1770
CARD_1771
CARD_1772
CARD_1773
CARD_1774
CARD_1775
CARD_1776
CARD_1777
CARD_1778
CARD_1779
CARD_1780
CARD_1781
CARD_1782
CARD_1783
CARD_1784
CARD_1785
CARD_1786
CARD_1787
CARD_1788
CARD_1789
CARD_1790
CARD_1791
CARD_1792
CARD_1793
CARD_1794
CARD_1795
CARD_1796
CARD_1797
CARD_1798
CARD_1799
CARD_1800
CARD_1801
CARD_1802
CARD_1803
CARD_1804
CARD_1805
CARD_1806
CARD_1807
CARD_1808
CARD_1809
CARD_1810
CARD_1811
CARD_1812
CARD_1813
CARD_1814
CARD_1815
CARD_1816
CARD_1817
CARD_1818
CARD_1819
CARD_1820
CARD_1821
CARD_1822
CARD_1823
CARD_1824
CARD_1825
CARD_1826
CARD_1827
CARD_1828
CARD_1829
CARD_1830
CARD_1831
CARD_1832
CARD_1833
CARD_1834
CARD_1835
CARD_1836
CARD_1837
CARD_1838
CARD_1839
CARD_1840
CARD_1841
CARD_1842
CARD_1843
CARD_1844
CARD_1845
CARD_1846
CARD_1847
CARD_1848
CARD_1849
CARD_1850
CARD_1851
CARD_1852
CARD_1853
CARD_1854
CARD_1855
CARD_1856
CARD_1857
CARD_1858
CARD_1859
CARD_1860
CARD_1861
CARD_1862
CARD_1863
CARD_1864
CARD_1865
CARD_1866
CARD_1867
CARD_1868
CARD_1869
CARD_1870
CARD_1871
CARD_1872
CARD_1873
CARD_1874
CARD_1875
CARD_1876
CARD_1877
CARD_1878
CARD_1879
CARD_1880
CARD_1881
CARD_1882
CARD_1883
CARD_1884
CARD_1885
CARD_1886
CARD_1887
CARD_1888
CARD_1889
CARD_1890
CARD_1891
CARD_1892
CARD_1893
CARD_1894
CARD_1895
CARD_1896
CARD_1897
CARD_1898
CARD_1899
CARD_1900
CARD_1901
CARD_1902
CARD_1903
CARD_1904
CARD_1905
CARD_1906
CARD_1907
CARD_1908
CARD_1909
CARD_1910
CARD_1911
CARD_1912
CARD_1913
CARD_1914
CARD_1915
CARD_1916
CARD_1917
CARD_1918
CARD_1919
CARD_1920
CARD_1921
CARD_1922
CARD_1923
CARD_1924
CARD_1925
CARD_1926
CARD_1927
CARD_1928
CARD_1929
CARD_1930
CARD_1931
CARD_1932
CARD_1933
CARD_1934
CARD_1935
CARD_1936
CARD_1937
CARD_1938
CARD_1939
CARD_1940
CARD_1941
CARD_1942
CARD_1943
CARD_1944
CARD_1945
CARD_1946
CARD_1947
CARD_1948
CARD_1949
CARD_1950
CARD_1951
CARD_1952
CARD_1953
CARD_1954
CARD_1955
CARD_1956
CARD_1957
CARD_1958
CARD_1959
CARD_1960
CARD_1961
CARD_1962
CARD_1963
CARD_1964
CARD_1965
CARD_1966
CARD_1967
CARD_1968
CARD_1969
CARD_1970
CARD_1971
CARD_1972
CARD_1973
CARD_1974
CARD_1975
CARD_1976
CARD_1977
CARD_1978
CARD_1979
CARD_1980
CARD_1981
CARD_1982
CARD_1983
CARD_1984
CARD_1985
CARD_1986
CARD_1987
CARD_1988
CARD_1989
CARD_1990
CARD_1991
CARD_1992
CARD_1993
CARD_1994
CARD_1995
CARD_1996
CARD_1997
CARD_1998
CARD_1999
CARD_2000
CARD_2001
CARD_2002
CARD_2003
CARD_2004
CARD_2005
CARD_2006
CARD_2007
CARD_2008
CARD_2009
CARD_2010
CARD_2011
CARD_2012
CARD_2013
CARD_2014
CARD_2015
CARD_2016
CARD_2017
CARD_2018
CARD_2019
CARD_2020
CARD_2021
CARD_2022
CARD_2023
CARD_2024
CARD_2025
CARD_2026
CARD_2027
CARD_2028
CARD_2029
CARD_2030
CARD_2031
CARD_2032
CARD_2033
CARD_2034
CARD_2035
CARD_2036
CARD_2037
CARD_2038
CARD_2039
CARD_2040
CARD_2041
CARD_2042
CARD_2043
CARD_2044
CARD_2045
CARD_2046
CARD_2047
CARD_2048
CARD_2049
CARD_2050
CARD_2051
CARD_2052
CARD_2053
CARD_2054
CARD_2055
CARD_2056
CARD_2057
CARD_2058
CARD_2059
CARD_2060
CARD_2061
CARD_2062
CARD_2063
CARD_2064
CARD_2065
CARD_2066
CARD_2067
CARD_2068
CARD_2069
CARD_2070
CARD_2071
CARD_2072
CARD_2073
CARD_2074
CARD_2075
CARD_2076
CARD_2077
CARD_2078
CARD_2079
CARD_2080
CARD_2081
CARD_2082
CARD_2083
CARD_2084
CARD_2085
CARD_2086
CARD_2087
CARD_2088
CARD_2089
CARD_2090
CARD_2091
CARD_2092
CARD_2093
CARD_2094
CARD_2095
CARD_2096
CARD_2097
CARD_2098
CARD_2099
CARD_2100
CARD_2101
CARD_2102
CARD_2103
CARD_2104
CARD_2105
CARD_2106
CARD_2107
CARD_2108
CARD_2109
CARD_2110

In [47]:
MetaDict

{'CARD_0': {'Drug Class': 'beta-lactam',
  'Name': 'CblA-1',
  'Sequence': 'MKAYFIAILTLFTCIATVVRAQQMSELENRIDSLLNGKKATVGIAVWTDKGDMLRYNDHVHFPLLSVFKFHVALAVLDKMDKQSISLDSIVSIKASQMPPNTYSPLRKKFPDQDFTITLRELMQYSISQSDNNACDILIEYAGGIKHINDYIHRLSIDSFNLSETEDGMHSSFEAVYRNWSTPSAMVRLLRTADEKELFSNKELKDFLWQTMIDTETGANKLKGMLPAKTVVGHKTGSSDRNADGMKTADNDAGLVILPDGRKYYIAAFVMDSYETDEDNANIIARISRMVYDAMR'},
 'CARD_1': {'Drug Class': 'beta-lactam',
  'Name': 'SHV-52',
  'Sequence': 'MRYIRLCIISLLAALPLAVHASPQPLEQIKQSESQLSGRVGMIEMDLASGRTLTAWRADERFPMISTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLAIVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARDTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR'},
 'CARD_2': {'Drug Class': 'diaminopyrimidine',
  'Name': 'dfrF',
  'Sequence': 'MIGLIVARSKNNVIGKNGNIPWKIKGEQKQFRELTTGNVVIMGRKSYEEIGHPLPNRMNIVVSTTTEYQGDNLVSVKSLEDALLLAKGRDVYISGGYGLFKEALQIVDKMYITEVDLNIEDGDTFFPEFDINDFEVLIGETLGEEVKYTRTFYVRKNELSRFWI'},
 'CARD_3': {'Drug Class': 'beta-lactam',
  'Name': 'CTX-M-130',
  'Sequence': 'MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDERFPMCSTSKVMAAAAVLKQSETQKQLLNQPVEIKPADLVNYNPIAEKHVNGTMTLAELSAAALQYSDNTAMNKLIAQLGGPGGVTAFARAIGDETFRLDRTEPTLNTAIPGDPRDTTTPRAMAQTLRQLTLGHALGETQRAQLVTWLKGNTTGAASIRAGLPTSWTVGDKTGSGDYGTTNDIAVIWPQGRAPLVLVTYFTQPQQNAERRHDVLASAARIIAEGL'},
 'CARD_4': {'Drug Class': 'beta-lactam',
  'Name': 'NDM-6',
  'Sequence': 'MELPNIMHPVAKLSTALAAALMLSGCMPGEIRPTIGQQMETGDQRFGDLVFRQLAPNVWQHTSYLDMPGFGAVASNGLIVRDGGRVLVVDTAWTDDQTAQILNWIKQEINLPVALAVVTHAHQDKMGGMDALHAAGIATYANALSNQLAPQEGMVAAQHSLTFAANGWVEPATAPNFGPLKVFYPGPGHTSDNITVGIDGTDIAFGGCLIKDSKAKSLGNLGDADTEHYAASVRAFGAAFPKASMIVMSHSAPDSRAAITHTARMADKLR'},
 'CARD_5': {'Drug Class': 'beta-lactam',
  'Name': 'ACT-35',
  'Sequence': 'MMKKSLCCALLLGISCSALATPVSEKQLAEVVANTVTPLMKAQSVPGMAVAVIYQGKPHYYTFGKADIAANKPVTPQTLFELGSISKTFTGVLGGDAIARGEISLDDPVTRYWPQLTGKQWQGIRMLDLATYTAGGLPLQVPDEVTDNASLLRFYQNWQPQWKPGTTRLYANASIGLFGALAVKPSGMPYEQAMTTRVLKPLKLDHTWINVPKAEEAHYAWGYRDGKAVRVSPGMLDAQAYGVKTNVQDMANWVMANMAPENVADASLKQGIALAQSRYWRIGSMYQGLGWEMLNWPVEANTVVEGSDSKVALAPLPVVEVNPPAPPVKASWVHKTGSTGGFGSYVAFIPEKQIGIVMLANTSYPNPARVEAAYYILEALQ'},
 'CARD_6': {'Drug Class': 'beta-lactam',
  'Name': 'CARB-5',
  'Sequence': 'MNVRKHKASFFSVVITFLCLTLSLNANATDSVLEAVTNAETELGARIGLAVHDLETGKRWEHKSNERFPLSSTFKTLACANVLQRVDLGKERIDRVVRFSESNLVTYSPVTEKHVGKKGMSLAELCQATLSTSDNSAANFILQAIGGPKALTKFLRSIGDDTTRLDRWETELNEAVPGDKRDTTTPIAMVTTLEKLLIDETLSIKSRQQLESWLKGNEVGDALFRKGVPSDWIVADRTGAGGYGSRAITAVMWPPNRKPIVAALYITETDASFEERNAVIAKIGEQIAKTVLMENSRN'},
 'CARD_7': {'Drug Class': 'MLS',
  'Name': 'Erm(34)',
  'Sequence': 'MTKKMNKYNGKKLSRGEPPNFSGQHFMHNKRLLKEIVDKADVSVRDTVLELGAGKGALTTILSERADRVLAVEYDQKCIEALQWKLVGSKNVSILHQDIMKVALPTEPFVVVSNIPYSITTAIMKMLLNNPKNKLQRGAIVMEKGAAKRFTSVSPKDAYVMAWHMWFDIHYERGISRSSFSPPPKVDSALVRIVRKQHPLFPYKEAKAMHDFLSYALNNPRAPLDQVLRGIFTAPQAKKVRQAIGVKPETPVAMLHARQWAMVCDAMVRHVPKVYWPRRKR'},
 'CARD_8': {'Drug Class': 'beta-lactam',
  'Name': 'TEM-126',
  'Sequence': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERETTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW'},
 'CARD_9': {'Drug Class': 'beta-lactam',
  'Name': 'LRA-12',
  'Sequence': 'MNVQNCMVKAVSVSIILFASLSLAAQKVKEPTVSNADWSKPYRPFRIAGNLYYIGTYDLACYLITTKQGNIIVNTGLAASALQIKNNIKALGFKLTDTKILLTTQAHYDHLGAMAEIKKITGAKLMADEGDATVMADGGSSDYAFGGHGSMFEPIIADRLLHDKDTIQLGDTKLVMLHHPGHTKGSCSFLFDTKDEQRSYRILIANMPTIVIEKKFSEVSSYPGIAKDYAYTLQAMKNLSFDIWVASHASQFSMHSKHKPGDGYNPKSFMDRKGYDESLDKLQKEYEKHLNEN'},
 'CARD_10': {'Drug Class': 'beta-lactam',
  'Name': 'TEM-72',
  'Sequence': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGASKRGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW'},
 'CARD_11': {'Drug Class': 'beta-lactam',
  'Name': 'TEM-59',
  'Sequence': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMGDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAE'},
 'CARD_12': {'Drug Class': 'beta-lactam',
  'Name': 'KPC-10',
  'Sequence': 'MSLYRRLVLLSCLSWPLAGFSATALTNLVAEPFAKLEQDFGGSIGVYAMDTGSGATVSYRAEERFPLCSSFKGFLAAAVLARSQQQAGLLDTPIRYGKNALVRWSPISEKYLTTGMTVAELSAAAVQYSDNAAANLLLKELGGPAGLTAFMRSIGDTTFRLDRWELELNSAIPGDARDTSSPRAVTESLQKLTLGSALAAPQRQQFVDWLKGNTTGNHRIRAAVPADWAVGDKTGTCGVYGTANDYAVVWPTGRAPIVLAVYTRAPNKDDKYSEAVIAAAARLALEGLGVNGQ'},
 'CARD_13': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-212',
  'Sequence': 'MKTLQSGLIALITTFGSACTTISPSVETAKNQQQQSAQQQIQQAFDQLQTTGVIVVKDKHSLHSYGNDLSRAQTPYIPASTFKMLNALIGLEHGKATSTEVFKWDGQKRSFPTWEKDMTLGQAMQASAVPVYQELARRIGLDLMKKEVQRIGYGNQQIGTVVDNFWLVGPLQITPVQEVLFVEKLANTQLAFKPDVQHAVQDMLLIEQKPNYKLYAKSGWGMDLEPQVGWWAGWVETSTGEKVYFALNMHMKTGISASVREQLVKQSLTALGII'},
 'CARD_14': {'Drug Class': 'beta-lactam',
  'Name': 'IMP-2',
  'Sequence': 'MKKLFVLCVCFLCSITAAGARLPDLKIEKLEEGVYVHTSFEEVNGWGVVSKHGLVVLVNTDAYLIDTPFTATDTEKLVNWFVERGYKIKGTISSHFHSDSTGGIEWLNSQSIPTYASELTNELLKKDGKVQAKNSFSGVSYWLVKNKIEVFYPGPGHTQDNVVVWLPEKKILFGGCFVKPDGLGNLGDANLEAWPKSAKILMSKYVKAKLVVSSHSEIGDASLLKRTWEQAVKGLNESKKPSQPSN'},
 'CARD_15': {'Drug Class': 'beta-lactam',
  'Name': 'CMY-1',
  'Sequence': 'MQQRQSILWGAVATLMWAGLAHAGEASPVDPLRPVVDASIQPLLKEHRIPGMAVAVLKDGKAHYFNYGVANRESGAGVSEQTLFEIGSVSKTLTATLGAYAVVKGAMQLDDKASRHAPWLKGSAFDSITMGELATYSAGGLPLQFPEEVDSSEKMRAYYRQWAPVYSPGSHRQYSNPSIGLFGHLAASSLKQPFAPLMEQTLLPGLGMHHTYVNVPKQAMASYAYGYSKEDKPIRVNPGMLADEAYGIKTSSADLLRFVKANIGGVDDKALQQAISLTHQGHYSVGGMTQGLGWESYAYPVTEQTLLAGNSAKVILEANPTAAPRESGSQVLFNKTGSTNGFGAYVAFVPARGIGIVMLANRNYPNEARIKAAHAILAQLAG'},
 'CARD_16': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-329',
  'Sequence': 'MYKKALIVATSILFLSACSSNTVKQHQIHSISANKNSEAIKSLFDQAQTTGVLVIKRGQTEEIYGNDLKRASTAYVPASTFKMLNALIGLEHHKAITTEVFKWDGQKRLFPDWEKDMTLGDAMKASAIPVYQELARRIGLDLMSKEVKRIGFGNANIGSKVDDFWLVGPLKITPQQETQFAYQLAHKMLPFSKDVQEQVQSMVFIEEKNGRKIYAKSGWGWDIEPQVGWLTGWVVQPQGEIVAFSLNLEMKKGTPSSIRKEIAYKGLEQLGIL'},
 'CARD_17': {'Drug Class': 'beta-lactam',
  'Name': 'ACT-10',
  'Sequence': 'MMKKSVCCALLLSTSCSVLAAPMSEKQLAEVVERTVTPLMKAQAIPGIAVAVIYQGQPHYFTFGKADVAANKPVTPQTLFELGSISKTFTGVLGGDAIARGEISLGDPVTKYWPELTGKQWKGIRMLDLATYTAGGLPLQVPDEVTDNASLLRFYQNWQPQWKPGTTRLYANASIGLFGALAVKPSGMSYEQAITTRVFKPLKLDHTWINVPKTEEAHYAWGYRDGKAVHVSPGMLDAEAYGVKTNVKDMASWVMVNMKPDSLEDSSLRKGFTLAQSRYWRVGAMYQGLGWEMLNWPVDAKTVVEGSDNKVALAPLPAREVNPPAPPVNASWVHKTGSTGGFGSYVAFIPEKQLGIVMLANKSYPNPARVEAAYRILDALQ'},
 'CARD_18': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-371',
  'Sequence': 'MNIKALLLITSAIFISACSPYIVTANPNHSASKSDDKAEKIKNLFNEAHTTGVLVIHQGQTQQSYGNDLARASTEYVPASTFKMLNALIGLEHHKATTTEVFKWDGEKRLFPEWEKNMTLGDAMKASAIPVYQDLARRIGLELMSKEVKRVGYGNADIGTQVDNFWLVGPLKITPQQEAQFAYKLANKTLPFSQKVQDEVQSMLFIEEKNGNKIYAKSGWGWDVNPQVGWLTGWVVKPQGNIVAFSLNLEMKKGIPSSVRKEITYKSLEQLGIL'},
 'CARD_19': {'Drug Class': 'fusidane',
  'Name': 'fusB',
  'Sequence': 'MKTMIYPHQYNYIRSVILRLKNVYKTVNDKETVKVIQSETYNDINEIFGHIDDDIEESLKVLMNIRLSNKEIEAILNKFLEYVVPFELPSPQKLQKVFKKVKKIKIPQFEEYDLKVSSFVGWNELASNRKYIIYYDEKKQLKGLYGEISNQVVKGFCTICNKESNVSLFMKKSKTNSDGQYVKKGDYICRDSIHCNKQLTDINQFYNFIDKLD'},
 'CARD_20': {'Drug Class': 'beta-lactam',
  'Name': 'CTX-M-121',
  'Sequence': 'MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDERFPMCSTSKVMAAAAVLKQSETQKQLLNQPVEIKPADLVNYNPITEKHVNGTMTLAELSAAALQYSDNTAMNKLIAQLGGPGGVTAFARAIGDETFRLDRTEPTLNTAIPGDPRDTTTPRAMAQTLRQLTLGHALGETQRAQLVTWLKGNTTGAASIRAGLPTSWTVGDKTGSGGYGTTNDIAVIWPQGRAPLVLVTYFTQPQQNAESRRDVLASAARIIAEGL'},
 'CARD_21': {'Drug Class': 'beta-lactam',
  'Name': 'VEB-3',
  'Sequence': 'MKIVKRILLVLLSLFFTVVYSNAQTDNLTLKIENVLKAKNARIGVAIFNSNEKDTFKINNDFHFPMQSVMKFPIALAVLSEIDKGNLSFEQKIEITPQDLLPKTWSPIKEEFPNGTTLTIEQILNYTVSESDNIGCDILLKLIGGTDSVQKFLNANHFTDISIKANEEQMHKDWNTQYQNWATPTAMNKLLIDTYNNKNQLLSKKSYDFIWKIMRETTTGSNRLKGQLPKNTIVAHKTGTSGINNGIAAATNDVGVITLPNGQLIFISVFVAESKETSEINEKIISDIAKITWNYYLNK'},
 'CARD_22': {'Drug Class': 'lincosamide',
  'Name': 'lnuA',
  'Sequence': 'MKNNNVTEKELFYILDLFEHMKVTYWLDGGWGVDVLTGKQQREHRDIDIDFDAQHTQKVIQKLEDIGYKIEVHWMPSRMELKHEEYGYLDIHPINLNDDGSITQANPEGGNYVFQNDWFSETNYKDRKIPCISKEAQLLFHSGYDLTETDHFDIKNLKSIT'},
 'CARD_23': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-45',
  'Sequence': 'MRGKHTVILGAALSALFAGAAGAQMLECTLVADAASGQELYRKGACDKAFAPMSTFKVPLAVMGYDAGILVDAHNPRWDYKPEFNGYKFQQKTTDPTIWEKDSIVWYSQQLTRKMGQKRFAAYVAGFGYGNGDISGEPGKSNGLTHSWLGSSLKISPEGQVRFVRDLLSAKLPASKDAQQMTVSILPHFAAGDWAVQGKTGTGSFIDARGAKAPLGWFIGWATHEERRVVFARMTAGGKKGEQPAGPAARDAFLKALPDLAKRF'},
 'CARD_24': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-226',
  'Sequence': 'MAIRIFAILFSIFSLATFAHAQEGTLERSDWRKFFSEFQAKGTIVVADERQADRAMLVFDPVRSKKRYSPASTFKIPHTLFALDAGAVRDEFQIFRWDGVNRGFAGHNQDQDLRSAMRNSTVWVYELFAKEIGDDKARRYLKKIDYGNADPSTSNGDYRIEGSLAISAQEQIAFLRKLYRNELPFRVEHQRLVKDLMIVEAGRNWILRAKTGWEGRMGWWVGWVEWPTGSVFFALNIDTPNRMDDLFKREAIVRAILRSIEALPPNPAVNSDAAR'},
 'CARD_25': {'Drug Class': 'beta-lactam',
  'Name': 'CTX-M-155',
  'Sequence': 'MVKKSLRQFTLMATATVTLLLGSVPLYAQTADVQQKLAELERQSGGRLGVALINTADNSQILYRADERFAMCSTSKVMAAAAVLKKSESEPNLLNQRVEIKKSDLVNYNPIAEKHVNGTMSLAELSAAALQYSDNVAMNKLIAHVGGPASVTAFARQLGDETFRLDRTAPTLNTAIPGDPRDTTSPRAMAQTLRNLTLGKALGDSQRAQLVTWMKGNTTGAASIQAGLPASWVVGDKTGSGGYGTTNDIAVIWPKDRAPLILVTYFTQPQPKAESRRDVLASGAKIVTDGL'},
 'CARD_26': {'Drug Class': 'beta-lactam',
  'Name': 'DHA-15',
  'Sequence': 'MKKSLSATLISALLAFSAPGFSAADNVAAVVDSTIKPLMAQQDIPGMAVAVSVKGKPYYFNYGFADIQAKQPVTENTLFELGSVSKTFTGVLGAVSVAKKEMALNDPAAKYQPELALPQWKGITLLDLATYTAGGLPLQVPDAVKSRADLLNFYQQWQPSRKPGYMRLYANSSIGLFGALTANAAGMPYEQLLTARILAPLGLSHTFITVPESAQSQYAYGYKNKKPVRVSPGQLDAESYGVKSASKDMLRWAEMNMEPSRAGNADLEMAMYLAQTRYYKTAAINQGLGWEMYDWPQQKDMIINGVTNEVALQPHPVTDNQVQPYNRASWVHKTGATTGFGAYVAFIPEKQVAIVILANKNYPNTERVKAAQAILSALE'},
 'CARD_27': {'Drug Class': 'macrolide ;streptogramin',
  'Name': 'msrE',
  'Sequence': 'MSLIIKARNIRLDYAGRDVLDIDELEIHSYDRIGLVGDNGAGKSSLLKVLNGEIVLAEATLQRFGDFAHISQLGGIEIETVEDRAMLSRLGVSNVQNDTMSGGEETRAKIAAAFSQQVHGILADEPTSHLDLNGIDLLIGQLKAFDGALLVISHDRYFLDMVVDKIWELKDGKITEYWGGYSDYLRQKEEERQHQAVEYELMMKERERLESAVQEKRQQANRLDNKKKGEKSKNSTESAGRLGHAKMTGTKQRKLYQAAKSMEKRLAALEDIQAPEHLRSIRFRQSSALELHNKFPITADGLSLKFGSRTIFDDANFIIPLGAKVAITGSNGTGKTSLLKMISERADGLTISPKAEIGYFTQTGYKFNTHKSVLSFMQEECEYTVAEIRAVLASMGIGANDIQKNLSDLSGGEIIKLLLSKMLLGKYNILLMDEPGNYLDLKSIAALETMMKSYAGTIIFVSHDKQLVDNIADIIYEIKDHKIIKTFERDC'},
 'CARD_28': {'Drug Class': 'beta-lactam',
  'Name': 'OXY-6-3',
  'Sequence': 'MLKSSWRKSALMAAAAVPLLLASGSLWASADAIQQKLADLEKRSGGRLGVALINTTDDSQTLYRGDERFAMCSTGKVMAAAAVLKQSESHPDVVNKRLEIKKSDLVVWSPITEKHLQSGMTLAELSAAALQYSDNTAMNKMISYLGGPEKVTAFAQSIGDVTFRLDRTEPALNSAIPGDKRDTTTPLAMAESLRKLTLGNALGEQQRAQLVTWLKGNTTGGQSIRAGLPASWAVGDKTGAGDYGTTNDIAVIWPENHAPLVLVTYFTQPQQDAKSRKEVLAAAAKIVTEGL'},
 'CARD_29': {'Drug Class': 'phosphonic acid',
  'Name': 'FosA2',
  'Sequence': 'MLQSLNHLTLAVSDLQKSVTFWHELLGLTLHARWNTGAYLTCGDLWVCLSYDEARGYVPPQESDYTHYAFTVAAEDFEPFSHKLEQAGVTVWKQNKSEGASFYFLDPDGHKLELHVGSLAARLAACREKPYAGMVFTSDEA'},
 'CARD_30': {'Drug Class': 'aminoglycoside',
  'Name': "APH(3')-Va",
  'Sequence': 'MDDSTLRRKYPHHEWHAVNEGDSGAFVYQLTGGPEPQPELYAKIAPRAPENSAFDLSGEADRLEWLHRHGIPVPRVVERGADDTAAWLVTEAVPGVAAAEEWPEHQRFAVVEAMAELARALHELPVEDCPSDRRLDAAVAEARRNVAEGLVDLDDLQEERAGWTGDQLLAELDRTRPEKEDLVVCHGDLCPNNVLLDPGTCRVTGVIDVGRLGVADRHADIALAARELEIDEDPWFGPAYAERFLERYGAHRVDKEKLAFYQLLDEFF'},
 'CARD_31': {'Drug Class': 'aminoglycoside',
  'Name': 'AAC(3)-Ia',
  'Sequence': 'MGIIRTCRLGPDQVKSMRAALDLFGREFGDVATYSQHQPDSDYLGNLLRSKTFIALAAFDQEAVVGALAAYVLPRFEQPRSEIYIYDLAVSGEHRRQGIATALINLLKHEANALGAYVIYVQADYGDDPAVALYTKLGIREEVMHFDIDPSTAT'},
 'CARD_32': {'Drug Class': 'fluoroquinolone',
  'Name': 'QnrB58',
  'Sequence': 'MTPLLYKKTGTNMALALVGEKIDRNRFTGEKIDNSTFFNCDFSGADLSGTEFIGCQFYDRESQKGCNFSRAMLKDAIFKSCDLSMADFRNASALGIEIRHCRAQGADFRGASFMNMITTRTWFCSAYITNTNLSYANFSKVVLEKCELWENRWMGAQVLGATFSGSDLSGGEFSTFDWRAANFTHCDLTNSELGDLDIRGVDLQGVKLDNYQASLLMERLGIAIIG'},
 'CARD_33': {'Drug Class': 'aminoglycoside',
  'Name': 'rmtH',
  'Sequence': 'MTIEQAAADILSSKKYQLLCPDTVVRILTQEWGRHKKPKQAVERTRERLHGICGAYLAPQVEKQASTALAAGDVQKALALHASTRERLDTYPQLYQFVFENNLPARVLDIACGLNPLMLHRQGVASVWGCDIHQGLGNVLTPYAQKHGWDFTFALHDVLCAPVAASGDMALVFKLLPLLEREQPGAALALLRTLDAPVICVSFPTRSLGGRGKGMHQHYATWFEGLVAPHFTVQHHTLIGDELLYRIQPNPA'},
 'CARD_34': {'Drug Class': 'beta-lactam',
  'Name': 'OXY-6-1',
  'Sequence': 'MLKSSWRKSALMAAAAVPLLLASGSLWASADAIQQKLADLEKRSGGRLGVALINTADDSQTLYRGDERFAMCSTGKVMAAAAVLKQSESHPDVVNKRLEIKKSDLVVWSPITEKHLQSGMTLAELSAAALQYSDNTAMNKMISYLGGPEKVTAFAQSIGDVTFRLDRTEPALNSAIPGDKRDTTTPLAMAESLRKLTLGNALGEQQRAQLVTWLKGNTTGGQSIRAGLPASWAVGDKTGAGDYGTTNDIAVIWPENHAPLVLVTYFTQPQQDAKSRKEVLAAAAKIVTEGL'},
 'CARD_35': {'Drug Class': 'beta-lactam',
  'Name': 'golS',
  'Sequence': 'MNIGKAAKASKVSAKMIRYYEQIGLIPAASRTDSGYRAYTQADVNQLHFIRRARDLGFSVAEISDLLNLWNNQSRQSADVKRLAQTHIDELDRRIQNMQHMAQTLKALIHCCAGDALPDCPILHTLGQPDDSEPEARTGAVLRRPRRHGLAKRL'},
 'CARD_36': {'Drug Class': 'disinfecting agents and antiseptics;nucleoside',
  'Name': 'mdtP',
  'Sequence': 'MINRQLSRLLLCSILGSTTLISGCALVRKDSAPHQQLKPEQIKLADDIHLASSGWPQAQWWKQLNDPQLDALIQRTLSGSHTLAEAKLREEKAQSQADLLDAGSQLQVAALGMLNRQRVSANGFLSPYSMDAPALGMDGPYYTEATVGLFAGLDLDLWGVHRSAVAAAIGAHNAALAETAAVELSLATGVAQLYYSMQASYQMLDLLEQTHDVIDYAVKAHQSKVAHGLEAQVPFHGARAQILAVDKQIVAVKGQITETRESLRALIGAGASDMPEIRPVALPQVQTGIPATLSYELLARRPDLQAMRWYVQASLDQVDSARALFYPSFDIKAFFGLDSIHLHTLFKKTSRQFNFIPGLKLPLFDGGRLNANLEGTRAASNMMIERYNQSVLNAVRDVAVNGTRLQTLNDEREMQAERVEATRFTQRAAEAAYQRGLTSRLQATEARLPVLAEEMSLLMLDSRRVIQSIQLMKSLGGGYQAGPVVEKK'},
 'CARD_37': {'Drug Class': 'beta-lactam',
  'Name': 'CMY-114',
  'Sequence': 'MMKKSLCCALLLTASFSTFAAAKTEQQIADIVNRTITPLMQEQAIPGMAVAIIYEGKPYYFTWGKADIANNHPVTQQTLFELGSVSKTFNGVLGGDAIARGEIKLSDPVTKYWPELTGKQWRGISLLHLATYTAGGLPLQIPDYVTDKAELLRFYQNWQPQWTPGAKRLYANSSIGLFGALVVKPSGMSYEEAMTRRVLQPLKLAHTWITVPQSEQKNYAWGYREGKPVHVSPGQLDAEAYGVKSSVIDMARWVQANMDASHVQEKTLQQGIELAQSRYWRIGDMYQGLGWEMLNWPLKADSIINGSDSKVALAALPAVEVNPPAPAVKASWVHKTGSTGGFGSYVAFVPEKNLGIVMLANKSYPNPARVEAAWRILEKLQ'},
 'CARD_38': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-60',
  'Sequence': 'MLSRYSKTLAFAVVACTLAISTATAHAELVVRNDLKRVFDDAGVSGTFVLMDITADRTYVVDPARAARSIHPASTFKIPNSLIAFDTGAVRDDQEVLPYGGKPQPYEQWEHDMALPEAIRLSAVPIYQEVARRVGFERMQAYVDAFDYGNRQLGSAIDQFWLRGPLEISAFEEARFTSRMALKQLPVKPRTWDMVQRMLLIEQQGDAALYAKTGVATEYQPEIGWWAGWVERAGHVYAFALNIDMPREGDMAKRIPLGKQLMRALEVWPAP'},
 'CARD_39': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-90',
  'Sequence': 'MNIKALLLITSAIFISACSPYIVTANPNHSASKSDEKAEKIKNLFNEAHTTGVLVIQQGQTQQSYGNDLARASTEYVPASTFKMLNALIGLEHHKATTTEVFKWDGKKRLFPEWEKDMTLGDAMKASAIPVYQDLARRIGLELMSKEVKRVGYGNADIGTQVDNFWLVGPLKITPQQEAQFAYKLANKTLPFSQKVQDEVQSMLFIEEKNGNKIYAKSGWGWDVDPQVGWLTGWVVQPQGNIVAFSLNLEMKKGIPSSVRKEITYKSLEQLGIL'},
 'CARD_40': {'Drug Class': 'beta-lactam',
  'Name': 'SME-2',
  'Sequence': 'MSNKVNFKTASFLFSVCLALSAFNAHANKSDAAAKQIKKLEEDFDGRIGVFAIDTGSGNTFGYRSDERFPLCSSFKGFLAAAVLERVQQKKLDINQKVKYESRDLEYHSPITTKYKGSGMTLGDMASAALQYSDNGATNIIMERFLGGPEGMTKFMRSIGDNEFRLDRWELELNTAIPGDKRDTSTPKAVANSLNKLALGNVLNAKEKAIYQNWLKGNTTGDARIRASVPADWVVGDKTGSCGAYGTANDYAVIWPKNRAPLIVSIYTTRKSKDDKHSDKTIAEASRIAIQAID'},
 'CARD_41': {'Drug Class': 'aminoglycoside',
  'Name': 'AAC(3)-IIIc',
  'Sequence': 'MFSRWSKPLVLAAVTRASLAADLAALGLAAGDAVMVHAAVSKVGRLLDGPDTIIAALSDAGRPAGTILAYADWEARYEDLVDEDGRVPQEWREHIPPFDPRRSRAIRDNGVLPEFLRTTPGALRSGNPGASMVGLGARAEWFTADHPLDYGYGEGSPLARLVEAGGKVLMLGAPLDTLTLLHHAEHLADIPGKRIRRIEVPLATPTGTQWRMIEEFDTGDPIVEGLAEDYFAEIVTAFLAGGRGRQGLIGTAPSVLVDAAAITAFGVAWLESRFGSPSS'},
 'CARD_42': {'Drug Class': 'beta-lactam',
  'Name': 'OXY-2-2',
  'Sequence': 'MIKSSWRKIAMLAAAVPLLLASGALWASTDAIHQKLTDLEKRSGGRLGVALINTADNSQILYRGDERFAMCSTSKVMAAAAVLKQSESNKEVVNKRLEINAADLVVWSPITEKHLQSGMTLAELSAATLQYSDNTAMNLIIGYLGGPEKVTAFARSIGDATFRLDRTEPTLNTAIPGDERDTSTPLAMAESLRKLTLGDALGEQQRAQLVTWLKGNTTGGQSIRAGLPESWVVGDKTGAGDYGTTNDIAVIWPEDHAPLILVTYFTQPQQDAKNRKEVLAAAAKIVTEGL'},
 'CARD_43': {'Drug Class': 'beta-lactam',
  'Name': 'MOX-5',
  'Sequence': 'MQQRQSILWGALATLMWAGLAHAGDKAATDPLRPVVDASIRPLLKEHRIPGMAVAVLKDGKAHYFNYGVADRERAVGVSEQTLFEIGSVSKTLTATLGAYAVVQGGFELDDKASLFAPWLKGSAFDNITMGELATYSAGGLPLQFPEEVDSLEKMQAYYRQWTPAYSRGSHRQYANPSIGLFGYLAASSMKQPFDRLMEQTMLPGLGLYHTYLNVPEQPMGHYAYGYWKEDKPFRVTPAMLAEEPYGIKTSSADLLRFVKANISGVDNAAMQQAIDLTHQGQYAVGEMTQGLGWERYPYPVSEQTLLAGNSPAMIYNANPAAPAPAAAGHPVLFKKTGSTNGFGAYVAFVPAKGIGVVMLANRNYPNEGTLKAGHAILTQLAR'},
 'CARD_44': {'Drug Class': 'beta-lactam',
  'Name': 'TEM-34',
  'Sequence': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMVSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW'},
 'CARD_45': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-69',
  'Sequence': 'MNIKALLLITSAIFISACSPYIVTANPNHSASKSDDKAEKIKNLFNEAHTTGVLVIHQGQTQQSYGNDLARASTEYVPASTFKMLNALIGLEHHKATTTEVFKWDGEKRLFPEWEKNMTLGDAMKASAIPVYQDLARRIGLELMSKEVKRVGYGNADIGTQVDNFWLVGPLKITPQQEAQFAYKLANKTLPFSQKVQDEVQSMLFIEEKNGNKIYAKSGWGWDVNPQVGWLTGWVVQPQGNIVAFSLNLEMKKGIPSSVRKEITYKSLEQLGIL'},
 'CARD_46': {'Drug Class': 'beta-lactam',
  'Name': 'TEM-7',
  'Sequence': 'FFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDSWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNR'},
 'CARD_47': {'Drug Class': 'beta-lactam',
  'Name': 'SHV-24',
  'Sequence': 'MRYIRLCIISLLATLPLAVHASPQPLEQIKLSESQLSGRVGMIEMDLASGRTLTAWRADERFPMMSTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLATVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARGTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR'},
 'CARD_48': {'Drug Class': 'fluoroquinolone',
  'Name': 'QnrB47',
  'Sequence': 'MTLALVGEKIDRNRFTGEKVENSTFFNCDFSGADLSGTEFIGCQFYDRESQKGCNFSRAMLRDAIFKSCDLSMADFRNVSALGIEIRHCRAQGADFRGASFMNMITTRTWFCSAYITNTNLSYANFSKVVLEKCELWENRWMGTQVLGATFSGSDLSGGEFSTFDWRAANFTHCDLTNSELGDLDIRGVDLQGVKLDNYQASLLMERLGIAVIG'},
 'CARD_49': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-256',
  'Sequence': 'MKTFAAYVIIACLSSTALAGSITENTSWNKEFSAEAVNGVFVLCKSSSKSCATNDLARASKEYLPASTFKIPDAIIGLETGVIKNEHQVFKWDGKPRAMKQWERDLTLRGAIQVSAVPVFQQIAREVGEVRMQKYLKKFSYGNQNISGGIDKFWLEGQLRISAVNQVEFLESLYLNKLSASKENQLIVKEALVTEAAPEYLVHSKTGFSGVGTESNPGVAWWVGWVEKETEVYFFAFNMDIDNESKLPLRKSIPTKIMESEGIIGG'},
 'CARD_50': {'Drug Class': 'fluoroquinolone',
  'Name': 'QnrS6',
  'Sequence': 'METYRHTYRHHSFSHQDLSDITFTACTFIRCDFRRANLRDATFINCKFIEQGDIEGCHFDVADLRDASFQQCQLAMANFSNANCYGIELRECDLKGANFSRANFANQVSNRMYFCSAFITGCNLSYANMERVCLEKCELYENRWIGTHLAGASLKESDLSRGVFSEDVWGQFSLQGANLCHAELDGLDPRKVDTSGIKIASWQQEQLLEALGIVVFPD'},
 'CARD_51': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-330',
  'Sequence': 'MYKKALIVATSILFLSACSSNLVKQHQIHSISANKSSEEIKSLFDQAQTTGVLVIKRGQTEEIYGNDLKRASTAYVPASTFKMLNALIGLEHHKATTTEVFKWNGQKRLFPDWEKDMTLGDAMKASAIPVYQELARRIGLDLMSKEVKRIGFGNANIGSKVDNFWLVGPLKITPQQETQFAYQLAHKTLPFSKNVQEQVQSMVFIEKKNGSKIYAKSGWGWDVEPQVGWLTGWVVQPQGEIVAFSLNLEMKKGTSSSIRKEIAYKGLEQLGIL'},
 'CARD_52': {'Drug Class': 'beta-lactam',
  'Name': 'CMY-42',
  'Sequence': 'MMKKSLCCALLLTASFSTFAAAKTEQQIADIVNRTITPLMQEQAIPGMAVAVIYQGKPYYFTWGKADIANNHPVTQQTLFELGSVSKTFNGVLGGDAIARGEIKLSDPVTKYWPELTGKQWQGIRLLHLATYTAGGLPLQIPDDVRDKAALLHFYQNWQPQWTPGAKRLYANSSIGLFGALAVKPSGMSYEEAMTRRVLQPLKLAHTWITVPQNEQKDYAWGYREGKPVHSSPGQLDAEAYGVKSSVIDMARWVQANMDASHVQEKTLQQGIALAQSRYWRIGDMYQGLGWEMLNWPLKADSIINGSDSKVALAALPAVEVNPPAPAVKASWVHKTGSTGGFGSYVAFVPEKNLGIVMLANKSYPNPVRVEAAWRILEKLQ'},
 'CARD_53': {'Drug Class': 'aminoglycoside',
  'Name': "AAC(6')-Ib",
  'Sequence': 'MTNSNDSVTLRLMTEHDLAMLYEWLNRSHIVEWWGGEEARPTLADVQEQYLPSVLAQESVTPYIAMLNGEPIGYAQSYVALGSGDGWWEEETDPGVRGIDQSLANASQLGKGLGTKLVRALVELLFNDPEVTKIQTDPSPSNLRAIRCYEKAGFEKQGTVTTPDGPAVYMVQTRQAFERTRSDA'},
 'CARD_54': {'Drug Class': 'beta-lactam',
  'Name': 'CMY-70',

In [48]:
Classes = pd.Series([MetaDict[key]["Drug Class"] for key, value in MetaDict.items()])

In [49]:
Classes.value_counts().head(10)

beta-lactam        26892
multidrug          13319
glycopeptide        8151
aminoglycoside      4943
bacitracin          4228
tetracycline        2932
MLS                 2655
na                  1290
chloramphenicol     1137
polymyxin           1114
Name: count, dtype: int64

In [50]:
with open("../data/processed/MetaDict.Cov80.maxseq5.json", "w+") as json_file  :
    json.dump(MetaDict, json_file, indent=4)