In [1]:
import sys
sys.path.append('../')
from source import Process
import pandas as pd
import re
import json
import numpy as np

/home/tiago/anaconda3/envs/databases/lib/python3.10/site-packages/Bio/Application/__init__.py:39: BiopythonDeprecationWarning: The Bio.Application modules and modules relying on it have been deprecated.

Due to the on going maintenance burden of keeping command line application
wrappers up to date, we have decided to deprecate and eventually remove these
modules.

We instead now recommend building your command line and invoking it directly
with the subprocess module.
  warnings.warn(

In [2]:
NcrdClusters = Process.ClusterCounter("../data/filtered/ncrd95.21032025.tagged.fasta")
ResfinderClusters = Process.ClusterCounter("../data/filtered/resfinder.21032025.tagged.fasta")
CardClusters = Process.ClusterCounter("../data/filtered/card.21032025.tagged.fasta")
MegaresClusters = Process.ClusterCounter("../data/filtered/megares.21032025.tagged.fasta")
HmdClusters = Process.ClusterCounter("../data/filtered/hmd.21032025.tagged.fasta")
NdaroClusters = Process.ClusterCounter("../data/filtered/ndaro.21032025.tagged.fasta")

================================================================
Program: CD-HIT, V4.8.1 (+OpenMP), Apr 24 2025, 22:00:32
Command: cd-hit -i
         ../data/filtered/ncrd95.21032025.tagged.fasta -o
         ../data/filtered/ncrd95.21032025.tagged.fasta.out -c 1
         -T 12 -p 1 -sc 1 -sf 1 -aL 0.8

Started: Sun May  3 09:36:35 2026
================================================================
                            Output
----------------------------------------------------------------
total seq: 34008
longest and shortest : 2975 and 21
Total letters: 11158353
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 15M
Buffer          : 12 X 17M = 204M
Table           : 2 X 65M = 131M
Miscellaneous   : 0M
Total           : 352M

Table limit with the given memory limit:
Max number of representatives: 883058
Max number of word counting entries: 55961112

# comparing sequences from          0  to       2429
..---------- new table with     2429 representatives
# comparing sequences from       2429  to       4684
----------   2155 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       2529  to       4777
----------   2148 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       2629  to       4870
----------   2141 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       2729  to       4963
----------   2134 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       2829  to       5056
----------   2127 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       2929  to       5148
----------   2119 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       3029  to       5241
----------   2112 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       3129  to       5334
----------   2105 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       3229  to       5427
----------   2098 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       3329  to       5520
----------   2091 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       3429  to       5613
----------   2084 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       3529  to       5706
----------   2077 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       3629  to       5798
----------   2069 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       3729  to       5891
----------   2062 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       3829  to       5984
----------   2055 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       3929  to       6077
----------   2048 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       4029  to       6170
----------   2041 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       4129  to       6263
----------   2034 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       4229  to       6356
----------   2027 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       4329  to       6448
----------   2019 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       4429  to       6541
----------   2012 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       4529  to       6634
----------   2005 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       4629  to       6727
----------   1998 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       4729  to       6820
----------   1991 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       4829  to       6913
----------   1984 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       4929  to       7006
----------   1977 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       5029  to       7098
----------   1969 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       5129  to       7191
----------   1962 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       5229  to       7284
----------   1955 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       5329  to       7377
----------   1948 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       5429  to       7470
----------   1941 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       5529  to       7563
----------   1934 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       5629  to       7656
----------   1927 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       5729  to       7748
----------   1919 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       5829  to       7841
----------   1912 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       5929  to       7934
----------   1905 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       6029  to       8027
----------   1898 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       6129  to       8120
----------   1891 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       6229  to       8213
----------   1884 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       6329  to       8306
----------   1877 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       6429  to       8398
----------   1869 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       6529  to       8491
----------   1862 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       6629  to       8584
----------   1855 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       6729  to       8677
----------   1848 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       6829  to       8770
----------   1841 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       6929  to       8863
----------   1834 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       7029  to       8956
----------   1827 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       7129  to       9048
----------   1819 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       7229  to       9141
----------   1812 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       7329  to       9234
----------   1805 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       7429  to       9327
----------   1798 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       7529  to       9420
----------   1791 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       7629  to       9513
----------   1784 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       7729  to       9606
----------   1777 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       7829  to       9698
----------   1769 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       7929  to       9791
----------   1762 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       8029  to       9884
----------   1755 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       8129  to       9977
----------   1748 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       8229  to      10070
----------   1741 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       8329  to      10163
----------   1734 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       8429  to      10256
----------   1727 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       8529  to      10348
----------   1719 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       8629  to      10441
----------   1712 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       8729  to      10534
----------   1705 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       8829  to      10627
----------   1698 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       8929  to      10720
----------   1691 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       9029  to      10813
----------   1684 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       9129  to      10906
----------   1677 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       9229  to      10998
----------   1669 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       9329  to      11091
----------   1662 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       9429  to      11184
----------   1655 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       9529  to      11277
----------   1648 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       9629  to      11370
----------   1641 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       9729  to      11463
----------   1634 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       9829  to      11556
----------   1627 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from       9929  to      11648
..........    10000  finished      10000  clusters
----------   1619 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from      10029  to      11741
----------   1612 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from      10129  to      11834
----------   1605 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from      10229  to      11927
----------   1598 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from      10329  to      12020
----------   1591 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from      10429  to      12113
----------   1584 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from      10529  to      12206
----------   1577 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from      10629  to      12298
----------   1569 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from      10729  to      12391
----------   1562 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from      10829  to      12484
----------   1555 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from      10929  to      12577
----------   1548 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from      11029  to      12670
----------   1541 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from      11129  to      12763
----------   1534 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from      11229  to      12856
----------   1527 remaining sequences to the next cycle
---------- new table with      100 representatives
# comparing sequences from      11329  to      12948
----------   1499 remaining sequences to the next cycle
---------- new table with      120 representatives
# comparing sequences from      11449  to      13060
----------   1477 remaining sequences to the next cycle
---------- new table with      134 representatives
# comparing sequences from      11583  to      13184
----------   1459 remaining sequences to the next cycle
---------- new table with      142 representatives
# comparing sequences from      11725  to      13316
----------   1438 remaining sequences to the next cycle
---------- new table with      153 representatives
# comparing sequences from      11878  to      13458
----------   1416 remaining sequences to the next cycle
---------- new table with      164 representatives
# comparing sequences from      12042  to      13611
----------   1402 remaining sequences to the next cycle
---------- new table with      167 representatives
# comparing sequences from      12209  to      13766
----------   1405 remaining sequences to the next cycle
---------- new table with      152 representatives
# comparing sequences from      12361  to      13907
----------   1386 remaining sequences to the next cycle
---------- new table with      160 representatives
# comparing sequences from      12521  to      14055
----------   1363 remaining sequences to the next cycle
---------- new table with      171 representatives
# comparing sequences from      12692  to      14214
----------   1347 remaining sequences to the next cycle
---------- new table with      175 representatives
# comparing sequences from      12867  to      14377
----------   1336 remaining sequences to the next cycle
---------- new table with      174 representatives
# comparing sequences from      13041  to      14538
----------   1325 remaining sequences to the next cycle
---------- new table with      172 representatives
# comparing sequences from      13213  to      14698
----------   1307 remaining sequences to the next cycle
---------- new table with      178 representatives
# comparing sequences from      13391  to      14863
----------   1295 remaining sequences to the next cycle
---------- new table with      177 representatives
# comparing sequences from      13568  to      15028
----------   1263 remaining sequences to the next cycle
---------- new table with      197 representatives
# comparing sequences from      13765  to      15210
----------   1251 remaining sequences to the next cycle
---------- new table with      194 representatives
# comparing sequences from      13959  to      15391
----------   1240 remaining sequences to the next cycle
---------- new table with      192 representatives
# comparing sequences from      14151  to      15569
----------   1238 remaining sequences to the next cycle
---------- new table with      180 representatives
# comparing sequences from      14331  to      15736
----------   1208 remaining sequences to the next cycle
---------- new table with      197 representatives
# comparing sequences from      14528  to      15919
----------   1213 remaining sequences to the next cycle
---------- new table with      178 representatives
# comparing sequences from      14706  to      16084
----------   1214 remaining sequences to the next cycle
---------- new table with      164 representatives
# comparing sequences from      14870  to      16237
----------   1216 remaining sequences to the next cycle
---------- new table with      151 representatives
# comparing sequences from      15021  to      16377
----------   1208 remaining sequences to the next cycle
---------- new table with      148 representatives
# comparing sequences from      15169  to      16514
----------   1182 remaining sequences to the next cycle
---------- new table with      163 representatives
# comparing sequences from      15332  to      16666
----------   1172 remaining sequences to the next cycle
---------- new table with      162 representatives
# comparing sequences from      15494  to      16816
----------   1170 remaining sequences to the next cycle
---------- new table with      152 representatives
# comparing sequences from      15646  to      16957
----------   1163 remaining sequences to the next cycle
---------- new table with      148 representatives
# comparing sequences from      15794  to      17095
----------   1157 remaining sequences to the next cycle
---------- new table with      144 representatives
# comparing sequences from      15938  to      17228
----------   1158 remaining sequences to the next cycle
---------- new table with      132 representatives
# comparing sequences from      16070  to      17351

In [3]:
ClusterLimits = pd.DataFrame({
    "Database": ["NCRD", "Resfinder", "CARD", "MEGARES", "HMD", "NDARO"],
    "100%": [NcrdClusters[0][0], ResfinderClusters[0][0], CardClusters[0][0], MegaresClusters[0][0], HmdClusters[0][0], NdaroClusters[0][0]],
    "95%":  [NcrdClusters[0][1], ResfinderClusters[0][1], CardClusters[0][1], MegaresClusters[0][1], HmdClusters[0][1], NdaroClusters[0][1]],
    "90%":  [NcrdClusters[0][2], ResfinderClusters[0][2], CardClusters[0][2], MegaresClusters[0][2], HmdClusters[0][2], NdaroClusters[0][2]],
    "85%":  [NcrdClusters[0][3], ResfinderClusters[0][3], CardClusters[0][3], MegaresClusters[0][3], HmdClusters[0][3], NdaroClusters[0][3]],
    "80%":  [NcrdClusters[0][4], ResfinderClusters[0][4], CardClusters[0][4], MegaresClusters[0][4], HmdClusters[0][4], NdaroClusters[0][4]],  
    "75%":  [NcrdClusters[0][5], ResfinderClusters[0][5], CardClusters[0][5], MegaresClusters[0][5], HmdClusters[0][5], NdaroClusters[0][5]],
    "70%":  [NcrdClusters[0][6], ResfinderClusters[0][6], CardClusters[0][6], MegaresClusters[0][6], HmdClusters[0][6], NdaroClusters[0][6]]
})
ClusterLimits = ClusterLimits.set_index("Database").T
ClusterLimits.columns.name = None
ClusterLimits.to_csv("../data/processed/cdhitclusters.defaultsettings.csv", index=True, sep = "\t")

In [4]:
PairWiseAlignment = pd.read_csv(
    "../data/filtered/AllDatabases.Paiwise.cov80.maxseq1.tsv", 
    sep = "\t",
    skipinitialspace=True, 
    header=None,
    names = "qseqid sseqid pident length qlen slen qstart qend sstart send evalue bitscore ppos full_qseq full_sseq".split(" ")
)

PairWiseAlignment["qseqtag"] = PairWiseAlignment["qseqid"].str.split("|").str[1]
PairWiseAlignment["sseqtag"] = PairWiseAlignment["sseqid"].str.split("|").str[1]
PairWiseAlignment["qseqid"] = PairWiseAlignment["qseqid"].str.split("|").str[0]
PairWiseAlignment["sseqid"] = PairWiseAlignment["sseqid"].str.split("|").str[0]
PairWiseAlignment = PairWiseAlignment.loc[PairWiseAlignment.pident >= 95]
PairWiseAlignment.replace({"RESFINDER":"ResFinder", "MEGARES":"MegaRes","HMDARG":"HMDARG-DB"}, inplace = True)
BlastPairWiseAlignmentPivoted = PairWiseAlignment.pivot_table(index="qseqtag", columns="sseqtag", values="pident", aggfunc="count").fillna(0)
BlastPairWiseAlignmentPivoted.index.name = None
BlastPairWiseAlignmentPivoted.columns.name = None
BlastPairWiseAlignmentPivoted.to_csv("../data/processed/BlastPairWiseAlignmentPivoted.cov80.maxseq1.csv", index=True, sep = "\t")

In [5]:
BlastPairWiseAlignmentPivoted

             CARD     HMD  MegaRes    NCRD   NDARO  ResFinder
CARD         25.0  2866.0   1774.0    84.0  1285.0        0.0
HMD        4018.0  6921.0   1283.0  1988.0   264.0        6.0
MegaRes    4786.0  1373.0    164.0    67.0   241.0      196.0
NCRD       2038.0  3564.0    231.0  4963.0    65.0        1.0
NDARO      5771.0   985.0    302.0    40.0    69.0       15.0
ResFinder  2254.0   327.0    336.0     0.0    18.0       10.0

In [6]:
PairWiseAlignment

,qseqid,sseqid,pident,length,qlen,slen,qstart,qend,sstart,send,evalue,bitscore,ppos,full_qseq,full_sseq,qseqtag,sseqtag
0,CARD_0,MEGARES_1086,100.0,296,296,296,1,296,1,296,5.450000e-215,587.0,100.0,MKAYFIAILTLFTCIATVVRAQQMSELENRIDSLLNGKKATVGIAV...,MKAYFIAILTLFTCIATVVRAQQMSELENRIDSLLNGKKATVGIAV...,CARD,MegaRes
1,CARD_1,HMD_829,100.0,286,286,286,1,286,1,286,3.770000e-201,551.0,100.0,MRYIRLCIISLLAALPLAVHASPQPLEQIKQSESQLSGRVGMIEMD...,MRYIRLCIISLLAALPLAVHASPQPLEQIKQSESQLSGRVGMIEMD...,CARD,HMD
2,CARD_2,NCRD_0,100.0,164,164,164,1,164,1,164,3.050000e-117,328.0,100.0,MIGLIVARSKNNVIGKNGNIPWKIKGEQKQFRELTTGNVVIMGRKS...,MIGLIVARSKNNVIGKNGNIPWKIKGEQKQFRELTTGNVVIMGRKS...,CARD,NCRD
3,CARD_3,HMD_1374,100.0,291,291,291,1,291,1,291,5.800000e-203,556.0,100.0,MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGG...,MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGG...,CARD,HMD
4,CARD_4,HMD_247,100.0,270,270,270,1,270,1,270,2.760000e-195,535.0,100.0,MELPNIMHPVAKLSTALAAALMLSGCMPGEIRPTIGQQMETGDQRF...,MELPNIMHPVAKLSTALAAALMLSGCMPGEIRPTIGQQMETGDQRF...,CARD,HMD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74155,RESFINDER_2950,HMD_5549,100.0,283,283,283,1,283,1,283,1.220000e-200,549.0,100.0,MLRSRVTVFGILNLTEDSFFDESRRLDPAGAVTAAIEMLRVGSDVV...,MLRSRVTVFGILNLTEDSFFDESRRLDPAGAVTAAIEMLRVGSDVV...,ResFinder,HMD
74156,RESFINDER_2951,MEGARES_4771,100.0,275,275,275,1,275,1,275,2.870000e-195,535.0,100.0,MVTVFGILNLTEDSFFDESRRLDPAGAVTAAIEMLRVGSDVVDVGP...,MVTVFGILNLTEDSFFDESRRLDPAGAVTAAIEMLRVGSDVVDVGP...,ResFinder,MegaRes
74157,RESFINDER_2952,HMD_8396,100.0,279,279,279,1,279,1,279,7.040000e-198,542.0,100.0,MVTVFGILNLTEDSFFDESRRLDPAGAVTAAIEMLRVGSDVVDVGP...,MVTVFGILNLTEDSFFDESRRLDPAGAVTAAIEMLRVGSDVVDVGP...,ResFinder,HMD
74158,RESFINDER_2953,MEGARES_4770,100.0,279,279,279,1,279,1,279,1.730000e-198,543.0,100.0,MVTVFGILNLTEDSFFDESRRLDPAGAVTAAIEMLRVGSDVVDVGP...,MVTVFGILNLTEDSFFDESRRLDPAGAVTAAIEMLRVGSDVVDVGP...,ResFinder,MegaRes
74159,RESFINDER_2954,CARD_2338,100.0,287,287,287,1,287,1,287,9.600000e-200,547.0,100.0,MSTTLTSFKWGERTYIMGILNVTPDSFSGDGVMVEEDVIAKAVAQA...,MSTTLTSFKWGERTYIMGILNVTPDSFSGDGVMVEEDVIAKAVAQA...,ResFinder,CARD

In [7]:
CardIndex = pd.read_csv(
    "../data/raw/CARD_Index.tsv",
    sep = "\t"
)
CardDict = CardIndex.drop_duplicates(subset="ARO Accession", keep='first').set_index("ARO Accession").to_dict(orient="index")
## Duplicates
CardIndex.value_counts("ARO Accession")[:10]

ARO Accession
ARO:3002118    2
ARO:3003900    2
ARO:3003893    2
ARO:3000506    2
ARO:3003170    2
ARO:3006379    1
ARO:3006378    1
ARO:3006377    1
ARO:3006376    1
ARO:3006375    1
Name: count, dtype: int64

In [8]:
NDAROIndex = pd.read_csv(
    "../data/raw/NDARO_Index.tsv", 
    sep="\t")
NdaroDict = NDAROIndex.dropna(subset=["RefSeq protein"]).drop_duplicates(subset="RefSeq protein", keep='first').set_index("RefSeq protein").to_dict(orient="index")
NDAROIndex.value_counts("RefSeq protein")[:10]

RefSeq protein
WP_000090315.1    61
WP_000918664.1    44
WP_003112576.1    32
WP_001281271.1    24
WP_003436174.1    24
WP_001281881.1    23
WP_001281243.1    23
WP_001212189.1    23
WP_003094139.1    22
WP_005693446.1    22
Name: count, dtype: int64

In [9]:
SCHEMAS = {
    "CARD": {
        "AROSplitPoint": 3,
        "IndexInfo": CardDict
    },
    "NDARO": {
        "AccSplitPoint": 0,
        "IndexInfo": NdaroDict
    },
    "MEGARES": {
        "DrugClassSplitPoint": 3,
        "NameSplitPoint": -1
    },
    "HMD": {
        "DrugClassSplitPoint": 4,
        "NameSplitPoint": 5
    },
    "NCRD": {
        "DrugClassSplitPoint": 4,
        "NameSplitPoint": 2
    },
    "RESFINDER": {
        "DrugClassSplitPoint": 2,
        "NameSplitPoint": 1
    }
}

In [10]:
MetaDict = Process.CreateMetadataFile(
    "../data/filtered/AllDatabases.21032025.tagged.fasta_ids",
    SCHEMAS
    )

In [11]:
MetaDict

{'CARD_0': {'Drug Class': 'cephalosporin', 'Name': 'CblA-1'},
 'CARD_1': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-52'},
 'CARD_2': {'Drug Class': 'diaminopyrimidine antibiotic', 'Name': 'dfrF'},
 'CARD_3': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-130'},
 'CARD_4': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'NDM-6'},
 'CARD_5': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'ACT-35'},
 'CARD_6': {'Drug Class': 'penicillin beta-lactam', 'Name': 'CARB-5'},
 'CARD_7': {'Drug Class': 'lincosamide antibiotic;macrolide antibiotic;streptogramin A antibiotic;streptogramin B antibiotic;streptogramin antibiotic',
  'Name': 'Erm(34)'},
 'CARD_8': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-126'},
 'CARD_9': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'LRA-12'},
 'CARD_10': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-72'},
 'CARD_11': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-59'},
 'CARD_12': {'Drug Class': 'carbapenem;cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'KPC-10'},
 'CARD_13': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-212'},
 'CARD_14': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'IMP-2'},
 'CARD_15': {'Drug Class': 'cephalosporin', 'Name': 'CMY-1'},
 'CARD_16': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-329'},
 'CARD_17': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'ACT-10'},
 'CARD_18': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-371'},
 'CARD_19': {'Drug Class': 'fusidane antibiotic', 'Name': 'fusB'},
 'CARD_20': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-121'},
 'CARD_21': {'Drug Class': 'cephalosporin;monobactam', 'Name': 'VEB-3'},
 'CARD_22': {'Drug Class': 'lincosamide antibiotic', 'Name': 'lnuA'},
 'CARD_23': {'Drug Class': 'penicillin beta-lactam', 'Name': 'OXA-45'},
 'CARD_24': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OXA-226'},
 'CARD_25': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-155'},
 'CARD_26': {'Drug Class': 'cephalosporin', 'Name': 'DHA-15'},
 'CARD_27': {'Drug Class': 'macrolide antibiotic;streptogramin antibiotic',
  'Name': 'msrE'},
 'CARD_28': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OXY-6-3'},
 'CARD_29': {'Drug Class': 'phosphonic acid antibiotic', 'Name': 'FosA2'},
 'CARD_30': {'Drug Class': 'aminoglycoside antibiotic', 'Name': "APH(3')-Va"},
 'CARD_31': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'AAC(3)-Ia'},
 'CARD_32': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrB58'},
 'CARD_33': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'rmtH'},
 'CARD_34': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OXY-6-1'},
 'CARD_35': {'Drug Class': 'carbapenem;cephalosporin;monobactam;penicillin beta-lactam;phenicol antibiotic',
  'Name': 'golS'},
 'CARD_36': {'Drug Class': 'disinfecting agents and antiseptics;nucleoside antibiotic',
  'Name': 'mdtP'},
 'CARD_37': {'Drug Class': 'cephalosporin', 'Name': 'CMY-114'},
 'CARD_38': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-60'},
 'CARD_39': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-90'},
 'CARD_40': {'Drug Class': 'carbapenem', 'Name': 'SME-2'},
 'CARD_41': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'AAC(3)-IIIc'},
 'CARD_42': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OXY-2-2'},
 'CARD_43': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'MOX-5'},
 'CARD_44': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-34'},
 'CARD_45': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-69'},
 'CARD_46': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-7'},
 'CARD_47': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-24'},
 'CARD_48': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrB47'},
 'CARD_49': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OXA-256'},
 'CARD_50': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrS6'},
 'CARD_51': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-330'},
 'CARD_52': {'Drug Class': 'cephalosporin', 'Name': 'CMY-42'},
 'CARD_53': {'Drug Class': 'aminoglycoside antibiotic', 'Name': "AAC(6')-Ib"},
 'CARD_54': {'Drug Class': 'cephalosporin', 'Name': 'CMY-70'},
 'CARD_55': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'GES-21'},
 'CARD_56': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-41'},
 'CARD_57': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-391'},
 'CARD_58': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-132'},
 'CARD_59': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'aadA23'},
 'CARD_60': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'NDM-10'},
 'CARD_61': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrB66'},
 'CARD_62': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-42'},
 'CARD_63': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OXA-35'},
 'CARD_64': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-18'},
 'CARD_65': {'Drug Class': 'fusidane antibiotic', 'Name': 'fusH'},
 'CARD_66': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-79'},
 'CARD_67': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-47'},
 'CARD_68': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-16'},
 'CARD_69': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'VIM-37'},
 'CARD_70': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'ACT-29'},
 'CARD_71': {'Drug Class': 'cephalosporin', 'Name': 'FOX-3'},
 'CARD_72': {'Drug Class': 'carbapenem;cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'PER-4'},
 'CARD_73': {'Drug Class': 'carbapenem;cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'GIM-1'},
 'CARD_74': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'IMP-42'},
 'CARD_75': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-102'},
 'CARD_76': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-116'},
 'CARD_77': {'Drug Class': 'cephalosporin', 'Name': 'CMY-55'},
 'CARD_78': {'Drug Class': 'fluoroquinolone antibiotic;macrolide antibiotic;penicillin beta-lactam',
  'Name': 'gadX'},
 'CARD_79': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-42'},
 'CARD_80': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-105'},
 'CARD_81': {'Drug Class': 'cephalosporin', 'Name': 'CMY-79'},
 'CARD_82': {'Drug Class': 'cephalosporin', 'Name': 'CMY-56'},
 'CARD_83': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-426'},
 'CARD_84': {'Drug Class': 'cephalosporin', 'Name': 'CMY-48'},
 'CARD_85': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrB38'},
 'CARD_86': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-109'},
 'CARD_87': {'Drug Class': 'cephalosporin;monobactam', 'Name': 'TLA-2'},
 'CARD_88': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-12'},
 'CARD_89': {'Drug Class': 'penicillin beta-lactam', 'Name': 'OXA-61'},
 'CARD_90': {'Drug Class': 'penicillin beta-lactam', 'Name': 'CARB-4'},
 'CARD_91': {'Drug Class': 'phenicol antibiotic', 'Name': 'catB9'},
 'CARD_92': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-43'},
 'CARD_93': {'Drug Class': 'carbapenem;cephalosporin;monobactam',
  'Name': 'PDC-8'},
 'CARD_94': {'Drug Class': 'lincosamide antibiotic;macrolide antibiotic;streptogramin A antibiotic;streptogramin B antibiotic;streptogramin antibiotic',
  'Name': 'ErmE'},
 'CARD_95': {'Drug Class': 'aminoglycoside antibiotic', 'Name': "AAC(6')-Iu"},
 'CARD_96': {'Drug Class': 'cephalosporin;monobactam', 'Name': 'VEB-5'},
 'CARD_97': {'Drug Class': 'diaminopyrimidine antibiotic', 'Name': 'dfrA13'},
 'CARD_98': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-87'},
 'CARD_99': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrB18'},
 'CARD_100': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'LRA-9'},
 'CARD_101': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'VIM-12'},
 'CARD_102': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'aadA4'},
 'CARD_103': {'Drug Class': 'fluoroquinolone antibiotic;macrolide antibiotic;penicillin beta-lactam',
  'Name': 'mdtF'},
 'CARD_104': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'VIM-34'},
 'CARD_105': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-64'},
 'CARD_106': {'Drug Class': 'carbapenem', 'Name': 'IND-7'},
 'CARD_107': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-182'},
 'CARD_108': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-183'},
 'CARD_109': {'Drug Class': 'lincosamide antibiotic;oxazolidinone antibiotic;phenicol antibiotic;pleuromutilin antibiotic;streptogramin A antibiotic;streptogramin antibiotic',
  'Name': 'clbB'},
 'CARD_110': {'Drug Class': 'macrolide antibiotic', 'Name': 'srmB'},
 'CARD_111': {'Drug Class': 'phosphonic acid antibiotic', 'Name': 'FosX'},
 'CARD_112': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-112'},
 'CARD_113': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-50'},
 'CARD_114': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-198'},
 'CARD_115': {'Drug Class': 'rifamycin antibiotic', 'Name': 'arr-8'},
 'CARD_116': {'Drug Class': 'rifamycin antibiotic', 'Name': 'rgt1438'},
 'CARD_117': {'Drug Class': 'carbapenem', 'Name': 'SME-5'},
 'CARD_118': {'Drug Class': 'cephalosporin', 'Name': 'CMY-9'},
 'CARD_119': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': "APH(2'')-Ie"},
 'CARD_120': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrB10'},
 'CARD_121': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': "AAC(6')-IIb"},
 'CARD_122': {'Drug Class': 'carbapenem', 'Name': 'cphA7'},
 'CARD_123': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'IMP-12'},
 'CARD_124': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-229'},
 'CARD_125': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-98'},
 'CARD_126': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-27'},
 'CARD_127': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-92'},
 'CARD_128': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'aadA12'},
 'CARD_129': {'Drug Class': 'phenicol antibiotic', 'Name': 'catB3'},
 'CARD_130': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OKP-A-15'},
 'CARD_131': {'Drug Class': 'aminocoumarin antibiotic;aminoglycoside antibiotic',
  'Name': 'cpxA'},
 'CARD_132': {'Drug Class': 'fluoroquinolone antibiotic;tetracycline antibiotic',
  'Name': 'adeF'},
 'CARD_133': {'Drug Class': 'cephalosporin;disinfecting agents and antiseptics;fluoroquinolone antibiotic;penicillin beta-lactam;peptide antibiotic;tetracycline antibiotic',
  'Name': 'mgrA'},
 'CARD_134': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-195'},
 'CARD_135': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': "AAC(6')-Iaf"},
 'CARD_136': {'Drug Class': 'diaminopyrimidine antibiotic', 'Name': 'dfrA21'},
 'CARD_137': {'Drug Class': 'lincosamide antibiotic;macrolide antibiotic',
  'Name': 'myrA'},
 'CARD_138': {'Drug Class': 'lincosamide antibiotic;pleuromutilin antibiotic;streptogramin A antibiotic;streptogramin antibiotic',
  'Name': 'vgaALC'},
 'CARD_139': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-236'},
 'CARD_140': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-56'},
 'CARD_141': {'Drug Class': 'carbapenem;cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'KPC-8'},
 'CARD_142': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-376'},
 'CARD_143': {'Drug Class': 'glycopeptide antibiotic', 'Name': 'vanN'},
 'CARD_144': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'VIM-29'},
 'CARD_145': {'Drug Class': 'tetracycline antibiotic', 'Name': 'tet(42)'},
 'CARD_146': {'Drug Class': 'tetracycline antibiotic', 'Name': 'tet(45)'},
 'CARD_147': {'Drug Class': 'tetracycline antibiotic', 'Name': 'tet(E)'},
 'CARD_148': {'Drug Class': 'peptide antibiotic', 'Name': 'tsnR'},
 'CARD_149': {'Drug Class': 'cephalosporin', 'Name': 'CMY-39'},
 'CARD_150': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'VIM-17'},
 'CARD_151': {'Drug Class': 'aminoglycoside antibiotic;fluoroquinolone antibiotic;phosphonic acid antibiotic',
  'Name': 'fosA5'},
 'CARD_152': {'Drug Class': 'phenicol antibiotic',
  'Name': 'Streptomyces lividans cmlR'},
 'CARD_153': {'Drug Class': 'glycopeptide antibiotic',
  'Name': 'vanR gene in vanB cluster'},
 'CARD_154': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'IMP-33'},
 'CARD_155': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'IMP-19'},
 'CARD_156': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-78'},
 'CARD_157': {'Drug Class': 'rifamycin antibiotic', 'Name': 'arr-4'},
 'CARD_158': {'Drug Class': 'cephalosporin', 'Name': 'CfxA2'},
 'CARD_159': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-24'},
 'CARD_160': {'Drug Class': 'cephalosporin', 'Name': 'CMY-25'},
 'CARD_161': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'IMP-51'},
 'CARD_162': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrA5'},
 'CARD_163': {'Drug Class': 'cephalosporin', 'Name': 'DHA-19'},
 'CARD_164': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'GES-14'},
 'CARD_165': {'Drug Class': 'disinfecting agents and antiseptics;fluoroquinolone antibiotic',
  'Name': 'arlS'},
 'CARD_166': {'Drug Class': 'glycylcycline;tetracycline antibiotic',
  'Name': 'adeS'},
 'CARD_167': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OCH-1'},
 'CARD_168': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-232'},
 'CARD_169': {'Drug Class': 'penicillin beta-lactam', 'Name': 'OXA-12'},
 'CARD_170': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-348'},
 'CARD_171': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-89'},
 'CARD_172': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-19'},
 'CARD_173': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-195'},
 'CARD_174': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-199'},
 'CARD_175': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-38'},
 'CARD_176': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-121'},
 'CARD_177': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-61'},
 'CARD_178': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-58'},
 'CARD_179': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-56'},
 'CARD_180': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-138'},
 'CARD_181': {'Drug Class': 'cephalosporin', 'Name': 'SRT-1'},
 'CARD_182': {'Drug Class': 'penicillin beta-lactam', 'Name': 'LEN-14'},
 'CARD_183': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OCH-3'},
 'CARD_184': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-101'},
 'CARD_185': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OXY-2-8'},
 'CARD_186': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'VIM-43'},
 'CARD_187': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'APH(4)-Ia'},
 'CARD_188': {'Drug Class': 'phosphonic acid antibiotic', 'Name': 'FomA'},
 'CARD_189': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'GES-12'},
 'CARD_190': {'Drug Class': 'cephalosporin', 'Name': 'CMY-105'},
 'CARD_191': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': "AAC(3)-Ib/AAC(6')-Ib3 bifunctional protein"},
 'CARD_192': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-35'},
 'CARD_193': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-206'},
 'CARD_194': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OXA-21'},
 'CARD_195': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-121'},
 'CARD_196': {'Drug Class': 'peptide antibiotic', 'Name': 'bcrC'},
 'CARD_197': {'Drug Class': 'penicillin beta-lactam', 'Name': 'LEN-9'},
 'CARD_198': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'npmA'},
 'CARD_199': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OKP-A-12'},
 'CARD_200': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-92'},
 'CARD_201': {'Drug Class': 'cephalosporin', 'Name': 'CMY-100'},
 'CARD_202': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'GES-3'},
 'CARD_203': {'Drug Class': 'cephalosporin;monobactam', 'Name': 'MIR-2'},
 'CARD_204': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-88'},
 'CARD_205': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-113'},
 'CARD_206': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OKP-B-3'},
 'CARD_207': {'Drug Class': 'cephalosporin;disinfecting agents and antiseptics;fluoroquinolone antibiotic;glycylcycline;penicillin beta-lactam;phenicol antibiotic;rifamycin antibiotic;tetracycline antibiotic',
  'Name': 'sdiA'},
 'CARD_208': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-422'},
 'CARD_209': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-178'},
 'CARD_210': {'Drug Class': 'carbapenem', 'Name': 'imiH'},
 'CARD_211': {'Drug Class': 'penicillin beta-lactam', 'Name': 'LEN-21'},
 'CARD_212': {'Drug Class': 'fluoroquinolone antibiotic', 'Name': 'QnrS8'},
 'CARD_213': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-181'},
 'CARD_214': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'ACT-19'},
 'CARD_215': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-137'},
 'CARD_216': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-83'},
 'CARD_217': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'ACT-30'},
 'CARD_218': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-152'},
 'CARD_219': {'Drug Class': 'penicillin beta-lactam', 'Name': 'OXA-9'},
 'CARD_220': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-164'},
 'CARD_221': {'Drug Class': 'phenicol antibiotic', 'Name': 'cmlA5'},
 'CARD_222': {'Drug Class': 'cephalosporin', 'Name': 'CTX-M-126'},
 'CARD_223': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-158'},
 'CARD_224': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OKP-B-9'},
 'CARD_225': {'Drug Class': 'lincosamide antibiotic;macrolide antibiotic;streptogramin antibiotic',
  'Name': 'ermZ'},
 'CARD_226': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': "APH(3')-VIIa"},
 'CARD_227': {'Drug Class': 'aminoglycoside antibiotic', 'Name': 'APH(9)-Ia'},
 'CARD_228': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-150'},

In [12]:
PairWiseAlignment = pd.read_csv(
    "../data/filtered/AllDatabases.Paiwise.cov80.maxseq1.tsv", 
    sep = "\t",
    skipinitialspace=True, 
    header=None,
    names = "qseqid sseqid pident length qlen slen qstart qend sstart send evalue bitscore ppos full_qseq full_sseq".split(" ")
)
PairWiseAlignment["qcov"] = np.round((PairWiseAlignment["qend"] - PairWiseAlignment["qstart"] + 1) / (PairWiseAlignment["qlen"]) * 100, 2)
PairWiseAlignment["scov"] = np.round((PairWiseAlignment["send"] - PairWiseAlignment["sstart"] + 1) / (PairWiseAlignment["slen"]) * 100, 2)
PairWiseAlignment["qseqtag"] = PairWiseAlignment["qseqid"].str.split("|").str[1]
PairWiseAlignment["sseqtag"] = PairWiseAlignment["sseqid"].str.split("|").str[1]
PairWiseAlignment["qseqid"] = PairWiseAlignment["qseqid"].str.split("|").str[0]
PairWiseAlignment["sseqid"] = PairWiseAlignment["sseqid"].str.split("|").str[0]

In [13]:
PairWiseDictSource = PairWiseAlignment[["qseqid","full_qseq"]].set_index("qseqid").to_dict()["full_qseq"]
PairWiseDictTarget = PairWiseAlignment[["sseqid","full_sseq"]].set_index("sseqid").to_dict()["full_sseq"]

In [14]:
PairWiseDictTarget

{'MEGARES_1086': 'MKAYFIAILTLFTCIATVVRAQQMSELENRIDSLLNGKKATVGIAVWTDKGDMLRYNDHVHFPLLSVFKFHVALAVLDKMDKQSISLDSIVSIKASQMPPNTYSPLRKKFPDQDFTITLRELMQYSISQSDNNACDILIEYAGGIKHINDYIHRLSIDSFNLSETEDGMHSSFEAVYRNWSTPSAMVRLLRTADEKELFSNKELKDFLWQTMIDTETGANKLKGMLPAKTVVGHKTGSSDRNADGMKTADNDAGLVILPDGRKYYIAAFVMDSYETDEDNANIIARISRMVYDAMR',
 'HMD_829': 'MRYIRLCIISLLAALPLAVHASPQPLEQIKQSESQLSGRVGMIEMDLASGRTLTAWRADERFPMISTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLAIVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARDTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR',
 'NCRD_0': 'MIGLIVARSKNNVIGKNGNIPWKIKGEQKQFRELTTGNVVIMGRKSYEEIGHPLPNRMNIVVSTTTEYQGDNLVSVKSLEDALLLAKGRDVYISGGYGLFKEALQIVDKMYITEVDLNIEDGDTFFPEFDINDFEVLIGETLGEEVKYTRTFYVRKNELSRFWI',
 'HMD_1374': 'MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDERFPMCSTSKVMAAAAVLKQSETQKQLLNQPVEIKPADLVNYNPIAEKHVNGTMTLAELSAAALQYSDNTAMNKLIAQLGGPGGVTAFARAIGDETFRLDRTEPTLNTAIPGDPRDTTTPRAMAQTLRQLTLGHALGETQRAQLVTWLKGNTTGAASIRAGLPTSWTVGDKTGSGDYGTTNDIAVIWPQGRAPLVLVTYFTQPQQNAERRHDVLASAARIIAEGL',
 'HMD_247': 'MELPNIMHPVAKLSTALAAALMLSGCMPGEIRPTIGQQMETGDQRFGDLVFRQLAPNVWQHTSYLDMPGFGAVASNGLIVRDGGRVLVVDTAWTDDQTAQILNWIKQEINLPVALAVVTHAHQDKMGGMDALHAAGIATYANALSNQLAPQEGMVAAQHSLTFAANGWVEPATAPNFGPLKVFYPGPGHTSDNITVGIDGTDIAFGGCLIKDSKAKSLGNLGDADTEHYAASVRAFGAAFPKASMIVMSHSAPDSRAAITHTARMADKLR',
 'HMD_1754': 'MMKKSLCCALLLGISCSALATPVSEKQLAEVVANTVTPLMKAQSVPGMAVAVIYQGKPHYYTFGKADIAANKPVTPQTLFELGSISKTFTGVLGGDAIARGEISLDDPVTRYWPQLTGKQWQGIRMLDLATYTAGGLPLQVPDEVTDNASLLRFYQNWQPQWKPGTTRLYANASIGLFGALAVKPSGMPYEQAMTTRVLKPLKLDHTWINVPKAEEAHYAWGYRDGKAVRVSPGMLDAQAYGVKTNVQDMANWVMANMAPENVADASLKQGIALAQSRYWRIGSMYQGLGWEMLNWPVEANTVVEGSDSKVALAPLPVVEVNPPAPPVKASWVHKTGSTGGFGSYVAFIPEKQIGIVMLANTSYPNPARVEAAYYILEALQ',
 'HMD_1175': 'MNVRKHKASFFSVVITFLCLTLSLNANATDSVLEAVTNAETELGARIGLAVHDLETGKRWEHKSNERFPLSSTFKTLACANVLQRVDLGKERIDRVVRFSESNLVTYSPVTEKHVGKKGMSLAELCQATLSTSDNSAANFILQAIGGPKALTKFLRSIGDDTTRLDRWETELNEAVPGDKRDTTTPIAMVTTLEKLLIDETLSIKSRQQLESWLKGNEVGDALFRKGVPSDWIVADRTGAGGYGSRAITAVMWPPNRKPIVAALYITETDASFEERNAVIAKIGEQIAKTVLMENSRN',
 'HMD_1580': 'MTKKMNKYNGKKLSRGEPPNFSGQHFMHNKRLLKEIVDKADVSVRDTVLELGAGKGALTTILSERADRVLAVEYDQKCIEALQWKLVGSKNVSILHQDIMKVALPTEPFVVVSNIPYSITTAIMKMLLNNPKNKLQRGAIVMEKGAAKRFTSVSPKDAYVMAWHMWFDIHYERGISRSSFSPPPKVDSALVRIVRKQHPLFPYKEAKAMHDFLSYALNNPRAPLDQVLRGIFTAPQAKKVRQAIGVKPETPVAMLHARQWAMVCDAMVRHVPKVYWPRRKR',
 'HMD_613': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERETTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
 'MEGARES_2430': 'MNVQNCMVKAVSVSIILFASLSLAAQKVKEPTVSNADWSKPYRPFRIAGNLYYIGTYDLACYLITTKQGNIIVNTGLAASALQIKNNIKALGFKLTDTKILLTTQAHYDHLGAMAEIKKITGAKLMADEGDATVMADGGSSDYAFGGHGSMFEPIIADRLLHDKDTIQLGDTKLVMLHHPGHTKGSCSFLFDTKDEQRSYRILIANMPTIVIEKKFSEVSSYPGIAKDYAYTLQAMKNLSFDIWVASHASQFSMHSKHKPGDGYNPKSFMDRKGYDESLDKLQKEYEKHLNEN',
 'HMD_565': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGASKRGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
 'HMD_558': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMGDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAE',
 'HMD_306': 'MSLYRRLVLLSCLSWPLAGFSATALTNLVAEPFAKLEQDFGGSIGVYAMDTGSGATVSYRAEERFPLCSSFKGFLAAAVLARSQQQAGLLDTPIRYGKNALVRWSPISEKYLTTGMTVAELSAAAVQYSDNAAANLLLKELGGPAGLTAFMRSIGDTTFRLDRWELELNSAIPGDARDTSSPRAVTESLQKLTLGSALAAPQRQQFVDWLKGNTTGNHRIRAAVPADWAVGDKTGTCGVYGTANDYAVVWPTGRAPIVLAVYTRAPNKDDKYSEAVIAAAARLALEGLGVNGQ',
 'HMD_1114': 'MKTLQSGLIALITTFGSACTTISPSVETAKNQQQQSAQQQIQQAFDQLQTTGVIVVKDKHSLHSYGNDLSRAQTPYIPASTFKMLNALIGLEHGKATSTEVFKWDGQKRSFPTWEKDMTLGQAMQASAVPVYQELARRIGLDLMKKEVQRIGYGNQQIGTVVDNFWLVGPLQITPVQEVLFVEKLANTQLAFKPDVQHAVQDMLLIEQKPNYKLYAKSGWGMDLEPQVGWWAGWVETSTGEKVYFALNMHMKTGISASVREQLVKQSLTALGII',
 'HMD_340': 'MKKLFVLCVCFLCSITAAGARLPDLKIEKLEEGVYVHTSFEEVNGWGVVSKHGLVVLVNTDAYLIDTPFTATDTEKLVNWFVERGYKIKGTISSHFHSDSTGGIEWLNSQSIPTYASELTNELLKKDGKVQAKNSFSGVSYWLVKNKIEVFYPGPGHTQDNVVVWLPEKKILFGGCFVKPDGLGNLGDANLEAWPKSAKILMSKYVKAKLVVSSHSEIGDASLLKRTWEQAVKGLNESKKPSQPSN',
 'HMD_688': 'MQQRQSILWGAVATLMWAGLAHAGEASPVDPLRPVVDASIQPLLKEHRIPGMAVAVLKDGKAHYFNYGVANRESGAGVSEQTLFEIGSVSKTLTATLGAYAVVKGAMQLDDKASRHAPWLKGSAFDSITMGELATYSAGGLPLQFPEEVDSSEKMRAYYRQWAPVYSPGSHRQYSNPSIGLFGHLAASSLKQPFAPLMEQTLLPGLGMHHTYVNVPKQAMASYAYGYSKEDKPIRVNPGMLADEAYGIKTSSADLLRFVKANIGGVDDKALQQAISLTHQGHYSVGGMTQGLGWESYAYPVTEQTLLAGNSAKVILEANPTAAPRESGSQVLFNKTGSTNGFGAYVAFVPARGIGIVMLANRNYPNEARIKAAHAILAQLAG',
 'HMD_1755': 'MYKKALIVATSILFLSACSSNTVKQHQIHSISANKNSEAIKSLFDQAQTTGVLVIKRGQTEEIYGNDLKRASTAYVPASTFKMLNALIGLEHHKAITTEVFKWDGQKRLFPDWEKDMTLGDAMKASAIPVYQELARRIGLDLMSKEVKRIGFGNANIGSKVDDFWLVGPLKITPQQETQFAYQLAHKMLPFSKDVQEQVQSMVFIEEKNGRKIYAKSGWGWDIEPQVGWLTGWVVQPQGEIVAFSLNLEMKKGTPSSIRKEIAYKGLEQLGIL',
 'HMD_202': 'MMKKSVCCALLLSTSCSVLAAPMSEKQLAEVVERTVTPLMKAQAIPGIAVAVIYQGQPHYFTFGKADVAANKPVTPQTLFELGSISKTFTGVLGGDAIARGEISLGDPVTKYWPELTGKQWKGIRMLDLATYTAGGLPLQVPDEVTDNASLLRFYQNWQPQWKPGTTRLYANASIGLFGALAVKPSGMSYEQAITTRVFKPLKLDHTWINVPKTEEAHYAWGYRDGKAVHVSPGMLDAEAYGVKTNVKDMASWVMVNMKPDSLEDSSLRKGFTLAQSRYWRVGAMYQGLGWEMLNWPVDAKTVVEGSDNKVALAPLPAREVNPPAPPVNASWVHKTGSTGGFGSYVAFIPEKQLGIVMLANKSYPNPARVEAAYRILDALQ',
 'HMD_1756': 'MNIKALLLITSAIFISACSPYIVTANPNHSASKSDDKAEKIKNLFNEAHTTGVLVIHQGQTQQSYGNDLARASTEYVPASTFKMLNALIGLEHHKATTTEVFKWDGEKRLFPEWEKNMTLGDAMKASAIPVYQDLARRIGLELMSKEVKRVGYGNADIGTQVDNFWLVGPLKITPQQEAQFAYKLANKTLPFSQKVQDEVQSMLFIEEKNGNKIYAKSGWGWDVNPQVGWLTGWVVKPQGNIVAFSLNLEMKKGIPSSVRKEITYKSLEQLGIL',
 'HMD_1491': 'MKTMIYPHQYNYIRSVILRLKNVYKTVNDKETVKVIQSETYNDINEIFGHIDDDIEESLKVLMNIRLSNKEIEAILNKFLEYVVPFELPSPQKLQKVFKKVKKIKIPQFEEYDLKVSSFVGWNELASNRKYIIYYDEKKQLKGLYGEISNQVVKGFCTICNKESNVSLFMKKSKTNSDGQYVKKGDYICRDSIHCNKQLTDINQFYNFIDKLD',
 'HMD_1367': 'MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDERFPMCSTSKVMAAAAVLKQSETQKQLLNQPVEIKPADLVNYNPITEKHVNGTMTLAELSAAALQYSDNTAMNKLIAQLGGPGGVTAFARAIGDETFRLDRTEPTLNTAIPGDPRDTTTPRAMAQTLRQLTLGHALGETQRAQLVTWLKGNTTGAASIRAGLPTSWTVGDKTGSGGYGTTNDIAVIWPQGRAPLVLVTYFTQPQQNAESRRDVLASAARIIAEGL',
 'HMD_1198': 'MKIVKRILLVLLSLFFTVVYSNAQTDNLTLKIENVLKAKNARIGVAIFNSNEKDTFKINNDFHFPMQSVMKFPIALAVLSEIDKGNLSFEQKIEITPQDLLPKTWSPIKEEFPNGTTLTIEQILNYTVSESDNIGCDILLKLIGGTDSVQKFLNANHFTDISIKANEEQMHKDWNTQYQNWATPTAMNKLLIDTYNNKNQLLSKKSYDFIWKIMRETTTGSNRLKGQLPKNTIVAHKTGTSGINNGIAAATNDVGVITLPNGQLIFISVFVAESKETSEINEKIISDIAKITWNYYLNK',
 'HMD_1606': 'MKNNNVTEKELFYILDLFEHMKVTYWLDGGWGVDVLTGKQQREHRDIDIDFDAQHTQKVIQKLEDIGYKIEVHWMPSRMELKHEEYGYLDIHPINLNDDGSITQANPEGGNYVFQNDWFSETNYKDRKIPCISKEAQLLFHSGYDLTETDHFDIKNLKSIT',
 'HMD_979': 'MRGKHTVILGAALSALFAGAAGAQMLECTLVADAASGQELYRKGACDKAFAPMSTFKVPLAVMGYDAGILVDAHNPRWDYKPEFNGYKFQQKTTDPTIWEKDSIVWYSQQLTRKMGQKRFAAYVAGFGYGNGDISGEPGKSNGLTHSWLGSSLKISPEGQVRFVRDLLSAKLPASKDAQQMTVSILPHFAAGDWAVQGKTGTGSFIDARGAKAPLGWFIGWATHEERRVVFARMTAGGKKGEQPAGPAARDAFLKALPDLAKRF',
 'HMD_1758': 'MAIRIFAILFSIFSLATFAHAQEGTLERSDWRKFFSEFQAKGTIVVADERQADRAMLVFDPVRSKKRYSPASTFKIPHTLFALDAGAVRDEFQIFRWDGVNRGFAGHNQDQDLRSAMRNSTVWVYELFAKEIGDDKARRYLKKIDYGNADPSTSNGDYRIEGSLAISAQEQIAFLRKLYRNELPFRVEHQRLVKDLMIVEAGRNWILRAKTGWEGRMGWWVGWVEWPTGSVFFALNIDTPNRMDDLFKREAIVRAILRSIEALPPNPAVNSDAAR',
 'HMD_1759': 'MVKKSLRQFTLMATATVTLLLGSVPLYAQTADVQQKLAELERQSGGRLGVALINTADNSQILYRADERFAMCSTSKVMAAAAVLKKSESEPNLLNQRVEIKKSDLVNYNPIAEKHVNGTMSLAELSAAALQYSDNVAMNKLIAHVGGPASVTAFARQLGDETFRLDRTAPTLNTAIPGDPRDTTSPRAMAQTLRNLTLGKALGDSQRAQLVTWMKGNTTGAASIQAGLPASWVVGDKTGSGGYGTTNDIAVIWPKDRAPLILVTYFTQPQPKAESRRDVLASGAKIVTDGL',
 'HMD_1760': 'MKKSLSATLISALLAFSAPGFSAADNVAAVVDSTIKPLMAQQDIPGMAVAVSVKGKPYYFNYGFADIQAKQPVTENTLFELGSVSKTFTGVLGAVSVAKKEMALNDPAAKYQPELALPQWKGITLLDLATYTAGGLPLQVPDAVKSRADLLNFYQQWQPSRKPGYMRLYANSSIGLFGALTANAAGMPYEQLLTARILAPLGLSHTFITVPESAQSQYAYGYKNKKPVRVSPGQLDAESYGVKSASKDMLRWAEMNMEPSRAGNADLEMAMYLAQTRYYKTAAINQGLGWEMYDWPQQKDMIINGVTNEVALQPHPVTDNQVQPYNRASWVHKTGATTGFGAYVAFIPEKQVAIVILANKNYPNTERVKAAQAILSALE',
 'HMD_1625': 'MSLIIKARNIRLDYAGRDVLDIDELEIHSYDRIGLVGDNGAGKSSLLKVLNGEIVLAEATLQRFGDFAHISQLGGIEIETVEDRAMLSRLGVSNVQNDTMSGGEETRAKIAAAFSQQVHGILADEPTSHLDLNGIDLLIGQLKAFDGALLVISHDRYFLDMVVDKIWELKDGKITEYWGGYSDYLRQKEEERQHQAVEYELMMKERERLESAVQEKRQQANRLDNKKKGEKSKNSTESAGRLGHAKMTGTKQRKLYQAAKSMEKRLAALEDIQAPEHLRSIRFRQSSALELHNKFPITADGLSLKFGSRTIFDDANFIIPLGAKVAITGSNGTGKTSLLKMISERADGLTISPKAEIGYFTQTGYKFNTHKSVLSFMQEECEYTVAEIRAVLASMGIGANDIQKNLSDLSGGEIIKLLLSKMLLGKYNILLMDEPGNYLDLKSIAALETMMKSYAGTIIFVSHDKQLVDNIADIIYEIKDHKIIKTFERDC',
 'HMD_944': 'MLKSSWRKSALMAAAAVPLLLASGSLWASADAIQQKLADLEKRSGGRLGVALINTTDDSQTLYRGDERFAMCSTGKVMAAAAVLKQSESHPDVVNKRLEIKKSDLVVWSPITEKHLQSGMTLAELSAAALQYSDNTAMNKMISYLGGPEKVTAFAQSIGDVTFRLDRTEPALNSAIPGDKRDTTTPLAMAESLRKLTLGNALGEQQRAQLVTWLKGNTTGGQSIRAGLPASWAVGDKTGAGDYGTTNDIAVIWPENHAPLVLVTYFTQPQQDAKSRKEVLAAAAKIVTEGL',
 'HMD_1489': 'MLQSLNHLTLAVSDLQKSVTFWHELLGLTLHARWNTGAYLTCGDLWVCLSYDEARGYVPPQESDYTHYAFTVAAEDFEPFSHKLEQAGVTVWKQNKSEGASFYFLDPDGHKLELHVGSLAARLAACREKPYAGMVFTSDEA',
 'HMD_1761': 'MDDSTLRRKYPHHEWHAVNEGDSGAFVYQLTGGPEPQPELYAKIAPRAPENSAFDLSGEADRLEWLHRHGIPVPRVVERGADDTAAWLVTEAVPGVAAAEEWPEHQRFAVVEAMAELARALHELPVEDCPSDRRLDAAVAEARRNVAEGLVDLDDLQEERAGWTGDQLLAELDRTRPEKEDLVVCHGDLCPNNVLLDPGTCRVTGVIDVGRLGVADRHADIALAARELEIDEDPWFGPAYAERFLERYGAHRVDKEKLAFYQLLDEFF',
 'HMD_1762': 'MGIIRTCRLGPDQVKSMRAALDLFGREFGDVATYSQHQPDSDYLGNLLRSKTFIALAAFDQEAVVGALAAYVLPRFEQPRSEIYIYDLAVSGEHRRQGIATALINLLKHEANALGAYVIYVQADYGDDPAVALYTKLGIREEVMHFDIDPSTAT',
 'HMD_1763': 'MTPLLYKKTGTNMALALVGEKIDRNRFTGEKIDNSTFFNCDFSGADLSGTEFIGCQFYDRESQKGCNFSRAMLKDAIFKSCDLSMADFRNASALGIEIRHCRAQGADFRGASFMNMITTRTWFCSAYITNTNLSYANFSKVVLEKCELWENRWMGAQVLGATFSGSDLSGGEFSTFDWRAANFTHCDLTNSELGDLDIRGVDLQGVKLDNYQASLLMERLGIAIIG',
 'HMD_165': 'MTIEQAAADILSSKKYQLLCPDTVVRILTQEWGRHKKPKQAVERTRERLHGICGAYLAPQVEKQASTALAAGDVQKALALHASTRERLDTYPQLYQFVFENNLPARVLDIACGLNPLMLHRQGVASVWGCDIHQGLGNVLTPYAQKHGWDFTFALHDVLCAPVAASGDMALVFKLLPLLEREQPGAALALLRTLDAPVICVSFPTRSLGGRGKGMHQHYATWFEGLVAPHFTVQHHTLIGDELLYRIQPNPA',
 'HMD_943': 'MLKSSWRKSALMAAAAVPLLLASGSLWASADAIQQKLADLEKRSGGRLGVALINTADDSQTLYRGDERFAMCSTGKVMAAAAVLKQSESHPDVVNKRLEIKKSDLVVWSPITEKHLQSGMTLAELSAAALQYSDNTAMNKMISYLGGPEKVTAFAQSIGDVTFRLDRTEPALNSAIPGDKRDTTTPLAMAESLRKLTLGNALGEQQRAQLVTWLKGNTTGGQSIRAGLPASWAVGDKTGAGDYGTTNDIAVIWPENHAPLVLVTYFTQPQQDAKSRKEVLAAAAKIVTEGL',
 'HMD_1764': 'MNIGKAAKASKVSAKMIRYYEQIGLIPAASRTDSGYRAYTQADVNQLHFIRRARDLGFSVAEISDLLNLWNNQSRQSADVKRLAQTHIDELDRRIQNMQHMAQTLKALIHCCAGDALPDCPILHTLGQPDDSEPEARTGAVLRRPRRHGLAKRL',
 'HMD_1765': 'MINRQLSRLLLCSILGSTTLISGCALVRKDSAPHQQLKPEQIKLADDIHLASSGWPQAQWWKQLNDPQLDALIQRTLSGSHTLAEAKLREEKAQSQADLLDAGSQLQVAALGMLNRQRVSANGFLSPYSMDAPALGMDGPYYTEATVGLFAGLDLDLWGVHRSAVAAAIGAHNAALAETAAVELSLATGVAQLYYSMQASYQMLDLLEQTHDVIDYAVKAHQSKVAHGLEAQVPFHGARAQILAVDKQIVAVKGQITETRESLRALIGAGASDMPEIRPVALPQVQTGIPATLSYELLARRPDLQAMRWYVQASLDQVDSARALFYPSFDIKAFFGLDSIHLHTLFKKTSRQFNFIPGLKLPLFDGGRLNANLEGTRAASNMMIERYNQSVLNAVRDVAVNGTRLQTLNDEREMQAERVEATRFTQRAAEAAYQRGLTSRLQATEARLPVLAEEMSLLMLDSRRVIQSIQLMKSLGGGYQAGPVVEKK',
 'HMD_778': 'MMKKSLCCALLLTASFSTFAAAKTEQQIADIVNRTITPLMQEQAIPGMAVAIIYEGKPYYFTWGKADIANNHPVTQQTLFELGSVSKTFNGVLGGDAIARGEIKLSDPVTKYWPELTGKQWRGISLLHLATYTAGGLPLQIPDYVTDKAELLRFYQNWQPQWTPGAKRLYANSSIGLFGALVVKPSGMSYEEAMTRRVLQPLKLAHTWITVPQSEQKNYAWGYREGKPVHVSPGQLDAEAYGVKSSVIDMARWVQANMDASHVQEKTLQQGIELAQSRYWRIGDMYQGLGWEMLNWPLKADSIINGSDSKVALAALPAVEVNPPAPAVKASWVHKTGSTGGFGSYVAFVPEKNLGIVMLANKSYPNPARVEAAWRILEKLQ',
 'HMD_1766': 'MLSRYSKTLAFAVVACTLAISTATAHAELVVRNDLKRVFDDAGVSGTFVLMDITADRTYVVDPARAARSIHPASTFKIPNSLIAFDTGAVRDDQEVLPYGGKPQPYEQWEHDMALPEAIRLSAVPIYQEVARRVGFERMQAYVDAFDYGNRQLGSAIDQFWLRGPLEISAFEEARFTSRMALKQLPVKPRTWDMVQRMLLIEQQGDAALYAKTGVATEYQPEIGWWAGWVERAGHVYAFALNIDMPREGDMAKRIPLGKQLMRALEVWPAP',
 'HMD_1022': 'MNIKALLLITSAIFISACSPYIVTANPNHSASKSDEKAEKIKNLFNEAHTTGVLVIQQGQTQQSYGNDLARASTEYVPASTFKMLNALIGLEHHKATTTEVFKWDGKKRLFPEWEKDMTLGDAMKASAIPVYQDLARRIGLELMSKEVKRVGYGNADIGTQVDNFWLVGPLKITPQQEAQFAYKLANKTLPFSQKVQDEVQSMLFIEEKNGNKIYAKSGWGWDVDPQVGWLTGWVVQPQGNIVAFSLNLEMKKGIPSSVRKEITYKSLEQLGIL',
 'HMD_789': 'MSNKVNFKTASFLFSVCLALSAFNAHANKSDAAAKQIKKLEEDFDGRIGVFAIDTGSGNTFGYRSDERFPLCSSFKGFLAAAVLERVQQKKLDINQKVKYESRDLEYHSPITTKYKGSGMTLGDMASAALQYSDNGATNIIMERFLGGPEGMTKFMRSIGDNEFRLDRWELELNTAIPGDKRDTSTPKAVANSLNKLALGNVLNAKEKAIYQNWLKGNTTGDARIRASVPADWVVGDKTGSCGAYGTANDYAVIWPKNRAPLIVSIYTTRKSKDDKHSDKTIAEASRIAIQAID',
 'HMD_38': 'MFSRWSKPLVLAAVTRASLAADLAALGLAAGDAVMVHAAVSKVGRLLDGPDTIIAALSDAGRPAGTILAYADWEARYEDLVDEDGRVPQEWREHIPPFDPRRSRAIRDNGVLPEFLRTTPGALRSGNPGASMVGLGARAEWFTADHPLDYGYGEGSPLARLVEAGGKVLMLGAPLDTLTLLHHAEHLADIPGKRIRRIEVPLATPTGTQWRMIEEFDTGDPIVEGLAEDYFAEIVTAFLAGGRGRQGLIGTAPSVLVDAAAITAFGVAWLESRFGSPSS',
 'HMD_932': 'MIKSSWRKIAMLAAAVPLLLASGALWASTDAIHQKLTDLEKRSGGRLGVALINTADNSQILYRGDERFAMCSTSKVMAAAAVLKQSESNKEVVNKRLEINAADLVVWSPITEKHLQSGMTLAELSAATLQYSDNTAMNLIIGYLGGPEKVTAFARSIGDATFRLDRTEPTLNTAIPGDERDTSTPLAMAESLRKLTLGDALGEQQRAQLVTWLKGNTTGGQSIRAGLPESWVVGDKTGAGDYGTTNDIAVIWPEDHAPLILVTYFTQPQQDAKNRKEVLAAAAKIVTEGL',
 'HMD_270': 'MQQRQSILWGALATLMWAGLAHAGDKAATDPLRPVVDASIRPLLKEHRIPGMAVAVLKDGKAHYFNYGVADRERAVGVSEQTLFEIGSVSKTLTATLGAYAVVQGGFELDDKASLFAPWLKGSAFDNITMGELATYSAGGLPLQFPEEVDSLEKMQAYYRQWTPAYSRGSHRQYANPSIGLFGYLAASSMKQPFDRLMEQTMLPGLGLYHTYLNVPEQPMGHYAYGYWKEDKPFRVTPAMLAEEPYGIKTSSADLLRFVKANISGVDNAAMQQAIDLTHQGQYAVGEMTQGLGWERYPYPVSEQTLLAGNSPAMIYNANPAAPAPAAAGHPVLFKKTGSTNGFGAYVAFVPAKGIGVVMLANRNYPNEGTLKAGHAILTQLAR',
 'HMD_547': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMVSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
 'HMD_1002': 'MNIKALLLITSAIFISACSPYIVTANPNHSASKSDDKAEKIKNLFNEAHTTGVLVIHQGQTQQSYGNDLARASTEYVPASTFKMLNALIGLEHHKATTTEVFKWDGEKRLFPEWEKNMTLGDAMKASAIPVYQDLARRIGLELMSKEVKRVGYGNADIGTQVDNFWLVGPLKITPQQEAQFAYKLANKTLPFSQKVQDEVQSMLFIEEKNGNKIYAKSGWGWDVNPQVGWLTGWVVQPQGNIVAFSLNLEMKKGIPSSVRKEITYKSLEQLGIL',
 'HMD_530': 'FFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDSWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNR',
 'HMD_804': 'MRYIRLCIISLLATLPLAVHASPQPLEQIKLSESQLSGRVGMIEMDLASGRTLTAWRADERFPMMSTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLATVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARGTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR',
 'HMD_1767': 'MTLALVGEKIDRNRFTGEKVENSTFFNCDFSGADLSGTEFIGCQFYDRESQKGCNFSRAMLRDAIFKSCDLSMADFRNVSALGIEIRHCRAQGADFRGASFMNMITTRTWFCSAYITNTNLSYANFSKVVLEKCELWENRWMGTQVLGATFSGSDLSGGEFSTFDWRAANFTHCDLTNSELGDLDIRGVDLQGVKLDNYQASLLMERLGIAVIG',
 'HMD_1143': 'MKTFAAYVIIACLSSTALAGSITENTSWNKEFSAEAVNGVFVLCKSSSKSCATNDLARASKEYLPASTFKIPDAIIGLETGVIKNEHQVFKWDGKPRAMKQWERDLTLRGAIQVSAVPVFQQIAREVGEVRMQKYLKKFSYGNQNISGGIDKFWLEGQLRISAVNQVEFLESLYLNKLSASKENQLIVKEALVTEAAPEYLVHSKTGFSGVGTESNPGVAWWVGWVEKETEVYFFAFNMDIDNESKLPLRKSIPTKIMESEGIIGG',
 'HMD_1768': 'METYRHTYRHHSFSHQDLSDITFTACTFIRCDFRRANLRDATFINCKFIEQGDIEGCHFDVADLRDASFQQCQLAMANFSNANCYGIELRECDLKGANFSRANFANQVSNRMYFCSAFITGCNLSYANMERVCLEKCELYENRWIGTHLAGASLKESDLSRGVFSEDVWGQFSLQGANLCHAELDGLDPRKVDTSGIKIASWQQEQLLEALGIVVFPD',
 'HMD_1769': 'MYKKALIVATSILFLSACSSNLVKQHQIHSISANKSSEEIKSLFDQAQTTGVLVIKRGQTEEIYGNDLKRASTAYVPASTFKMLNALIGLEHHKATTTEVFKWNGQKRLFPDWEKDMTLGDAMKASAIPVYQELARRIGLDLMSKEVKRIGFGNANIGSKVDNFWLVGPLKITPQQETQFAYQLAHKTLPFSKNVQEQVQSMVFIEKKNGSKIYAKSGWGWDVEPQVGWLTGWVVQPQGEIVAFSLNLEMKKGTSSSIRKEIAYKGLEQLGIL',
 'HMD_728': 'MMKKSLCCALLLTASFSTFAAAKTEQQIADIVNRTITPLMQEQAIPGMAVAVIYQGKPYYFTWGKADIANNHPVTQQTLFELGSVSKTFNGVLGGDAIARGEIKLSDPVTKYWPELTGKQWQGIRLLHLATYTAGGLPLQIPDDVRDKAALLHFYQNWQPQWTPGAKRLYANSSIGLFGALAVKPSGMSYEEAMTRRVLQPLKLAHTWITVPQNEQKDYAWGYREGKPVHSSPGQLDAEAYGVKSSVIDMARWVQANMDASHVQEKTLQQGIALAQSRYWRIGDMYQGLGWEMLNWPLKADSIINGSDSKVALAALPAVEVNPPAPAVKASWVHKTGSTGGFGSYVAFVPEKNLGIVMLANKSYPNPVRVEAAWRILEKLQ',
 'HMD_1770': 'MTNSNDSVTLRLMTEHDLAMLYEWLNRSHIVEWWGGEEARPTLADVQEQYLPSVLAQESVTPYIAMLNGEPIGYAQSYVALGSGDGWWEEETDPGVRGIDQSLANASQLGKGLGTKLVRALVELLFNDPEVTKIQTDPSPSNLRAIRCYEKAGFEKQGTVTTPDGPAVYMVQTRQAFERTRSDA',
 'HMD_753': 'MMKKSICCALLLTASFSTFAAAKTEQQIADIVNRTITPLMQEQAIPGMAVAIIYQGKPYYFTWGKADIANNRPVTQQTLFELGSVSKTFNGVLGGDAIARGEIKLSDPVTQYWPELTGKQWQGISLLHLATYTAGGLPLQVPDDVTDKAALLRFYQNWQPQWAPGAKRLYANSSIGLFGALAVKPSGMSYEEAMSKRVLHPLKLAHTWITVPQSEQKDYAWGYREGKPVHVSPGQLDAEAYGVKSSVIDMTRWVQANMDASQVQEKTLQQGIELAQSRYWRIGDMYQGLGWEMLNWPVKADSIISGSDSKVALAALPAVEVNPPAPAVKASWVHKTGSTGGFGSYVAFVPEKNLGIVMLANKSYPNPVRVEAAWRILEKLQ',
 'HMD_428': 'MRFIHALLLAGIAHSAYASEKLTFKTDLEKLEREKAAQIGVAIVDPQGEIVAGHRMAQRFAMCSTFKFPLAALVLERIDSGTERGDRKLSYGPDMIVEWSPATERFLASGHMTVLEAAQAAVQLSDNGATNLLLREIGGPAAMTQYFRKIGDSVSRLDRKEPEMSDNTPGDLRDTTTPIAMARTVAKVLYGGALTSTSTHTIERWLIGNQTGDATLRAGFPKDWVVGEKTGTCANGGRNDIGFFKAQERDYAVAVYTTAPKLSAVERDELVASVGQVITQLILSTDK',
 'HMD_819': 'MRYIRLCIISLLATLPLAVHASPQPLEQIKLSESQLSGRVGMIEMDLASGRTLTAWRADERFPMMSTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLATFGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARDTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR',
 'HMD_1771': 'MNIKALLLITSAIFISACSPYIVTANPNHSASKSDKKAEKIKNLFNEVHTTGVLVIQQGQTQQSYGNDLARASTEYVPASTFKMLNALIGLEHHKATTTEVFKWNGQKRLFPEWEKDMTLGDAMKASAIPVYQDLARRIGLELMSNEVKRVGYGNADIGTQVDNFWLVGPLKITPQQEAQFAYKLANKTLPFSQKVQDEVQSMLFIEEKNGNKIYAKSGWGWDVDPQVGWLTGWVVQPQGNIVAFSLNLEMKKGIPSSVRKEITYKSLEQLGIL',
 'HMD_619': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDHWEPELNEAVPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGKRGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
 'HMD_1772': 'MTIEISNQLSEVLSVIERHLESTLLAVHLYGSAVDGGLKPYSDIDLLVTVTVRLDETTRRALINDLLETSASPGESEILRAVEVTIVVHDDIIPWRYPAKRELQFGEWQRNDILAGIFEPATIDIDLAILLTKAREHSVALVGPAAEELFDPVPEQDLFEALNETLTLWNSPPDWAGDERNVVLTLSRIWYSAVTGKIAPKDVAADWAMERLPAQYQPVILEARQAYLGQEEDRLASRADQLEEFVHYVKGEITKVVGK',
 'HMD_251': 'MELPNIMHPVAKLSTALAAALMLSGCMPGEISPTIDQQMETGDQRFGDLVFRQLAPNVWQHTSYLDMPSFGAVTSNGLIVRDGGRVLVVDTAWTDDQTAQILNWIKQEINLPVALAVVTHAHQDKMGGMDALHAAGIATYANALSNQLAPQEGMVAAQHSLTFAANGWVEPATAPNFGPLKVFYPGPGHTSDNITVGIDRTDIAFGGCLIKDSKAKSLGNLGDADTEHYAASARAFGAAFPKASMIVMSHSAPDSRAAITHTARMADKLR',
 'HMD_1773': 'MALALVGEKINRNRFTGEKIENSTFFNCDFSGADLSGTEFIGCQFYDRESQKGCNFSRAMLKDAIFKSCDLSMADFRNSSALGIEIRHCRAQGADFRGASFMNMITTRTWFCSAYITNTNLSYANFSKVVLEKCELWENRWMGAQVLGATFSGSDLSGGEFSTFDWRAANFTHCDLTNSELGDLDIRGVDLQGVKLDNYQASLLMERLGIAVIG',
 'HMD_820': 'MRYIRLCIISLLATLPLAVHSSPQPLEQIKLSESQLSGRVGMIEMDLASGRTLTAWRADERFPMMSTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITVSDNSAANLLLATVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARDTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR',
 'HMD_975': 'MKTFAAYVITACLSSTALASSITENTSWNKEFSAEAVNGVFVLCKSSSKSCATNNLARASKEYLPASTFKIPNAIIGLETGVIKNEHQVFKWDGKPRAMKQWERDLSLRGAIQVSAVPVFQQIAREVGEVRMQKYLKKFSYGNQNISGGIDKFWLEGQLRISAVNQVEFLESLFLNKLSASKENQLIVKEALVTEAAPEYLVHSKTGFSGVGTESNPGVAWWVGWVEKGTEVYFFAFNMDIDNENKLPLRKSIPTKIMASEGIIGG',
 'HMD_803': 'MRYFRLCIISLLATLPLAVHASPQPLEQIKLSESQLSGSVGMIEMDLASGRTLTAWRADERFPMMSTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLATVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARDTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAAKRGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR',
 'HMD_1774': 'MLNKGIRTRRARGALAGGTVLTAAAALLTAVPAAQAISGEPPAATDHAFTARLHIGEGDTLRGCSAALVHQQWLLTATSCFAATPGGEVKSGKPALKSTATLGGKTLGIVEVVPRDDRDVAMVRLAEPVTTVEPVRLAADAPVAAETLLGAGFGRTRTEWAPDQLHTGEFRVDSVTGTTVELTGQDGVSVCKGDTGGPALRGTGGEVELAAVHSRSWQGGCFGETETRTGAVDARADGLADWVTDVRNRDRTQSADVDGDGRADLVVLRSNGDVVVHRNLGDSFAAGRVMSGGWGLFVTWKDLGRLYFADVDGDRKADMIVHTSDGNIEVRFNHGTYWDQGTHWSGGWGRFIDGSDLGRLYFADVDGDGRADMIVHTGDGNVEVRFNHGTYWDQGTHWSGGWGRFVTWKDLGRLYFADVDGDGRADMIVHTGDGNVEVRFNHGTYWDQGTHWSGGWGRFVDGSDLGSLEFGDATGDGKADLLVRTKDGKVALRTNHGTYWDQGKFMITL',

In [15]:
def MergeSequences(base, override1, override2):
    for key, value in base.items():
        try:     
            base[key].update({"Sequence": override1[key]})
            try:
                base[key].update({"Sequence": override2[key]})
            except:
                pass
        except:
            pass
    return base

In [16]:
MergeSequences(MetaDict, PairWiseDictSource, PairWiseDictTarget)

{'CARD_0': {'Drug Class': 'cephalosporin',
  'Name': 'CblA-1',
  'Sequence': 'MKAYFIAILTLFTCIATVVRAQQMSELENRIDSLLNGKKATVGIAVWTDKGDMLRYNDHVHFPLLSVFKFHVALAVLDKMDKQSISLDSIVSIKASQMPPNTYSPLRKKFPDQDFTITLRELMQYSISQSDNNACDILIEYAGGIKHINDYIHRLSIDSFNLSETEDGMHSSFEAVYRNWSTPSAMVRLLRTADEKELFSNKELKDFLWQTMIDTETGANKLKGMLPAKTVVGHKTGSSDRNADGMKTADNDAGLVILPDGRKYYIAAFVMDSYETDEDNANIIARISRMVYDAMR'},
 'CARD_1': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-52',
  'Sequence': 'MRYIRLCIISLLAALPLAVHASPQPLEQIKQSESQLSGRVGMIEMDLASGRTLTAWRADERFPMISTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLAIVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARDTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR'},
 'CARD_2': {'Drug Class': 'diaminopyrimidine antibiotic',
  'Name': 'dfrF',
  'Sequence': 'MIGLIVARSKNNVIGKNGNIPWKIKGEQKQFRELTTGNVVIMGRKSYEEIGHPLPNRMNIVVSTTTEYQGDNLVSVKSLEDALLLAKGRDVYISGGYGLFKEALQIVDKMYITEVDLNIEDGDTFFPEFDINDFEVLIGETLGEEVKYTRTFYVRKNELSRFWI'},
 'CARD_3': {'Drug Class': 'cephalosporin',
  'Name': 'CTX-M-130',
  'Sequence': 'MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDERFPMCSTSKVMAAAAVLKQSETQKQLLNQPVEIKPADLVNYNPIAEKHVNGTMTLAELSAAALQYSDNTAMNKLIAQLGGPGGVTAFARAIGDETFRLDRTEPTLNTAIPGDPRDTTTPRAMAQTLRQLTLGHALGETQRAQLVTWLKGNTTGAASIRAGLPTSWTVGDKTGSGDYGTTNDIAVIWPQGRAPLVLVTYFTQPQQNAERRHDVLASAARIIAEGL'},
 'CARD_4': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'NDM-6',
  'Sequence': 'MELPNIMHPVAKLSTALAAALMLSGCMPGEIRPTIGQQMETGDQRFGDLVFRQLAPNVWQHTSYLDMPGFGAVASNGLIVRDGGRVLVVDTAWTDDQTAQILNWIKQEINLPVALAVVTHAHQDKMGGMDALHAAGIATYANALSNQLAPQEGMVAAQHSLTFAANGWVEPATAPNFGPLKVFYPGPGHTSDNITVGIDGTDIAFGGCLIKDSKAKSLGNLGDADTEHYAASVRAFGAAFPKASMIVMSHSAPDSRAAITHTARMADKLR'},
 'CARD_5': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'ACT-35',
  'Sequence': 'MMKKSLCCALLLGISCSALATPVSEKQLAEVVANTVTPLMKAQSVPGMAVAVIYQGKPHYYTFGKADIAANKPVTPQTLFELGSISKTFTGVLGGDAIARGEISLDDPVTRYWPQLTGKQWQGIRMLDLATYTAGGLPLQVPDEVTDNASLLRFYQNWQPQWKPGTTRLYANASIGLFGALAVKPSGMPYEQAMTTRVLKPLKLDHTWINVPKAEEAHYAWGYRDGKAVRVSPGMLDAQAYGVKTNVQDMANWVMANMAPENVADASLKQGIALAQSRYWRIGSMYQGLGWEMLNWPVEANTVVEGSDSKVALAPLPVVEVNPPAPPVKASWVHKTGSTGGFGSYVAFIPEKQIGIVMLANTSYPNPARVEAAYYILEALQ'},
 'CARD_6': {'Drug Class': 'penicillin beta-lactam',
  'Name': 'CARB-5',
  'Sequence': 'MNVRKHKASFFSVVITFLCLTLSLNANATDSVLEAVTNAETELGARIGLAVHDLETGKRWEHKSNERFPLSSTFKTLACANVLQRVDLGKERIDRVVRFSESNLVTYSPVTEKHVGKKGMSLAELCQATLSTSDNSAANFILQAIGGPKALTKFLRSIGDDTTRLDRWETELNEAVPGDKRDTTTPIAMVTTLEKLLIDETLSIKSRQQLESWLKGNEVGDALFRKGVPSDWIVADRTGAGGYGSRAITAVMWPPNRKPIVAALYITETDASFEERNAVIAKIGEQIAKTVLMENSRN'},
 'CARD_7': {'Drug Class': 'lincosamide antibiotic;macrolide antibiotic;streptogramin A antibiotic;streptogramin B antibiotic;streptogramin antibiotic',
  'Name': 'Erm(34)',
  'Sequence': 'MTKKMNKYNGKKLSRGEPPNFSGQHFMHNKRLLKEIVDKADVSVRDTVLELGAGKGALTTILSERADRVLAVEYDQKCIEALQWKLVGSKNVSILHQDIMKVALPTEPFVVVSNIPYSITTAIMKMLLNNPKNKLQRGAIVMEKGAAKRFTSVSPKDAYVMAWHMWFDIHYERGISRSSFSPPPKVDSALVRIVRKQHPLFPYKEAKAMHDFLSYALNNPRAPLDQVLRGIFTAPQAKKVRQAIGVKPETPVAMLHARQWAMVCDAMVRHVPKVYWPRRKR'},
 'CARD_8': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-126',
  'Sequence': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERETTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW'},
 'CARD_9': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'LRA-12',
  'Sequence': 'MNVQNCMVKAVSVSIILFASLSLAAQKVKEPTVSNADWSKPYRPFRIAGNLYYIGTYDLACYLITTKQGNIIVNTGLAASALQIKNNIKALGFKLTDTKILLTTQAHYDHLGAMAEIKKITGAKLMADEGDATVMADGGSSDYAFGGHGSMFEPIIADRLLHDKDTIQLGDTKLVMLHHPGHTKGSCSFLFDTKDEQRSYRILIANMPTIVIEKKFSEVSSYPGIAKDYAYTLQAMKNLSFDIWVASHASQFSMHSKHKPGDGYNPKSFMDRKGYDESLDKLQKEYEKHLNEN'},
 'CARD_10': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-72',
  'Sequence': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGASKRGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW'},
 'CARD_11': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-59',
  'Sequence': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMGDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAE'},
 'CARD_12': {'Drug Class': 'carbapenem;cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'KPC-10',
  'Sequence': 'MSLYRRLVLLSCLSWPLAGFSATALTNLVAEPFAKLEQDFGGSIGVYAMDTGSGATVSYRAEERFPLCSSFKGFLAAAVLARSQQQAGLLDTPIRYGKNALVRWSPISEKYLTTGMTVAELSAAAVQYSDNAAANLLLKELGGPAGLTAFMRSIGDTTFRLDRWELELNSAIPGDARDTSSPRAVTESLQKLTLGSALAAPQRQQFVDWLKGNTTGNHRIRAAVPADWAVGDKTGTCGVYGTANDYAVVWPTGRAPIVLAVYTRAPNKDDKYSEAVIAAAARLALEGLGVNGQ'},
 'CARD_13': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-212',
  'Sequence': 'MKTLQSGLIALITTFGSACTTISPSVETAKNQQQQSAQQQIQQAFDQLQTTGVIVVKDKHSLHSYGNDLSRAQTPYIPASTFKMLNALIGLEHGKATSTEVFKWDGQKRSFPTWEKDMTLGQAMQASAVPVYQELARRIGLDLMKKEVQRIGYGNQQIGTVVDNFWLVGPLQITPVQEVLFVEKLANTQLAFKPDVQHAVQDMLLIEQKPNYKLYAKSGWGMDLEPQVGWWAGWVETSTGEKVYFALNMHMKTGISASVREQLVKQSLTALGII'},
 'CARD_14': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'IMP-2',
  'Sequence': 'MKKLFVLCVCFLCSITAAGARLPDLKIEKLEEGVYVHTSFEEVNGWGVVSKHGLVVLVNTDAYLIDTPFTATDTEKLVNWFVERGYKIKGTISSHFHSDSTGGIEWLNSQSIPTYASELTNELLKKDGKVQAKNSFSGVSYWLVKNKIEVFYPGPGHTQDNVVVWLPEKKILFGGCFVKPDGLGNLGDANLEAWPKSAKILMSKYVKAKLVVSSHSEIGDASLLKRTWEQAVKGLNESKKPSQPSN'},
 'CARD_15': {'Drug Class': 'cephalosporin',
  'Name': 'CMY-1',
  'Sequence': 'MQQRQSILWGAVATLMWAGLAHAGEASPVDPLRPVVDASIQPLLKEHRIPGMAVAVLKDGKAHYFNYGVANRESGAGVSEQTLFEIGSVSKTLTATLGAYAVVKGAMQLDDKASRHAPWLKGSAFDSITMGELATYSAGGLPLQFPEEVDSSEKMRAYYRQWAPVYSPGSHRQYSNPSIGLFGHLAASSLKQPFAPLMEQTLLPGLGMHHTYVNVPKQAMASYAYGYSKEDKPIRVNPGMLADEAYGIKTSSADLLRFVKANIGGVDDKALQQAISLTHQGHYSVGGMTQGLGWESYAYPVTEQTLLAGNSAKVILEANPTAAPRESGSQVLFNKTGSTNGFGAYVAFVPARGIGIVMLANRNYPNEARIKAAHAILAQLAG'},
 'CARD_16': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-329',
  'Sequence': 'MYKKALIVATSILFLSACSSNTVKQHQIHSISANKNSEAIKSLFDQAQTTGVLVIKRGQTEEIYGNDLKRASTAYVPASTFKMLNALIGLEHHKAITTEVFKWDGQKRLFPDWEKDMTLGDAMKASAIPVYQELARRIGLDLMSKEVKRIGFGNANIGSKVDDFWLVGPLKITPQQETQFAYQLAHKMLPFSKDVQEQVQSMVFIEEKNGRKIYAKSGWGWDIEPQVGWLTGWVVQPQGEIVAFSLNLEMKKGTPSSIRKEIAYKGLEQLGIL'},
 'CARD_17': {'Drug Class': 'carbapenem;cephalosporin;penicillin beta-lactam',
  'Name': 'ACT-10',
  'Sequence': 'MMKKSVCCALLLSTSCSVLAAPMSEKQLAEVVERTVTPLMKAQAIPGIAVAVIYQGQPHYFTFGKADVAANKPVTPQTLFELGSISKTFTGVLGGDAIARGEISLGDPVTKYWPELTGKQWKGIRMLDLATYTAGGLPLQVPDEVTDNASLLRFYQNWQPQWKPGTTRLYANASIGLFGALAVKPSGMSYEQAITTRVFKPLKLDHTWINVPKTEEAHYAWGYRDGKAVHVSPGMLDAEAYGVKTNVKDMASWVMVNMKPDSLEDSSLRKGFTLAQSRYWRVGAMYQGLGWEMLNWPVDAKTVVEGSDNKVALAPLPAREVNPPAPPVNASWVHKTGSTGGFGSYVAFIPEKQLGIVMLANKSYPNPARVEAAYRILDALQ'},
 'CARD_18': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-371',
  'Sequence': 'MNIKALLLITSAIFISACSPYIVTANPNHSASKSDDKAEKIKNLFNEAHTTGVLVIHQGQTQQSYGNDLARASTEYVPASTFKMLNALIGLEHHKATTTEVFKWDGEKRLFPEWEKNMTLGDAMKASAIPVYQDLARRIGLELMSKEVKRVGYGNADIGTQVDNFWLVGPLKITPQQEAQFAYKLANKTLPFSQKVQDEVQSMLFIEEKNGNKIYAKSGWGWDVNPQVGWLTGWVVKPQGNIVAFSLNLEMKKGIPSSVRKEITYKSLEQLGIL'},
 'CARD_19': {'Drug Class': 'fusidane antibiotic',
  'Name': 'fusB',
  'Sequence': 'MKTMIYPHQYNYIRSVILRLKNVYKTVNDKETVKVIQSETYNDINEIFGHIDDDIEESLKVLMNIRLSNKEIEAILNKFLEYVVPFELPSPQKLQKVFKKVKKIKIPQFEEYDLKVSSFVGWNELASNRKYIIYYDEKKQLKGLYGEISNQVVKGFCTICNKESNVSLFMKKSKTNSDGQYVKKGDYICRDSIHCNKQLTDINQFYNFIDKLD'},
 'CARD_20': {'Drug Class': 'cephalosporin',
  'Name': 'CTX-M-121',
  'Sequence': 'MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDERFPMCSTSKVMAAAAVLKQSETQKQLLNQPVEIKPADLVNYNPITEKHVNGTMTLAELSAAALQYSDNTAMNKLIAQLGGPGGVTAFARAIGDETFRLDRTEPTLNTAIPGDPRDTTTPRAMAQTLRQLTLGHALGETQRAQLVTWLKGNTTGAASIRAGLPTSWTVGDKTGSGGYGTTNDIAVIWPQGRAPLVLVTYFTQPQQNAESRRDVLASAARIIAEGL'},
 'CARD_21': {'Drug Class': 'cephalosporin;monobactam',
  'Name': 'VEB-3',
  'Sequence': 'MKIVKRILLVLLSLFFTVVYSNAQTDNLTLKIENVLKAKNARIGVAIFNSNEKDTFKINNDFHFPMQSVMKFPIALAVLSEIDKGNLSFEQKIEITPQDLLPKTWSPIKEEFPNGTTLTIEQILNYTVSESDNIGCDILLKLIGGTDSVQKFLNANHFTDISIKANEEQMHKDWNTQYQNWATPTAMNKLLIDTYNNKNQLLSKKSYDFIWKIMRETTTGSNRLKGQLPKNTIVAHKTGTSGINNGIAAATNDVGVITLPNGQLIFISVFVAESKETSEINEKIISDIAKITWNYYLNK'},
 'CARD_22': {'Drug Class': 'lincosamide antibiotic',
  'Name': 'lnuA',
  'Sequence': 'MKNNNVTEKELFYILDLFEHMKVTYWLDGGWGVDVLTGKQQREHRDIDIDFDAQHTQKVIQKLEDIGYKIEVHWMPSRMELKHEEYGYLDIHPINLNDDGSITQANPEGGNYVFQNDWFSETNYKDRKIPCISKEAQLLFHSGYDLTETDHFDIKNLKSIT'},
 'CARD_23': {'Drug Class': 'penicillin beta-lactam',
  'Name': 'OXA-45',
  'Sequence': 'MRGKHTVILGAALSALFAGAAGAQMLECTLVADAASGQELYRKGACDKAFAPMSTFKVPLAVMGYDAGILVDAHNPRWDYKPEFNGYKFQQKTTDPTIWEKDSIVWYSQQLTRKMGQKRFAAYVAGFGYGNGDISGEPGKSNGLTHSWLGSSLKISPEGQVRFVRDLLSAKLPASKDAQQMTVSILPHFAAGDWAVQGKTGTGSFIDARGAKAPLGWFIGWATHEERRVVFARMTAGGKKGEQPAGPAARDAFLKALPDLAKRF'},
 'CARD_24': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OXA-226',
  'Sequence': 'MAIRIFAILFSIFSLATFAHAQEGTLERSDWRKFFSEFQAKGTIVVADERQADRAMLVFDPVRSKKRYSPASTFKIPHTLFALDAGAVRDEFQIFRWDGVNRGFAGHNQDQDLRSAMRNSTVWVYELFAKEIGDDKARRYLKKIDYGNADPSTSNGDYRIEGSLAISAQEQIAFLRKLYRNELPFRVEHQRLVKDLMIVEAGRNWILRAKTGWEGRMGWWVGWVEWPTGSVFFALNIDTPNRMDDLFKREAIVRAILRSIEALPPNPAVNSDAAR'},
 'CARD_25': {'Drug Class': 'cephalosporin',
  'Name': 'CTX-M-155',
  'Sequence': 'MVKKSLRQFTLMATATVTLLLGSVPLYAQTADVQQKLAELERQSGGRLGVALINTADNSQILYRADERFAMCSTSKVMAAAAVLKKSESEPNLLNQRVEIKKSDLVNYNPIAEKHVNGTMSLAELSAAALQYSDNVAMNKLIAHVGGPASVTAFARQLGDETFRLDRTAPTLNTAIPGDPRDTTSPRAMAQTLRNLTLGKALGDSQRAQLVTWMKGNTTGAASIQAGLPASWVVGDKTGSGGYGTTNDIAVIWPKDRAPLILVTYFTQPQPKAESRRDVLASGAKIVTDGL'},
 'CARD_26': {'Drug Class': 'cephalosporin',
  'Name': 'DHA-15',
  'Sequence': 'MKKSLSATLISALLAFSAPGFSAADNVAAVVDSTIKPLMAQQDIPGMAVAVSVKGKPYYFNYGFADIQAKQPVTENTLFELGSVSKTFTGVLGAVSVAKKEMALNDPAAKYQPELALPQWKGITLLDLATYTAGGLPLQVPDAVKSRADLLNFYQQWQPSRKPGYMRLYANSSIGLFGALTANAAGMPYEQLLTARILAPLGLSHTFITVPESAQSQYAYGYKNKKPVRVSPGQLDAESYGVKSASKDMLRWAEMNMEPSRAGNADLEMAMYLAQTRYYKTAAINQGLGWEMYDWPQQKDMIINGVTNEVALQPHPVTDNQVQPYNRASWVHKTGATTGFGAYVAFIPEKQVAIVILANKNYPNTERVKAAQAILSALE'},
 'CARD_27': {'Drug Class': 'macrolide antibiotic;streptogramin antibiotic',
  'Name': 'msrE',
  'Sequence': 'MSLIIKARNIRLDYAGRDVLDIDELEIHSYDRIGLVGDNGAGKSSLLKVLNGEIVLAEATLQRFGDFAHISQLGGIEIETVEDRAMLSRLGVSNVQNDTMSGGEETRAKIAAAFSQQVHGILADEPTSHLDLNGIDLLIGQLKAFDGALLVISHDRYFLDMVVDKIWELKDGKITEYWGGYSDYLRQKEEERQHQAVEYELMMKERERLESAVQEKRQQANRLDNKKKGEKSKNSTESAGRLGHAKMTGTKQRKLYQAAKSMEKRLAALEDIQAPEHLRSIRFRQSSALELHNKFPITADGLSLKFGSRTIFDDANFIIPLGAKVAITGSNGTGKTSLLKMISERADGLTISPKAEIGYFTQTGYKFNTHKSVLSFMQEECEYTVAEIRAVLASMGIGANDIQKNLSDLSGGEIIKLLLSKMLLGKYNILLMDEPGNYLDLKSIAALETMMKSYAGTIIFVSHDKQLVDNIADIIYEIKDHKIIKTFERDC'},
 'CARD_28': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OXY-6-3',
  'Sequence': 'MLKSSWRKSALMAAAAVPLLLASGSLWASADAIQQKLADLEKRSGGRLGVALINTTDDSQTLYRGDERFAMCSTGKVMAAAAVLKQSESHPDVVNKRLEIKKSDLVVWSPITEKHLQSGMTLAELSAAALQYSDNTAMNKMISYLGGPEKVTAFAQSIGDVTFRLDRTEPALNSAIPGDKRDTTTPLAMAESLRKLTLGNALGEQQRAQLVTWLKGNTTGGQSIRAGLPASWAVGDKTGAGDYGTTNDIAVIWPENHAPLVLVTYFTQPQQDAKSRKEVLAAAAKIVTEGL'},
 'CARD_29': {'Drug Class': 'phosphonic acid antibiotic',
  'Name': 'FosA2',
  'Sequence': 'MLQSLNHLTLAVSDLQKSVTFWHELLGLTLHARWNTGAYLTCGDLWVCLSYDEARGYVPPQESDYTHYAFTVAAEDFEPFSHKLEQAGVTVWKQNKSEGASFYFLDPDGHKLELHVGSLAARLAACREKPYAGMVFTSDEA'},
 'CARD_30': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': "APH(3')-Va",
  'Sequence': 'MDDSTLRRKYPHHEWHAVNEGDSGAFVYQLTGGPEPQPELYAKIAPRAPENSAFDLSGEADRLEWLHRHGIPVPRVVERGADDTAAWLVTEAVPGVAAAEEWPEHQRFAVVEAMAELARALHELPVEDCPSDRRLDAAVAEARRNVAEGLVDLDDLQEERAGWTGDQLLAELDRTRPEKEDLVVCHGDLCPNNVLLDPGTCRVTGVIDVGRLGVADRHADIALAARELEIDEDPWFGPAYAERFLERYGAHRVDKEKLAFYQLLDEFF'},
 'CARD_31': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': 'AAC(3)-Ia',
  'Sequence': 'MGIIRTCRLGPDQVKSMRAALDLFGREFGDVATYSQHQPDSDYLGNLLRSKTFIALAAFDQEAVVGALAAYVLPRFEQPRSEIYIYDLAVSGEHRRQGIATALINLLKHEANALGAYVIYVQADYGDDPAVALYTKLGIREEVMHFDIDPSTAT'},
 'CARD_32': {'Drug Class': 'fluoroquinolone antibiotic',
  'Name': 'QnrB58',
  'Sequence': 'MTPLLYKKTGTNMALALVGEKIDRNRFTGEKIDNSTFFNCDFSGADLSGTEFIGCQFYDRESQKGCNFSRAMLKDAIFKSCDLSMADFRNASALGIEIRHCRAQGADFRGASFMNMITTRTWFCSAYITNTNLSYANFSKVVLEKCELWENRWMGAQVLGATFSGSDLSGGEFSTFDWRAANFTHCDLTNSELGDLDIRGVDLQGVKLDNYQASLLMERLGIAIIG'},
 'CARD_33': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': 'rmtH',
  'Sequence': 'MTIEQAAADILSSKKYQLLCPDTVVRILTQEWGRHKKPKQAVERTRERLHGICGAYLAPQVEKQASTALAAGDVQKALALHASTRERLDTYPQLYQFVFENNLPARVLDIACGLNPLMLHRQGVASVWGCDIHQGLGNVLTPYAQKHGWDFTFALHDVLCAPVAASGDMALVFKLLPLLEREQPGAALALLRTLDAPVICVSFPTRSLGGRGKGMHQHYATWFEGLVAPHFTVQHHTLIGDELLYRIQPNPA'},
 'CARD_34': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OXY-6-1',
  'Sequence': 'MLKSSWRKSALMAAAAVPLLLASGSLWASADAIQQKLADLEKRSGGRLGVALINTADDSQTLYRGDERFAMCSTGKVMAAAAVLKQSESHPDVVNKRLEIKKSDLVVWSPITEKHLQSGMTLAELSAAALQYSDNTAMNKMISYLGGPEKVTAFAQSIGDVTFRLDRTEPALNSAIPGDKRDTTTPLAMAESLRKLTLGNALGEQQRAQLVTWLKGNTTGGQSIRAGLPASWAVGDKTGAGDYGTTNDIAVIWPENHAPLVLVTYFTQPQQDAKSRKEVLAAAAKIVTEGL'},
 'CARD_35': {'Drug Class': 'carbapenem;cephalosporin;monobactam;penicillin beta-lactam;phenicol antibiotic',
  'Name': 'golS',
  'Sequence': 'MNIGKAAKASKVSAKMIRYYEQIGLIPAASRTDSGYRAYTQADVNQLHFIRRARDLGFSVAEISDLLNLWNNQSRQSADVKRLAQTHIDELDRRIQNMQHMAQTLKALIHCCAGDALPDCPILHTLGQPDDSEPEARTGAVLRRPRRHGLAKRL'},
 'CARD_36': {'Drug Class': 'disinfecting agents and antiseptics;nucleoside antibiotic',
  'Name': 'mdtP',
  'Sequence': 'MINRQLSRLLLCSILGSTTLISGCALVRKDSAPHQQLKPEQIKLADDIHLASSGWPQAQWWKQLNDPQLDALIQRTLSGSHTLAEAKLREEKAQSQADLLDAGSQLQVAALGMLNRQRVSANGFLSPYSMDAPALGMDGPYYTEATVGLFAGLDLDLWGVHRSAVAAAIGAHNAALAETAAVELSLATGVAQLYYSMQASYQMLDLLEQTHDVIDYAVKAHQSKVAHGLEAQVPFHGARAQILAVDKQIVAVKGQITETRESLRALIGAGASDMPEIRPVALPQVQTGIPATLSYELLARRPDLQAMRWYVQASLDQVDSARALFYPSFDIKAFFGLDSIHLHTLFKKTSRQFNFIPGLKLPLFDGGRLNANLEGTRAASNMMIERYNQSVLNAVRDVAVNGTRLQTLNDEREMQAERVEATRFTQRAAEAAYQRGLTSRLQATEARLPVLAEEMSLLMLDSRRVIQSIQLMKSLGGGYQAGPVVEKK'},
 'CARD_37': {'Drug Class': 'cephalosporin',
  'Name': 'CMY-114',
  'Sequence': 'MMKKSLCCALLLTASFSTFAAAKTEQQIADIVNRTITPLMQEQAIPGMAVAIIYEGKPYYFTWGKADIANNHPVTQQTLFELGSVSKTFNGVLGGDAIARGEIKLSDPVTKYWPELTGKQWRGISLLHLATYTAGGLPLQIPDYVTDKAELLRFYQNWQPQWTPGAKRLYANSSIGLFGALVVKPSGMSYEEAMTRRVLQPLKLAHTWITVPQSEQKNYAWGYREGKPVHVSPGQLDAEAYGVKSSVIDMARWVQANMDASHVQEKTLQQGIELAQSRYWRIGDMYQGLGWEMLNWPLKADSIINGSDSKVALAALPAVEVNPPAPAVKASWVHKTGSTGGFGSYVAFVPEKNLGIVMLANKSYPNPARVEAAWRILEKLQ'},
 'CARD_38': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-60',
  'Sequence': 'MLSRYSKTLAFAVVACTLAISTATAHAELVVRNDLKRVFDDAGVSGTFVLMDITADRTYVVDPARAARSIHPASTFKIPNSLIAFDTGAVRDDQEVLPYGGKPQPYEQWEHDMALPEAIRLSAVPIYQEVARRVGFERMQAYVDAFDYGNRQLGSAIDQFWLRGPLEISAFEEARFTSRMALKQLPVKPRTWDMVQRMLLIEQQGDAALYAKTGVATEYQPEIGWWAGWVERAGHVYAFALNIDMPREGDMAKRIPLGKQLMRALEVWPAP'},
 'CARD_39': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-90',
  'Sequence': 'MNIKALLLITSAIFISACSPYIVTANPNHSASKSDEKAEKIKNLFNEAHTTGVLVIQQGQTQQSYGNDLARASTEYVPASTFKMLNALIGLEHHKATTTEVFKWDGKKRLFPEWEKDMTLGDAMKASAIPVYQDLARRIGLELMSKEVKRVGYGNADIGTQVDNFWLVGPLKITPQQEAQFAYKLANKTLPFSQKVQDEVQSMLFIEEKNGNKIYAKSGWGWDVDPQVGWLTGWVVQPQGNIVAFSLNLEMKKGIPSSVRKEITYKSLEQLGIL'},
 'CARD_40': {'Drug Class': 'carbapenem',
  'Name': 'SME-2',
  'Sequence': 'MSNKVNFKTASFLFSVCLALSAFNAHANKSDAAAKQIKKLEEDFDGRIGVFAIDTGSGNTFGYRSDERFPLCSSFKGFLAAAVLERVQQKKLDINQKVKYESRDLEYHSPITTKYKGSGMTLGDMASAALQYSDNGATNIIMERFLGGPEGMTKFMRSIGDNEFRLDRWELELNTAIPGDKRDTSTPKAVANSLNKLALGNVLNAKEKAIYQNWLKGNTTGDARIRASVPADWVVGDKTGSCGAYGTANDYAVIWPKNRAPLIVSIYTTRKSKDDKHSDKTIAEASRIAIQAID'},
 'CARD_41': {'Drug Class': 'aminoglycoside antibiotic',
  'Name': 'AAC(3)-IIIc',
  'Sequence': 'MFSRWSKPLVLAAVTRASLAADLAALGLAAGDAVMVHAAVSKVGRLLDGPDTIIAALSDAGRPAGTILAYADWEARYEDLVDEDGRVPQEWREHIPPFDPRRSRAIRDNGVLPEFLRTTPGALRSGNPGASMVGLGARAEWFTADHPLDYGYGEGSPLARLVEAGGKVLMLGAPLDTLTLLHHAEHLADIPGKRIRRIEVPLATPTGTQWRMIEEFDTGDPIVEGLAEDYFAEIVTAFLAGGRGRQGLIGTAPSVLVDAAAITAFGVAWLESRFGSPSS'},
 'CARD_42': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'OXY-2-2',
  'Sequence': 'MIKSSWRKIAMLAAAVPLLLASGALWASTDAIHQKLTDLEKRSGGRLGVALINTADNSQILYRGDERFAMCSTSKVMAAAAVLKQSESNKEVVNKRLEINAADLVVWSPITEKHLQSGMTLAELSAATLQYSDNTAMNLIIGYLGGPEKVTAFARSIGDATFRLDRTEPTLNTAIPGDERDTSTPLAMAESLRKLTLGDALGEQQRAQLVTWLKGNTTGGQSIRAGLPESWVVGDKTGAGDYGTTNDIAVIWPEDHAPLILVTYFTQPQQDAKNRKEVLAAAAKIVTEGL'},
 'CARD_43': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'MOX-5',
  'Sequence': 'MQQRQSILWGALATLMWAGLAHAGDKAATDPLRPVVDASIRPLLKEHRIPGMAVAVLKDGKAHYFNYGVADRERAVGVSEQTLFEIGSVSKTLTATLGAYAVVQGGFELDDKASLFAPWLKGSAFDNITMGELATYSAGGLPLQFPEEVDSLEKMQAYYRQWTPAYSRGSHRQYANPSIGLFGYLAASSMKQPFDRLMEQTMLPGLGLYHTYLNVPEQPMGHYAYGYWKEDKPFRVTPAMLAEEPYGIKTSSADLLRFVKANISGVDNAAMQQAIDLTHQGQYAVGEMTQGLGWERYPYPVSEQTLLAGNSPAMIYNANPAAPAPAAAGHPVLFKKTGSTNGFGAYVAFVPAKGIGVVMLANRNYPNEGTLKAGHAILTQLAR'},
 'CARD_44': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-34',
  'Sequence': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMVSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW'},
 'CARD_45': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-69',
  'Sequence': 'MNIKALLLITSAIFISACSPYIVTANPNHSASKSDDKAEKIKNLFNEAHTTGVLVIHQGQTQQSYGNDLARASTEYVPASTFKMLNALIGLEHHKATTTEVFKWDGEKRLFPEWEKNMTLGDAMKASAIPVYQDLARRIGLELMSKEVKRVGYGNADIGTQVDNFWLVGPLKITPQQEAQFAYKLANKTLPFSQKVQDEVQSMLFIEEKNGNKIYAKSGWGWDVNPQVGWLTGWVVQPQGNIVAFSLNLEMKKGIPSSVRKEITYKSLEQLGIL'},
 'CARD_46': {'Drug Class': 'cephalosporin;monobactam;penicillin beta-lactam',
  'Name': 'TEM-7',
  'Sequence': 'FFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDSWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNR'},
 'CARD_47': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'SHV-24',
  'Sequence': 'MRYIRLCIISLLATLPLAVHASPQPLEQIKLSESQLSGRVGMIEMDLASGRTLTAWRADERFPMMSTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLATVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARGTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR'},
 'CARD_48': {'Drug Class': 'fluoroquinolone antibiotic',
  'Name': 'QnrB47',
  'Sequence': 'MTLALVGEKIDRNRFTGEKVENSTFFNCDFSGADLSGTEFIGCQFYDRESQKGCNFSRAMLRDAIFKSCDLSMADFRNVSALGIEIRHCRAQGADFRGASFMNMITTRTWFCSAYITNTNLSYANFSKVVLEKCELWENRWMGTQVLGATFSGSDLSGGEFSTFDWRAANFTHCDLTNSELGDLDIRGVDLQGVKLDNYQASLLMERLGIAVIG'},
 'CARD_49': {'Drug Class': 'cephalosporin;penicillin beta-lactam',
  'Name': 'OXA-256',
  'Sequence': 'MKTFAAYVIIACLSSTALAGSITENTSWNKEFSAEAVNGVFVLCKSSSKSCATNDLARASKEYLPASTFKIPDAIIGLETGVIKNEHQVFKWDGKPRAMKQWERDLTLRGAIQVSAVPVFQQIAREVGEVRMQKYLKKFSYGNQNISGGIDKFWLEGQLRISAVNQVEFLESLYLNKLSASKENQLIVKEALVTEAAPEYLVHSKTGFSGVGTESNPGVAWWVGWVEKETEVYFFAFNMDIDNESKLPLRKSIPTKIMESEGIIGG'},
 'CARD_50': {'Drug Class': 'fluoroquinolone antibiotic',
  'Name': 'QnrS6',
  'Sequence': 'METYRHTYRHHSFSHQDLSDITFTACTFIRCDFRRANLRDATFINCKFIEQGDIEGCHFDVADLRDASFQQCQLAMANFSNANCYGIELRECDLKGANFSRANFANQVSNRMYFCSAFITGCNLSYANMERVCLEKCELYENRWIGTHLAGASLKESDLSRGVFSEDVWGQFSLQGANLCHAELDGLDPRKVDTSGIKIASWQQEQLLEALGIVVFPD'},
 'CARD_51': {'Drug Class': 'carbapenem;penicillin beta-lactam',
  'Name': 'OXA-330',

In [17]:
def CreateGeneralClass(base):
    for key, value in base.items():
        DrugClass = base[key]["Drug Class"]
        DrugClass = DrugClass.replace("antibiotic", "").lower().strip()
        base[key].update({"Drug Class": DrugClass.rstrip('s')})

        if "cephalosporin" in DrugClass:
            base[key].update({"Drug Class": "beta-lactam"})
        if "carbapenem" in DrugClass:
            base[key].update({"Drug Class": "beta-lactam"})
        if "penicillin" in DrugClass:
            base[key].update({"Drug Class": "beta-lactam"})
        if "beta_lactam" in DrugClass:
            base[key].update({"Drug Class": "beta-lactam"})
        if "betalactams" in DrugClass:
            base[key].update({"Drug Class": "beta-lactam"})
        if "penicillin" in DrugClass:
            base[key].update({"Drug Class": "beta-lactam"})
        if "phosphonic acid" in DrugClass:
            base[key].update({"Drug Class": "phosphonic acid"})

        Macrolide = bool(re.search(rf'\b{re.escape("macrolide")}\b', DrugClass))
        Lincosamide = bool(re.search(rf'\b{re.escape("lincosamide")}\b', DrugClass))
        Streptogramin = bool(re.search(rf'\b{re.escape("streptogramin")}\b', DrugClass))
        if Macrolide and Lincosamide and Streptogramin:
            base[key].update({"Drug Class": "MLS"})


    return base

In [18]:
"Tiagos".strip('s')

'Tiago'

In [19]:
MetaDict = CreateGeneralClass(MetaDict)

In [20]:
MetaDict

{'CARD_0': {'Drug Class': 'beta-lactam',
  'Name': 'CblA-1',
  'Sequence': 'MKAYFIAILTLFTCIATVVRAQQMSELENRIDSLLNGKKATVGIAVWTDKGDMLRYNDHVHFPLLSVFKFHVALAVLDKMDKQSISLDSIVSIKASQMPPNTYSPLRKKFPDQDFTITLRELMQYSISQSDNNACDILIEYAGGIKHINDYIHRLSIDSFNLSETEDGMHSSFEAVYRNWSTPSAMVRLLRTADEKELFSNKELKDFLWQTMIDTETGANKLKGMLPAKTVVGHKTGSSDRNADGMKTADNDAGLVILPDGRKYYIAAFVMDSYETDEDNANIIARISRMVYDAMR'},
 'CARD_1': {'Drug Class': 'beta-lactam',
  'Name': 'SHV-52',
  'Sequence': 'MRYIRLCIISLLAALPLAVHASPQPLEQIKQSESQLSGRVGMIEMDLASGRTLTAWRADERFPMISTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLAIVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARDTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR'},
 'CARD_2': {'Drug Class': 'diaminopyrimidine',
  'Name': 'dfrF',
  'Sequence': 'MIGLIVARSKNNVIGKNGNIPWKIKGEQKQFRELTTGNVVIMGRKSYEEIGHPLPNRMNIVVSTTTEYQGDNLVSVKSLEDALLLAKGRDVYISGGYGLFKEALQIVDKMYITEVDLNIEDGDTFFPEFDINDFEVLIGETLGEEVKYTRTFYVRKNELSRFWI'},
 'CARD_3': {'Drug Class': 'beta-lactam',
  'Name': 'CTX-M-130',
  'Sequence': 'MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDERFPMCSTSKVMAAAAVLKQSETQKQLLNQPVEIKPADLVNYNPIAEKHVNGTMTLAELSAAALQYSDNTAMNKLIAQLGGPGGVTAFARAIGDETFRLDRTEPTLNTAIPGDPRDTTTPRAMAQTLRQLTLGHALGETQRAQLVTWLKGNTTGAASIRAGLPTSWTVGDKTGSGDYGTTNDIAVIWPQGRAPLVLVTYFTQPQQNAERRHDVLASAARIIAEGL'},
 'CARD_4': {'Drug Class': 'beta-lactam',
  'Name': 'NDM-6',
  'Sequence': 'MELPNIMHPVAKLSTALAAALMLSGCMPGEIRPTIGQQMETGDQRFGDLVFRQLAPNVWQHTSYLDMPGFGAVASNGLIVRDGGRVLVVDTAWTDDQTAQILNWIKQEINLPVALAVVTHAHQDKMGGMDALHAAGIATYANALSNQLAPQEGMVAAQHSLTFAANGWVEPATAPNFGPLKVFYPGPGHTSDNITVGIDGTDIAFGGCLIKDSKAKSLGNLGDADTEHYAASVRAFGAAFPKASMIVMSHSAPDSRAAITHTARMADKLR'},
 'CARD_5': {'Drug Class': 'beta-lactam',
  'Name': 'ACT-35',
  'Sequence': 'MMKKSLCCALLLGISCSALATPVSEKQLAEVVANTVTPLMKAQSVPGMAVAVIYQGKPHYYTFGKADIAANKPVTPQTLFELGSISKTFTGVLGGDAIARGEISLDDPVTRYWPQLTGKQWQGIRMLDLATYTAGGLPLQVPDEVTDNASLLRFYQNWQPQWKPGTTRLYANASIGLFGALAVKPSGMPYEQAMTTRVLKPLKLDHTWINVPKAEEAHYAWGYRDGKAVRVSPGMLDAQAYGVKTNVQDMANWVMANMAPENVADASLKQGIALAQSRYWRIGSMYQGLGWEMLNWPVEANTVVEGSDSKVALAPLPVVEVNPPAPPVKASWVHKTGSTGGFGSYVAFIPEKQIGIVMLANTSYPNPARVEAAYYILEALQ'},
 'CARD_6': {'Drug Class': 'beta-lactam',
  'Name': 'CARB-5',
  'Sequence': 'MNVRKHKASFFSVVITFLCLTLSLNANATDSVLEAVTNAETELGARIGLAVHDLETGKRWEHKSNERFPLSSTFKTLACANVLQRVDLGKERIDRVVRFSESNLVTYSPVTEKHVGKKGMSLAELCQATLSTSDNSAANFILQAIGGPKALTKFLRSIGDDTTRLDRWETELNEAVPGDKRDTTTPIAMVTTLEKLLIDETLSIKSRQQLESWLKGNEVGDALFRKGVPSDWIVADRTGAGGYGSRAITAVMWPPNRKPIVAALYITETDASFEERNAVIAKIGEQIAKTVLMENSRN'},
 'CARD_7': {'Drug Class': 'MLS',
  'Name': 'Erm(34)',
  'Sequence': 'MTKKMNKYNGKKLSRGEPPNFSGQHFMHNKRLLKEIVDKADVSVRDTVLELGAGKGALTTILSERADRVLAVEYDQKCIEALQWKLVGSKNVSILHQDIMKVALPTEPFVVVSNIPYSITTAIMKMLLNNPKNKLQRGAIVMEKGAAKRFTSVSPKDAYVMAWHMWFDIHYERGISRSSFSPPPKVDSALVRIVRKQHPLFPYKEAKAMHDFLSYALNNPRAPLDQVLRGIFTAPQAKKVRQAIGVKPETPVAMLHARQWAMVCDAMVRHVPKVYWPRRKR'},
 'CARD_8': {'Drug Class': 'beta-lactam',
  'Name': 'TEM-126',
  'Sequence': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERETTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW'},
 'CARD_9': {'Drug Class': 'beta-lactam',
  'Name': 'LRA-12',
  'Sequence': 'MNVQNCMVKAVSVSIILFASLSLAAQKVKEPTVSNADWSKPYRPFRIAGNLYYIGTYDLACYLITTKQGNIIVNTGLAASALQIKNNIKALGFKLTDTKILLTTQAHYDHLGAMAEIKKITGAKLMADEGDATVMADGGSSDYAFGGHGSMFEPIIADRLLHDKDTIQLGDTKLVMLHHPGHTKGSCSFLFDTKDEQRSYRILIANMPTIVIEKKFSEVSSYPGIAKDYAYTLQAMKNLSFDIWVASHASQFSMHSKHKPGDGYNPKSFMDRKGYDESLDKLQKEYEKHLNEN'},
 'CARD_10': {'Drug Class': 'beta-lactam',
  'Name': 'TEM-72',
  'Sequence': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTTPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGASKRGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW'},
 'CARD_11': {'Drug Class': 'beta-lactam',
  'Name': 'TEM-59',
  'Sequence': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMGDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAE'},
 'CARD_12': {'Drug Class': 'beta-lactam',
  'Name': 'KPC-10',
  'Sequence': 'MSLYRRLVLLSCLSWPLAGFSATALTNLVAEPFAKLEQDFGGSIGVYAMDTGSGATVSYRAEERFPLCSSFKGFLAAAVLARSQQQAGLLDTPIRYGKNALVRWSPISEKYLTTGMTVAELSAAAVQYSDNAAANLLLKELGGPAGLTAFMRSIGDTTFRLDRWELELNSAIPGDARDTSSPRAVTESLQKLTLGSALAAPQRQQFVDWLKGNTTGNHRIRAAVPADWAVGDKTGTCGVYGTANDYAVVWPTGRAPIVLAVYTRAPNKDDKYSEAVIAAAARLALEGLGVNGQ'},
 'CARD_13': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-212',
  'Sequence': 'MKTLQSGLIALITTFGSACTTISPSVETAKNQQQQSAQQQIQQAFDQLQTTGVIVVKDKHSLHSYGNDLSRAQTPYIPASTFKMLNALIGLEHGKATSTEVFKWDGQKRSFPTWEKDMTLGQAMQASAVPVYQELARRIGLDLMKKEVQRIGYGNQQIGTVVDNFWLVGPLQITPVQEVLFVEKLANTQLAFKPDVQHAVQDMLLIEQKPNYKLYAKSGWGMDLEPQVGWWAGWVETSTGEKVYFALNMHMKTGISASVREQLVKQSLTALGII'},
 'CARD_14': {'Drug Class': 'beta-lactam',
  'Name': 'IMP-2',
  'Sequence': 'MKKLFVLCVCFLCSITAAGARLPDLKIEKLEEGVYVHTSFEEVNGWGVVSKHGLVVLVNTDAYLIDTPFTATDTEKLVNWFVERGYKIKGTISSHFHSDSTGGIEWLNSQSIPTYASELTNELLKKDGKVQAKNSFSGVSYWLVKNKIEVFYPGPGHTQDNVVVWLPEKKILFGGCFVKPDGLGNLGDANLEAWPKSAKILMSKYVKAKLVVSSHSEIGDASLLKRTWEQAVKGLNESKKPSQPSN'},
 'CARD_15': {'Drug Class': 'beta-lactam',
  'Name': 'CMY-1',
  'Sequence': 'MQQRQSILWGAVATLMWAGLAHAGEASPVDPLRPVVDASIQPLLKEHRIPGMAVAVLKDGKAHYFNYGVANRESGAGVSEQTLFEIGSVSKTLTATLGAYAVVKGAMQLDDKASRHAPWLKGSAFDSITMGELATYSAGGLPLQFPEEVDSSEKMRAYYRQWAPVYSPGSHRQYSNPSIGLFGHLAASSLKQPFAPLMEQTLLPGLGMHHTYVNVPKQAMASYAYGYSKEDKPIRVNPGMLADEAYGIKTSSADLLRFVKANIGGVDDKALQQAISLTHQGHYSVGGMTQGLGWESYAYPVTEQTLLAGNSAKVILEANPTAAPRESGSQVLFNKTGSTNGFGAYVAFVPARGIGIVMLANRNYPNEARIKAAHAILAQLAG'},
 'CARD_16': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-329',
  'Sequence': 'MYKKALIVATSILFLSACSSNTVKQHQIHSISANKNSEAIKSLFDQAQTTGVLVIKRGQTEEIYGNDLKRASTAYVPASTFKMLNALIGLEHHKAITTEVFKWDGQKRLFPDWEKDMTLGDAMKASAIPVYQELARRIGLDLMSKEVKRIGFGNANIGSKVDDFWLVGPLKITPQQETQFAYQLAHKMLPFSKDVQEQVQSMVFIEEKNGRKIYAKSGWGWDIEPQVGWLTGWVVQPQGEIVAFSLNLEMKKGTPSSIRKEIAYKGLEQLGIL'},
 'CARD_17': {'Drug Class': 'beta-lactam',
  'Name': 'ACT-10',
  'Sequence': 'MMKKSVCCALLLSTSCSVLAAPMSEKQLAEVVERTVTPLMKAQAIPGIAVAVIYQGQPHYFTFGKADVAANKPVTPQTLFELGSISKTFTGVLGGDAIARGEISLGDPVTKYWPELTGKQWKGIRMLDLATYTAGGLPLQVPDEVTDNASLLRFYQNWQPQWKPGTTRLYANASIGLFGALAVKPSGMSYEQAITTRVFKPLKLDHTWINVPKTEEAHYAWGYRDGKAVHVSPGMLDAEAYGVKTNVKDMASWVMVNMKPDSLEDSSLRKGFTLAQSRYWRVGAMYQGLGWEMLNWPVDAKTVVEGSDNKVALAPLPAREVNPPAPPVNASWVHKTGSTGGFGSYVAFIPEKQLGIVMLANKSYPNPARVEAAYRILDALQ'},
 'CARD_18': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-371',
  'Sequence': 'MNIKALLLITSAIFISACSPYIVTANPNHSASKSDDKAEKIKNLFNEAHTTGVLVIHQGQTQQSYGNDLARASTEYVPASTFKMLNALIGLEHHKATTTEVFKWDGEKRLFPEWEKNMTLGDAMKASAIPVYQDLARRIGLELMSKEVKRVGYGNADIGTQVDNFWLVGPLKITPQQEAQFAYKLANKTLPFSQKVQDEVQSMLFIEEKNGNKIYAKSGWGWDVNPQVGWLTGWVVKPQGNIVAFSLNLEMKKGIPSSVRKEITYKSLEQLGIL'},
 'CARD_19': {'Drug Class': 'fusidane',
  'Name': 'fusB',
  'Sequence': 'MKTMIYPHQYNYIRSVILRLKNVYKTVNDKETVKVIQSETYNDINEIFGHIDDDIEESLKVLMNIRLSNKEIEAILNKFLEYVVPFELPSPQKLQKVFKKVKKIKIPQFEEYDLKVSSFVGWNELASNRKYIIYYDEKKQLKGLYGEISNQVVKGFCTICNKESNVSLFMKKSKTNSDGQYVKKGDYICRDSIHCNKQLTDINQFYNFIDKLD'},
 'CARD_20': {'Drug Class': 'beta-lactam',
  'Name': 'CTX-M-121',
  'Sequence': 'MVTKRVQRMMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDERFPMCSTSKVMAAAAVLKQSETQKQLLNQPVEIKPADLVNYNPITEKHVNGTMTLAELSAAALQYSDNTAMNKLIAQLGGPGGVTAFARAIGDETFRLDRTEPTLNTAIPGDPRDTTTPRAMAQTLRQLTLGHALGETQRAQLVTWLKGNTTGAASIRAGLPTSWTVGDKTGSGGYGTTNDIAVIWPQGRAPLVLVTYFTQPQQNAESRRDVLASAARIIAEGL'},
 'CARD_21': {'Drug Class': 'beta-lactam',
  'Name': 'VEB-3',
  'Sequence': 'MKIVKRILLVLLSLFFTVVYSNAQTDNLTLKIENVLKAKNARIGVAIFNSNEKDTFKINNDFHFPMQSVMKFPIALAVLSEIDKGNLSFEQKIEITPQDLLPKTWSPIKEEFPNGTTLTIEQILNYTVSESDNIGCDILLKLIGGTDSVQKFLNANHFTDISIKANEEQMHKDWNTQYQNWATPTAMNKLLIDTYNNKNQLLSKKSYDFIWKIMRETTTGSNRLKGQLPKNTIVAHKTGTSGINNGIAAATNDVGVITLPNGQLIFISVFVAESKETSEINEKIISDIAKITWNYYLNK'},
 'CARD_22': {'Drug Class': 'lincosamide',
  'Name': 'lnuA',
  'Sequence': 'MKNNNVTEKELFYILDLFEHMKVTYWLDGGWGVDVLTGKQQREHRDIDIDFDAQHTQKVIQKLEDIGYKIEVHWMPSRMELKHEEYGYLDIHPINLNDDGSITQANPEGGNYVFQNDWFSETNYKDRKIPCISKEAQLLFHSGYDLTETDHFDIKNLKSIT'},
 'CARD_23': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-45',
  'Sequence': 'MRGKHTVILGAALSALFAGAAGAQMLECTLVADAASGQELYRKGACDKAFAPMSTFKVPLAVMGYDAGILVDAHNPRWDYKPEFNGYKFQQKTTDPTIWEKDSIVWYSQQLTRKMGQKRFAAYVAGFGYGNGDISGEPGKSNGLTHSWLGSSLKISPEGQVRFVRDLLSAKLPASKDAQQMTVSILPHFAAGDWAVQGKTGTGSFIDARGAKAPLGWFIGWATHEERRVVFARMTAGGKKGEQPAGPAARDAFLKALPDLAKRF'},
 'CARD_24': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-226',
  'Sequence': 'MAIRIFAILFSIFSLATFAHAQEGTLERSDWRKFFSEFQAKGTIVVADERQADRAMLVFDPVRSKKRYSPASTFKIPHTLFALDAGAVRDEFQIFRWDGVNRGFAGHNQDQDLRSAMRNSTVWVYELFAKEIGDDKARRYLKKIDYGNADPSTSNGDYRIEGSLAISAQEQIAFLRKLYRNELPFRVEHQRLVKDLMIVEAGRNWILRAKTGWEGRMGWWVGWVEWPTGSVFFALNIDTPNRMDDLFKREAIVRAILRSIEALPPNPAVNSDAAR'},
 'CARD_25': {'Drug Class': 'beta-lactam',
  'Name': 'CTX-M-155',
  'Sequence': 'MVKKSLRQFTLMATATVTLLLGSVPLYAQTADVQQKLAELERQSGGRLGVALINTADNSQILYRADERFAMCSTSKVMAAAAVLKKSESEPNLLNQRVEIKKSDLVNYNPIAEKHVNGTMSLAELSAAALQYSDNVAMNKLIAHVGGPASVTAFARQLGDETFRLDRTAPTLNTAIPGDPRDTTSPRAMAQTLRNLTLGKALGDSQRAQLVTWMKGNTTGAASIQAGLPASWVVGDKTGSGGYGTTNDIAVIWPKDRAPLILVTYFTQPQPKAESRRDVLASGAKIVTDGL'},
 'CARD_26': {'Drug Class': 'beta-lactam',
  'Name': 'DHA-15',
  'Sequence': 'MKKSLSATLISALLAFSAPGFSAADNVAAVVDSTIKPLMAQQDIPGMAVAVSVKGKPYYFNYGFADIQAKQPVTENTLFELGSVSKTFTGVLGAVSVAKKEMALNDPAAKYQPELALPQWKGITLLDLATYTAGGLPLQVPDAVKSRADLLNFYQQWQPSRKPGYMRLYANSSIGLFGALTANAAGMPYEQLLTARILAPLGLSHTFITVPESAQSQYAYGYKNKKPVRVSPGQLDAESYGVKSASKDMLRWAEMNMEPSRAGNADLEMAMYLAQTRYYKTAAINQGLGWEMYDWPQQKDMIINGVTNEVALQPHPVTDNQVQPYNRASWVHKTGATTGFGAYVAFIPEKQVAIVILANKNYPNTERVKAAQAILSALE'},
 'CARD_27': {'Drug Class': 'macrolide ;streptogramin',
  'Name': 'msrE',
  'Sequence': 'MSLIIKARNIRLDYAGRDVLDIDELEIHSYDRIGLVGDNGAGKSSLLKVLNGEIVLAEATLQRFGDFAHISQLGGIEIETVEDRAMLSRLGVSNVQNDTMSGGEETRAKIAAAFSQQVHGILADEPTSHLDLNGIDLLIGQLKAFDGALLVISHDRYFLDMVVDKIWELKDGKITEYWGGYSDYLRQKEEERQHQAVEYELMMKERERLESAVQEKRQQANRLDNKKKGEKSKNSTESAGRLGHAKMTGTKQRKLYQAAKSMEKRLAALEDIQAPEHLRSIRFRQSSALELHNKFPITADGLSLKFGSRTIFDDANFIIPLGAKVAITGSNGTGKTSLLKMISERADGLTISPKAEIGYFTQTGYKFNTHKSVLSFMQEECEYTVAEIRAVLASMGIGANDIQKNLSDLSGGEIIKLLLSKMLLGKYNILLMDEPGNYLDLKSIAALETMMKSYAGTIIFVSHDKQLVDNIADIIYEIKDHKIIKTFERDC'},
 'CARD_28': {'Drug Class': 'beta-lactam',
  'Name': 'OXY-6-3',
  'Sequence': 'MLKSSWRKSALMAAAAVPLLLASGSLWASADAIQQKLADLEKRSGGRLGVALINTTDDSQTLYRGDERFAMCSTGKVMAAAAVLKQSESHPDVVNKRLEIKKSDLVVWSPITEKHLQSGMTLAELSAAALQYSDNTAMNKMISYLGGPEKVTAFAQSIGDVTFRLDRTEPALNSAIPGDKRDTTTPLAMAESLRKLTLGNALGEQQRAQLVTWLKGNTTGGQSIRAGLPASWAVGDKTGAGDYGTTNDIAVIWPENHAPLVLVTYFTQPQQDAKSRKEVLAAAAKIVTEGL'},
 'CARD_29': {'Drug Class': 'phosphonic acid',
  'Name': 'FosA2',
  'Sequence': 'MLQSLNHLTLAVSDLQKSVTFWHELLGLTLHARWNTGAYLTCGDLWVCLSYDEARGYVPPQESDYTHYAFTVAAEDFEPFSHKLEQAGVTVWKQNKSEGASFYFLDPDGHKLELHVGSLAARLAACREKPYAGMVFTSDEA'},
 'CARD_30': {'Drug Class': 'aminoglycoside',
  'Name': "APH(3')-Va",
  'Sequence': 'MDDSTLRRKYPHHEWHAVNEGDSGAFVYQLTGGPEPQPELYAKIAPRAPENSAFDLSGEADRLEWLHRHGIPVPRVVERGADDTAAWLVTEAVPGVAAAEEWPEHQRFAVVEAMAELARALHELPVEDCPSDRRLDAAVAEARRNVAEGLVDLDDLQEERAGWTGDQLLAELDRTRPEKEDLVVCHGDLCPNNVLLDPGTCRVTGVIDVGRLGVADRHADIALAARELEIDEDPWFGPAYAERFLERYGAHRVDKEKLAFYQLLDEFF'},
 'CARD_31': {'Drug Class': 'aminoglycoside',
  'Name': 'AAC(3)-Ia',
  'Sequence': 'MGIIRTCRLGPDQVKSMRAALDLFGREFGDVATYSQHQPDSDYLGNLLRSKTFIALAAFDQEAVVGALAAYVLPRFEQPRSEIYIYDLAVSGEHRRQGIATALINLLKHEANALGAYVIYVQADYGDDPAVALYTKLGIREEVMHFDIDPSTAT'},
 'CARD_32': {'Drug Class': 'fluoroquinolone',
  'Name': 'QnrB58',
  'Sequence': 'MTPLLYKKTGTNMALALVGEKIDRNRFTGEKIDNSTFFNCDFSGADLSGTEFIGCQFYDRESQKGCNFSRAMLKDAIFKSCDLSMADFRNASALGIEIRHCRAQGADFRGASFMNMITTRTWFCSAYITNTNLSYANFSKVVLEKCELWENRWMGAQVLGATFSGSDLSGGEFSTFDWRAANFTHCDLTNSELGDLDIRGVDLQGVKLDNYQASLLMERLGIAIIG'},
 'CARD_33': {'Drug Class': 'aminoglycoside',
  'Name': 'rmtH',
  'Sequence': 'MTIEQAAADILSSKKYQLLCPDTVVRILTQEWGRHKKPKQAVERTRERLHGICGAYLAPQVEKQASTALAAGDVQKALALHASTRERLDTYPQLYQFVFENNLPARVLDIACGLNPLMLHRQGVASVWGCDIHQGLGNVLTPYAQKHGWDFTFALHDVLCAPVAASGDMALVFKLLPLLEREQPGAALALLRTLDAPVICVSFPTRSLGGRGKGMHQHYATWFEGLVAPHFTVQHHTLIGDELLYRIQPNPA'},
 'CARD_34': {'Drug Class': 'beta-lactam',
  'Name': 'OXY-6-1',
  'Sequence': 'MLKSSWRKSALMAAAAVPLLLASGSLWASADAIQQKLADLEKRSGGRLGVALINTADDSQTLYRGDERFAMCSTGKVMAAAAVLKQSESHPDVVNKRLEIKKSDLVVWSPITEKHLQSGMTLAELSAAALQYSDNTAMNKMISYLGGPEKVTAFAQSIGDVTFRLDRTEPALNSAIPGDKRDTTTPLAMAESLRKLTLGNALGEQQRAQLVTWLKGNTTGGQSIRAGLPASWAVGDKTGAGDYGTTNDIAVIWPENHAPLVLVTYFTQPQQDAKSRKEVLAAAAKIVTEGL'},
 'CARD_35': {'Drug Class': 'beta-lactam',
  'Name': 'golS',
  'Sequence': 'MNIGKAAKASKVSAKMIRYYEQIGLIPAASRTDSGYRAYTQADVNQLHFIRRARDLGFSVAEISDLLNLWNNQSRQSADVKRLAQTHIDELDRRIQNMQHMAQTLKALIHCCAGDALPDCPILHTLGQPDDSEPEARTGAVLRRPRRHGLAKRL'},
 'CARD_36': {'Drug Class': 'disinfecting agents and antiseptics;nucleoside',
  'Name': 'mdtP',
  'Sequence': 'MINRQLSRLLLCSILGSTTLISGCALVRKDSAPHQQLKPEQIKLADDIHLASSGWPQAQWWKQLNDPQLDALIQRTLSGSHTLAEAKLREEKAQSQADLLDAGSQLQVAALGMLNRQRVSANGFLSPYSMDAPALGMDGPYYTEATVGLFAGLDLDLWGVHRSAVAAAIGAHNAALAETAAVELSLATGVAQLYYSMQASYQMLDLLEQTHDVIDYAVKAHQSKVAHGLEAQVPFHGARAQILAVDKQIVAVKGQITETRESLRALIGAGASDMPEIRPVALPQVQTGIPATLSYELLARRPDLQAMRWYVQASLDQVDSARALFYPSFDIKAFFGLDSIHLHTLFKKTSRQFNFIPGLKLPLFDGGRLNANLEGTRAASNMMIERYNQSVLNAVRDVAVNGTRLQTLNDEREMQAERVEATRFTQRAAEAAYQRGLTSRLQATEARLPVLAEEMSLLMLDSRRVIQSIQLMKSLGGGYQAGPVVEKK'},
 'CARD_37': {'Drug Class': 'beta-lactam',
  'Name': 'CMY-114',
  'Sequence': 'MMKKSLCCALLLTASFSTFAAAKTEQQIADIVNRTITPLMQEQAIPGMAVAIIYEGKPYYFTWGKADIANNHPVTQQTLFELGSVSKTFNGVLGGDAIARGEIKLSDPVTKYWPELTGKQWRGISLLHLATYTAGGLPLQIPDYVTDKAELLRFYQNWQPQWTPGAKRLYANSSIGLFGALVVKPSGMSYEEAMTRRVLQPLKLAHTWITVPQSEQKNYAWGYREGKPVHVSPGQLDAEAYGVKSSVIDMARWVQANMDASHVQEKTLQQGIELAQSRYWRIGDMYQGLGWEMLNWPLKADSIINGSDSKVALAALPAVEVNPPAPAVKASWVHKTGSTGGFGSYVAFVPEKNLGIVMLANKSYPNPARVEAAWRILEKLQ'},
 'CARD_38': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-60',
  'Sequence': 'MLSRYSKTLAFAVVACTLAISTATAHAELVVRNDLKRVFDDAGVSGTFVLMDITADRTYVVDPARAARSIHPASTFKIPNSLIAFDTGAVRDDQEVLPYGGKPQPYEQWEHDMALPEAIRLSAVPIYQEVARRVGFERMQAYVDAFDYGNRQLGSAIDQFWLRGPLEISAFEEARFTSRMALKQLPVKPRTWDMVQRMLLIEQQGDAALYAKTGVATEYQPEIGWWAGWVERAGHVYAFALNIDMPREGDMAKRIPLGKQLMRALEVWPAP'},
 'CARD_39': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-90',
  'Sequence': 'MNIKALLLITSAIFISACSPYIVTANPNHSASKSDEKAEKIKNLFNEAHTTGVLVIQQGQTQQSYGNDLARASTEYVPASTFKMLNALIGLEHHKATTTEVFKWDGKKRLFPEWEKDMTLGDAMKASAIPVYQDLARRIGLELMSKEVKRVGYGNADIGTQVDNFWLVGPLKITPQQEAQFAYKLANKTLPFSQKVQDEVQSMLFIEEKNGNKIYAKSGWGWDVDPQVGWLTGWVVQPQGNIVAFSLNLEMKKGIPSSVRKEITYKSLEQLGIL'},
 'CARD_40': {'Drug Class': 'beta-lactam',
  'Name': 'SME-2',
  'Sequence': 'MSNKVNFKTASFLFSVCLALSAFNAHANKSDAAAKQIKKLEEDFDGRIGVFAIDTGSGNTFGYRSDERFPLCSSFKGFLAAAVLERVQQKKLDINQKVKYESRDLEYHSPITTKYKGSGMTLGDMASAALQYSDNGATNIIMERFLGGPEGMTKFMRSIGDNEFRLDRWELELNTAIPGDKRDTSTPKAVANSLNKLALGNVLNAKEKAIYQNWLKGNTTGDARIRASVPADWVVGDKTGSCGAYGTANDYAVIWPKNRAPLIVSIYTTRKSKDDKHSDKTIAEASRIAIQAID'},
 'CARD_41': {'Drug Class': 'aminoglycoside',
  'Name': 'AAC(3)-IIIc',
  'Sequence': 'MFSRWSKPLVLAAVTRASLAADLAALGLAAGDAVMVHAAVSKVGRLLDGPDTIIAALSDAGRPAGTILAYADWEARYEDLVDEDGRVPQEWREHIPPFDPRRSRAIRDNGVLPEFLRTTPGALRSGNPGASMVGLGARAEWFTADHPLDYGYGEGSPLARLVEAGGKVLMLGAPLDTLTLLHHAEHLADIPGKRIRRIEVPLATPTGTQWRMIEEFDTGDPIVEGLAEDYFAEIVTAFLAGGRGRQGLIGTAPSVLVDAAAITAFGVAWLESRFGSPSS'},
 'CARD_42': {'Drug Class': 'beta-lactam',
  'Name': 'OXY-2-2',
  'Sequence': 'MIKSSWRKIAMLAAAVPLLLASGALWASTDAIHQKLTDLEKRSGGRLGVALINTADNSQILYRGDERFAMCSTSKVMAAAAVLKQSESNKEVVNKRLEINAADLVVWSPITEKHLQSGMTLAELSAATLQYSDNTAMNLIIGYLGGPEKVTAFARSIGDATFRLDRTEPTLNTAIPGDERDTSTPLAMAESLRKLTLGDALGEQQRAQLVTWLKGNTTGGQSIRAGLPESWVVGDKTGAGDYGTTNDIAVIWPEDHAPLILVTYFTQPQQDAKNRKEVLAAAAKIVTEGL'},
 'CARD_43': {'Drug Class': 'beta-lactam',
  'Name': 'MOX-5',
  'Sequence': 'MQQRQSILWGALATLMWAGLAHAGDKAATDPLRPVVDASIRPLLKEHRIPGMAVAVLKDGKAHYFNYGVADRERAVGVSEQTLFEIGSVSKTLTATLGAYAVVQGGFELDDKASLFAPWLKGSAFDNITMGELATYSAGGLPLQFPEEVDSLEKMQAYYRQWTPAYSRGSHRQYANPSIGLFGYLAASSMKQPFDRLMEQTMLPGLGLYHTYLNVPEQPMGHYAYGYWKEDKPFRVTPAMLAEEPYGIKTSSADLLRFVKANISGVDNAAMQQAIDLTHQGQYAVGEMTQGLGWERYPYPVSEQTLLAGNSPAMIYNANPAAPAPAAAGHPVLFKKTGSTNGFGAYVAFVPAKGIGVVMLANRNYPNEGTLKAGHAILTQLAR'},
 'CARD_44': {'Drug Class': 'beta-lactam',
  'Name': 'TEM-34',
  'Sequence': 'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMVSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW'},
 'CARD_45': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-69',
  'Sequence': 'MNIKALLLITSAIFISACSPYIVTANPNHSASKSDDKAEKIKNLFNEAHTTGVLVIHQGQTQQSYGNDLARASTEYVPASTFKMLNALIGLEHHKATTTEVFKWDGEKRLFPEWEKNMTLGDAMKASAIPVYQDLARRIGLELMSKEVKRVGYGNADIGTQVDNFWLVGPLKITPQQEAQFAYKLANKTLPFSQKVQDEVQSMLFIEEKNGNKIYAKSGWGWDVNPQVGWLTGWVVQPQGNIVAFSLNLEMKKGIPSSVRKEITYKSLEQLGIL'},
 'CARD_46': {'Drug Class': 'beta-lactam',
  'Name': 'TEM-7',
  'Sequence': 'FFAAFCLPVFAHPETLVKVKDAEDKLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDSWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNR'},
 'CARD_47': {'Drug Class': 'beta-lactam',
  'Name': 'SHV-24',
  'Sequence': 'MRYIRLCIISLLATLPLAVHASPQPLEQIKLSESQLSGRVGMIEMDLASGRTLTAWRADERFPMMSTFKVVLCGAVLARVDAGDEQLERKIHYRQQDLVDYSPVSEKHLADGMTVGELCAAAITMSDNSAANLLLATVGGPAGLTAFLRQIGDNVTRLDRWETELNEALPGDARGTTTPASMAATLRKLLTSQRLSARSQRQLLQWMVDDRVAGPLIRSVLPAGWFIADKTGAGERGARGIVALLGPNNKAERIVVIYLRDTPASMAERNQQIAGIGAALIEHWQR'},
 'CARD_48': {'Drug Class': 'fluoroquinolone',
  'Name': 'QnrB47',
  'Sequence': 'MTLALVGEKIDRNRFTGEKVENSTFFNCDFSGADLSGTEFIGCQFYDRESQKGCNFSRAMLRDAIFKSCDLSMADFRNVSALGIEIRHCRAQGADFRGASFMNMITTRTWFCSAYITNTNLSYANFSKVVLEKCELWENRWMGTQVLGATFSGSDLSGGEFSTFDWRAANFTHCDLTNSELGDLDIRGVDLQGVKLDNYQASLLMERLGIAVIG'},
 'CARD_49': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-256',
  'Sequence': 'MKTFAAYVIIACLSSTALAGSITENTSWNKEFSAEAVNGVFVLCKSSSKSCATNDLARASKEYLPASTFKIPDAIIGLETGVIKNEHQVFKWDGKPRAMKQWERDLTLRGAIQVSAVPVFQQIAREVGEVRMQKYLKKFSYGNQNISGGIDKFWLEGQLRISAVNQVEFLESLYLNKLSASKENQLIVKEALVTEAAPEYLVHSKTGFSGVGTESNPGVAWWVGWVEKETEVYFFAFNMDIDNESKLPLRKSIPTKIMESEGIIGG'},
 'CARD_50': {'Drug Class': 'fluoroquinolone',
  'Name': 'QnrS6',
  'Sequence': 'METYRHTYRHHSFSHQDLSDITFTACTFIRCDFRRANLRDATFINCKFIEQGDIEGCHFDVADLRDASFQQCQLAMANFSNANCYGIELRECDLKGANFSRANFANQVSNRMYFCSAFITGCNLSYANMERVCLEKCELYENRWIGTHLAGASLKESDLSRGVFSEDVWGQFSLQGANLCHAELDGLDPRKVDTSGIKIASWQQEQLLEALGIVVFPD'},
 'CARD_51': {'Drug Class': 'beta-lactam',
  'Name': 'OXA-330',
  'Sequence': 'MYKKALIVATSILFLSACSSNLVKQHQIHSISANKSSEEIKSLFDQAQTTGVLVIKRGQTEEIYGNDLKRASTAYVPASTFKMLNALIGLEHHKATTTEVFKWNGQKRLFPDWEKDMTLGDAMKASAIPVYQELARRIGLDLMSKEVKRIGFGNANIGSKVDNFWLVGPLKITPQQETQFAYQLAHKTLPFSKNVQEQVQSMVFIEKKNGSKIYAKSGWGWDVEPQVGWLTGWVVQPQGEIVAFSLNLEMKKGTSSSIRKEIAYKGLEQLGIL'},
 'CARD_52': {'Drug Class': 'beta-lactam',
  'Name': 'CMY-42',
  'Sequence': 'MMKKSLCCALLLTASFSTFAAAKTEQQIADIVNRTITPLMQEQAIPGMAVAVIYQGKPYYFTWGKADIANNHPVTQQTLFELGSVSKTFNGVLGGDAIARGEIKLSDPVTKYWPELTGKQWQGIRLLHLATYTAGGLPLQIPDDVRDKAALLHFYQNWQPQWTPGAKRLYANSSIGLFGALAVKPSGMSYEEAMTRRVLQPLKLAHTWITVPQNEQKDYAWGYREGKPVHSSPGQLDAEAYGVKSSVIDMARWVQANMDASHVQEKTLQQGIALAQSRYWRIGDMYQGLGWEMLNWPLKADSIINGSDSKVALAALPAVEVNPPAPAVKASWVHKTGSTGGFGSYVAFVPEKNLGIVMLANKSYPNPVRVEAAWRILEKLQ'},
 'CARD_53': {'Drug Class': 'aminoglycoside',
  'Name': "AAC(6')-Ib",
  'Sequence': 'MTNSNDSVTLRLMTEHDLAMLYEWLNRSHIVEWWGGEEARPTLADVQEQYLPSVLAQESVTPYIAMLNGEPIGYAQSYVALGSGDGWWEEETDPGVRGIDQSLANASQLGKGLGTKLVRALVELLFNDPEVTKIQTDPSPSNLRAIRCYEKAGFEKQGTVTTPDGPAVYMVQTRQAFERTRSDA'},
 'CARD_54': {'Drug Class': 'beta-lactam',
  'Name': 'CMY-70',

In [21]:
Classes = pd.Series([MetaDict[key]["Drug Class"] for key, value in MetaDict.items()])

In [22]:
Classes.value_counts().head(10)

beta-lactam        25793
multidrug          13300
glycopeptide        8142
aminoglycoside      4926
bacitracin          4228
tetracycline        2923
MLS                 2577
na                  1290
chloramphenicol     1137
quinolone           1037
Name: count, dtype: int64

In [23]:
with open("../data/processed/MetaDict.json", "w+") as json_file  :
    json.dump(MetaDict, json_file, indent=4)